package setting;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import permintaan.DlgSuratIstirahatSakit;
import permintaan.DlgSuratJawabanKonsul;
import permintaan.DlgSuratKeteranganDisabilitas;
import permintaan.DlgSuratKeteranganDokter;
import permintaan.DlgSuratKeteranganNapza;
import permintaan.DlgSuratKeteranganRohani;
import permintaan.DlgSuratKeteranganSakit;
import permintaan.DlgSuratKonsulUnit;
import simrskhanza.DlgSuratKonsulRalan;
import simrskhanza.frmUtama;

/**
 *
 * @author dosen
 */
public class PanelMenuUtamaG extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private String versi = "";
    private int jmlmenu = 0, grid = 0, tinggi = 0, i = 0;
    private frmUtama formUtama;
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public PanelMenuUtamaG(frmUtama parent, boolean modal) {
        super(parent, modal);
        formUtama = parent;
        initComponents();
        aturTampilanTombol();

        versi = Sequel.cariIsi("select versi_update from history_update ORDER BY tgl_update desc, jam_update desc limit 1");        
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        internalFrame2 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TCari = new widget.TextBox();
        btnClear = new widget.Button();
        ChkInput = new widget.CekBox();
        scrollMenu = new widget.ScrollPane();
        FormMenu = new widget.PanelBiasa();
        btnSuratKonsulInternalPoli = new widget.ButtonBig();
        btnSuratKonsulUnitRanap = new widget.ButtonBig();
        btnSuratJawabanKonsulRanap = new widget.ButtonBig();
        btnSuratKeteranganDokter = new widget.ButtonBig();
        btnSuratKeteranganDisabilitas = new widget.ButtonBig();
        btnSuratKeteranganRohani = new widget.ButtonBig();
        btnSuratKeteranganNAPZA = new widget.ButtonBig();
        btnSuratIstirahatSakit = new widget.ButtonBig();
        btnSuratKeteranganSakit = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(12, 39));
        internalFrame2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cari Menu G :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(jLabel3);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        internalFrame2.add(TCari);

        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        btnClear.setGlassColor(new java.awt.Color(255, 255, 255));
        btnClear.setMinimumSize(new java.awt.Dimension(28, 23));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(30, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        internalFrame2.add(btnClear);

        ChkInput.setBorder(null);
        ChkInput.setForeground(new java.awt.Color(0, 0, 0));
        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setMnemonic('C');
        ChkInput.setSelected(true);
        ChkInput.setText("Pencarian");
        ChkInput.setToolTipText("Alt+C");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setOpaque(false);
        ChkInput.setPreferredSize(new java.awt.Dimension(100, 23));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        internalFrame2.add(ChkInput);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        scrollMenu.setName("scrollMenu"); // NOI18N
        scrollMenu.setPreferredSize(new java.awt.Dimension(102, 557));

        FormMenu.setBackground(new java.awt.Color(255, 255, 255));
        FormMenu.setBorder(null);
        FormMenu.setName("FormMenu"); // NOI18N
        FormMenu.setPreferredSize(new java.awt.Dimension(2400, 3240));
        FormMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        btnSuratKonsulInternalPoli.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKonsulInternalPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_TextEdit_37595.png"))); // NOI18N
        btnSuratKonsulInternalPoli.setText("Surat Konsul Internal Poliklinik");
        btnSuratKonsulInternalPoli.setIconTextGap(0);
        btnSuratKonsulInternalPoli.setName("btnSuratKonsulInternalPoli"); // NOI18N
        btnSuratKonsulInternalPoli.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKonsulInternalPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKonsulInternalPoliActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKonsulInternalPoli);

        btnSuratKonsulUnitRanap.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKonsulUnitRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/email_open.png"))); // NOI18N
        btnSuratKonsulUnitRanap.setText("Surat Konsul Antar Unit Ranap");
        btnSuratKonsulUnitRanap.setIconTextGap(0);
        btnSuratKonsulUnitRanap.setName("btnSuratKonsulUnitRanap"); // NOI18N
        btnSuratKonsulUnitRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKonsulUnitRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKonsulUnitRanapActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKonsulUnitRanap);

        btnSuratJawabanKonsulRanap.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratJawabanKonsulRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kwrite.png"))); // NOI18N
        btnSuratJawabanKonsulRanap.setText("Surat Jawaban Konsul Unit");
        btnSuratJawabanKonsulRanap.setIconTextGap(0);
        btnSuratJawabanKonsulRanap.setName("btnSuratJawabanKonsulRanap"); // NOI18N
        btnSuratJawabanKonsulRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratJawabanKonsulRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratJawabanKonsulRanapActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratJawabanKonsulRanap);

        btnSuratKeteranganDokter.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKeteranganDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_order-history_49596.png"))); // NOI18N
        btnSuratKeteranganDokter.setText("Surat Keterangan Dokter");
        btnSuratKeteranganDokter.setIconTextGap(0);
        btnSuratKeteranganDokter.setName("btnSuratKeteranganDokter"); // NOI18N
        btnSuratKeteranganDokter.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKeteranganDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKeteranganDokterActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKeteranganDokter);

        btnSuratKeteranganDisabilitas.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKeteranganDisabilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png"))); // NOI18N
        btnSuratKeteranganDisabilitas.setText("Surat Keterangan Dokter (Disabilitas)");
        btnSuratKeteranganDisabilitas.setIconTextGap(0);
        btnSuratKeteranganDisabilitas.setName("btnSuratKeteranganDisabilitas"); // NOI18N
        btnSuratKeteranganDisabilitas.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKeteranganDisabilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKeteranganDisabilitasActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKeteranganDisabilitas);

        btnSuratKeteranganRohani.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKeteranganRohani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_todo_list_add_17451.png"))); // NOI18N
        btnSuratKeteranganRohani.setText("Surat Keterangan Kes. Rohani");
        btnSuratKeteranganRohani.setIconTextGap(0);
        btnSuratKeteranganRohani.setName("btnSuratKeteranganRohani"); // NOI18N
        btnSuratKeteranganRohani.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKeteranganRohani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKeteranganRohaniActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKeteranganRohani);

        btnSuratKeteranganNAPZA.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKeteranganNAPZA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        btnSuratKeteranganNAPZA.setText("Surat Keterangan NAPZA");
        btnSuratKeteranganNAPZA.setIconTextGap(0);
        btnSuratKeteranganNAPZA.setName("btnSuratKeteranganNAPZA"); // NOI18N
        btnSuratKeteranganNAPZA.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKeteranganNAPZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKeteranganNAPZAActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKeteranganNAPZA);

        btnSuratIstirahatSakit.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratIstirahatSakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kwrite.png"))); // NOI18N
        btnSuratIstirahatSakit.setText("Surat Istirahat Sakit");
        btnSuratIstirahatSakit.setIconTextGap(0);
        btnSuratIstirahatSakit.setName("btnSuratIstirahatSakit"); // NOI18N
        btnSuratIstirahatSakit.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratIstirahatSakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratIstirahatSakitActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratIstirahatSakit);

        btnSuratKeteranganSakit.setForeground(new java.awt.Color(0, 0, 0));
        btnSuratKeteranganSakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_TextEdit_37595.png"))); // NOI18N
        btnSuratKeteranganSakit.setText("Surat Keterangan Sakit");
        btnSuratKeteranganSakit.setIconTextGap(0);
        btnSuratKeteranganSakit.setName("btnSuratKeteranganSakit"); // NOI18N
        btnSuratKeteranganSakit.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuratKeteranganSakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratKeteranganSakitActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuratKeteranganSakit);

        scrollMenu.setViewportView(FormMenu);

        internalFrame1.add(scrollMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampilkanMenu();
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        akses.setCopyData5("");
        TCari.setText("");
        TCari.requestFocus();        
    }//GEN-LAST:event_btnClearActionPerformed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        FormMenu.removeAll();

        isTampil();
        aturTampilanTombol();
        aturLayoutMenu();

        javax.swing.SwingUtilities.invokeLater(() -> {
            FormMenu.revalidate();
            FormMenu.repaint();
            scrollMenu.getViewport().revalidate();
            scrollMenu.revalidate();
            scrollMenu.repaint();
            scrollMenu.getVerticalScrollBar().setValue(0);
        });
    }//GEN-LAST:event_ChkInputActionPerformed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ChkInputActionPerformed(null);
            akses.setCopyData5(TCari.getText());
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void btnSuratKonsulInternalPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKonsulInternalPoliActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKonsulRalan aplikasi = new DlgSuratKonsulRalan(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKonsulInternalPoli.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKonsulInternalPoliActionPerformed

    private void btnSuratKonsulUnitRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKonsulUnitRanapActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKonsulUnit aplikasi = new DlgSuratKonsulUnit(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKonsulUnitRanap.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKonsulUnitRanapActionPerformed

    private void btnSuratJawabanKonsulRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratJawabanKonsulRanapActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratJawabanKonsul aplikasi = new DlgSuratJawabanKonsul(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.isiCombo();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratJawabanKonsulRanap.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratJawabanKonsulRanapActionPerformed

    private void btnSuratKeteranganDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKeteranganDokterActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKeteranganDokter aplikasi = new DlgSuratKeteranganDokter(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKeteranganDokter.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKeteranganDokterActionPerformed

    private void btnSuratKeteranganDisabilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKeteranganDisabilitasActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKeteranganDisabilitas aplikasi = new DlgSuratKeteranganDisabilitas(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.setTampil();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKeteranganDisabilitas.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKeteranganDisabilitasActionPerformed

    private void btnSuratKeteranganRohaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKeteranganRohaniActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKeteranganRohani aplikasi = new DlgSuratKeteranganRohani(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKeteranganRohani.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKeteranganRohaniActionPerformed

    private void btnSuratKeteranganNAPZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKeteranganNAPZAActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKeteranganNapza aplikasi = new DlgSuratKeteranganNapza(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKeteranganNAPZA.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKeteranganNAPZAActionPerformed

    private void btnSuratIstirahatSakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratIstirahatSakitActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratIstirahatSakit aplikasi = new DlgSuratIstirahatSakit(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratIstirahatSakit.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratIstirahatSakitActionPerformed

    private void btnSuratKeteranganSakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratKeteranganSakitActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuratKeteranganSakit aplikasi = new DlgSuratKeteranganSakit(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuratKeteranganSakit.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuratKeteranganSakitActionPerformed

    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox ChkInput;
    private widget.PanelBiasa FormMenu;
    public widget.TextBox TCari;
    private widget.Button btnClear;
    private widget.ButtonBig btnSuratIstirahatSakit;
    private widget.ButtonBig btnSuratJawabanKonsulRanap;
    private widget.ButtonBig btnSuratKeteranganDisabilitas;
    private widget.ButtonBig btnSuratKeteranganDokter;
    private widget.ButtonBig btnSuratKeteranganNAPZA;
    private widget.ButtonBig btnSuratKeteranganRohani;
    private widget.ButtonBig btnSuratKeteranganSakit;
    private widget.ButtonBig btnSuratKonsulInternalPoli;
    private widget.ButtonBig btnSuratKonsulUnitRanap;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel3;
    private widget.ScrollPane scrollMenu;
    // End of variables declaration//GEN-END:variables

    private void isTampil() {
        jmlmenu = 0;
        String cari = TCari.getText().toLowerCase().trim();

        if (akses.gettindakan_ralan() && btnSuratKonsulInternalPoli.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKonsulInternalPoli);
            jmlmenu++;
        }
        
        if (akses.getpermintaan_lab() && btnSuratKonsulUnitRanap.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKonsulUnitRanap);
            jmlmenu++;
        }
        
        if (akses.getpermintaan_lab() && btnSuratJawabanKonsulRanap.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratJawabanKonsulRanap);
            jmlmenu++;
        }
        
        if (akses.getsurat_keterangan_kir_mcu() && btnSuratKeteranganDokter.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKeteranganDokter);
            jmlmenu++;
        }
        
        if (akses.getsurat_keterangan_kir_mcu() && btnSuratKeteranganDisabilitas.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKeteranganDisabilitas);
            jmlmenu++;
        }
        
        if (akses.getsurat_keterangan_kir_mcu() && btnSuratKeteranganRohani.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKeteranganRohani);
            jmlmenu++;
        }
        
        if (akses.getsurat_keterangan_kir_mcu() && btnSuratKeteranganNAPZA.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKeteranganNAPZA);
            jmlmenu++;
        }
        
        if (akses.getsurat_sakit() && btnSuratIstirahatSakit.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratIstirahatSakit);
            jmlmenu++;
        }
        
        if (akses.getsurat_sakit() && btnSuratKeteranganSakit.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuratKeteranganSakit);
            jmlmenu++;
        }
    }
    
    public JPanel getFormMenu() {
        return FormMenu;
    }

    public javax.swing.JPanel getPanelUtama() {
        return internalFrame1;
    }

    public void tampilkanMenu() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            ChkInputActionPerformed(null);

            javax.swing.Timer timer
                    = new javax.swing.Timer(100, e -> {

                        ((javax.swing.Timer) e.getSource()).stop();

                        ChkInputActionPerformed(null);

                        scrollMenu.getVerticalScrollBar().setValue(0);
                    });

            timer.setRepeats(false);
            timer.start();
        });
    }

    public void terapkanHakAkses() {
        FormMenu.removeAll();
        jmlmenu = 0;

        if (akses.gettindakan_ralan() == true) {
            FormMenu.add(btnSuratKonsulInternalPoli);
            jmlmenu++;
        }

        if (akses.getpermintaan_lab() == true) {
            FormMenu.add(btnSuratKonsulUnitRanap);
            jmlmenu++;
        }

        if (akses.getpermintaan_lab() == true) {
            FormMenu.add(btnSuratJawabanKonsulRanap);
            jmlmenu++;
        }

        if (akses.getsurat_keterangan_kir_mcu() == true) {
            FormMenu.add(btnSuratKeteranganDokter);
            jmlmenu++;
        }

        if (akses.getsurat_keterangan_kir_mcu() == true) {
            FormMenu.add(btnSuratKeteranganDisabilitas);
            jmlmenu++;
        }

        if (akses.getsurat_keterangan_kir_mcu() == true) {
            FormMenu.add(btnSuratKeteranganRohani);
            jmlmenu++;
        }

        if (akses.getsurat_keterangan_kir_mcu() == true) {
            FormMenu.add(btnSuratKeteranganNAPZA);
            jmlmenu++;
        }

        if (akses.getsurat_sakit() == true) {
            FormMenu.add(btnSuratIstirahatSakit);
            jmlmenu++;
        }

        if (akses.getsurat_sakit() == true) {
            FormMenu.add(btnSuratKeteranganSakit);
            jmlmenu++;
        }

        aturLayoutMenu();

        FormMenu.revalidate();
        FormMenu.repaint();
    }
    
    private void aturLayoutMenu() {
        int lebarViewport = scrollMenu.getViewport().getExtentSize().width;
        int tinggiViewport = scrollMenu.getViewport().getExtentSize().height;

        if (lebarViewport <= 0) {
            lebarViewport = scrollMenu.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport = scrollMenu.getHeight();
        }

        if (lebarViewport <= 0) {
            lebarViewport = internalFrame1.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport
                    = internalFrame1.getHeight() - internalFrame2.getHeight();
        }

        /*
     * Sama seperti menu frmUtama:
     * jumlah menu menentukan jumlah kolom.
         */
        if (jmlmenu <= 1) {
            grid = 1;
        } else if (jmlmenu <= 4) {
            grid = 2;
        } else if (jmlmenu <= 9) {
            grid = 3;
        } else if (jmlmenu <= 16) {
            grid = 4;
        } else {
            grid = 5;
        }

        int tinggiTombol = 120;
        int jarakHorizontal = 5;
        int jarakVertikal = 35;

        int jumlahBaris = (int) Math.ceil(
                (double) jmlmenu / grid
        );

        int tinggiIsi
                = (jumlahBaris * tinggiTombol)
                + (Math.max(0, jumlahBaris - 1) * jarakVertikal)
                + 20;

        /*
     * Jika isi lebih tinggi dari viewport,
     * scrollbar otomatis muncul.
         */
        tinggi = Math.max(tinggiViewport, tinggiIsi);

        FormMenu.setLayout(new GridLayout(
                0,
                grid,
                jarakHorizontal,
                jarakVertikal
        ));

        Dimension ukuranMenu = new Dimension(
                Math.max(lebarViewport - 10, 200),
                tinggi
        );

        FormMenu.setPreferredSize(ukuranMenu);
        FormMenu.setMinimumSize(ukuranMenu);

        scrollMenu.setVerticalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        );

        scrollMenu.setHorizontalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
        );

        scrollMenu.getVerticalScrollBar().setUnitIncrement(16);
        scrollMenu.getVerticalScrollBar().setBlockIncrement(120);

        FormMenu.revalidate();
        FormMenu.repaint();

        scrollMenu.getViewport().revalidate();
        scrollMenu.getViewport().repaint();

        scrollMenu.revalidate();
        scrollMenu.repaint();
    }

    private void aturTampilanTombol() {
        java.awt.Component[] komponen = FormMenu.getComponents();

        for (java.awt.Component komponenMenu : komponen) {
            if (komponenMenu instanceof widget.ButtonBig) {
                widget.ButtonBig tombol
                        = (widget.ButtonBig) komponenMenu;

                tombol.setHorizontalAlignment(
                        javax.swing.SwingConstants.CENTER
                );

                tombol.setVerticalAlignment(
                        javax.swing.SwingConstants.CENTER
                );
            }
        }
    }
}
