package setting;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import inventory.DlgAturanPakai;
import inventory.DlgBarang;
import inventory.DlgCariJenis;
import inventory.DlgDaftarPermintaanResep;
import inventory.DlgDaruratStok;
import inventory.DlgGolongan;
import inventory.DlgIndustriFarmasi;
import inventory.DlgInputStok;
import inventory.DlgKategori;
import inventory.DlgKonversi;
import inventory.DlgMutasiBarang;
import inventory.DlgObatPerTanggal;
import inventory.DlgPelaksanaPemberiObat;
import inventory.DlgPembelian;
import inventory.DlgPemberianObatPasien;
import inventory.DlgPemesanan;
import inventory.DlgPengambilanUTD;
import inventory.DlgPenjualan;
import inventory.DlgPenjualanPerTanggal;
import inventory.DlgPiutang;
import inventory.DlgProyeksiBeriObat;
import inventory.DlgProyeksiBeriObat2;
import inventory.DlgProyeksiJual;
import inventory.DlgResepIterObat;
import inventory.DlgReturBeli;
import inventory.DlgReturJual;
import inventory.DlgReturObatPasien;
import inventory.DlgReturPiutang;
import inventory.DlgRiwayatBarangMedis;
import inventory.DlgSatuan;
import inventory.DlgSirkulasiBarang;
import inventory.DlgSirkulasiBarang2;
import inventory.DlgStokPasien;
import inventory.DlgSuplier;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.util.Date;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import laporan.DlgLaporanFarmasi;
import rekammedis.RMRekonsiliasiObat;
import simrskhanza.DlgDashboardEresep;
import simrskhanza.DlgDashboardEresepRanap;
import simrskhanza.frmUtama;


/**
 *
 * @author dosen
 */
public class PanelMenuUtamaD extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private String versi = "";
    private int jmlmenu = 0, grid = 0, tinggi = 0, i = 0;
    private frmUtama formUtama;
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public PanelMenuUtamaD(frmUtama parent, boolean modal) {
        super(parent, modal);
        formUtama = parent;
        initComponents();
        aturTampilanTombol();

        versi = Sequel.cariIsi("select versi_update from history_update ORDER BY tgl_update desc, jam_update desc limit 1");        
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        internalFrame2 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TCari = new widget.TextBox();
        btnClear = new widget.Button();
        ChkInput = new widget.CekBox();
        scrollMenu = new widget.ScrollPane();
        FormMenu = new widget.PanelBiasa();
        btnRekonsiliasiObat = new widget.ButtonBig();
        btnPemberianObat = new widget.ButtonBig();
        btnPetugasPelaksanaPemberianObat = new widget.ButtonBig();
        btnIndustriFarmasi = new widget.ButtonBig();
        btnSuplier = new widget.ButtonBig();
        btnSatuan = new widget.ButtonBig();
        btnKonversi = new widget.ButtonBig();
        btnDashboardeResepRalan = new widget.ButtonBig();
        btnDashboardeResepRanap = new widget.ButtonBig();
        btnJnsBarang = new widget.ButtonBig();
        btnKategoriBarang = new widget.ButtonBig();
        btnGolonganBarang = new widget.ButtonBig();
        btnObat = new widget.ButtonBig();
        btnResepIterBpjs = new widget.ButtonBig();
        btnMasterAturanPakai = new widget.ButtonBig();
        btnOpname = new widget.ButtonBig();
        btnMutasiBarang = new widget.ButtonBig();
        btnLaporanFarmasi = new widget.ButtonBig();
        btnStokObatPasien = new widget.ButtonBig();
        btnPembelian = new widget.ButtonBig();
        btnPemesanan = new widget.ButtonBig();
        btnPenjualan = new widget.ButtonBig();
        btnDaftarPermintaanResep = new widget.ButtonBig();
        btnPiutang = new widget.ButtonBig();
        btnReturBeli = new widget.ButtonBig();
        btnReturJual = new widget.ButtonBig();
        btnReturPasien = new widget.ButtonBig();
        btnReturPiutang = new widget.ButtonBig();
        btnPengambilanUTD = new widget.ButtonBig();
        btnKeuntungan = new widget.ButtonBig();
        btnKeuntunganObatRanap = new widget.ButtonBig();
        btnKeuntunganObat2 = new widget.ButtonBig();
        btnSirkulasi = new widget.ButtonBig();
        btnSirkulasi2 = new widget.ButtonBig();
        btnObatPerTanggal = new widget.ButtonBig();
        btnPenjualanPerTanggal = new widget.ButtonBig();
        btnRiwayatBarangMedis = new widget.ButtonBig();
        btnDaruratStok = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(12, 39));
        internalFrame2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cari Menu D :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(jLabel3);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        internalFrame2.add(TCari);

        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        btnClear.setGlassColor(new java.awt.Color(255, 255, 255));
        btnClear.setMinimumSize(new java.awt.Dimension(28, 23));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(30, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        internalFrame2.add(btnClear);

        ChkInput.setBorder(null);
        ChkInput.setForeground(new java.awt.Color(0, 0, 0));
        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setSelected(true);
        ChkInput.setText("Pencarian");
        ChkInput.setToolTipText("Alt+C");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setOpaque(false);
        ChkInput.setPreferredSize(new java.awt.Dimension(100, 23));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        internalFrame2.add(ChkInput);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        scrollMenu.setName("scrollMenu"); // NOI18N
        scrollMenu.setPreferredSize(new java.awt.Dimension(102, 557));

        FormMenu.setBackground(new java.awt.Color(255, 255, 255));
        FormMenu.setBorder(null);
        FormMenu.setName("FormMenu"); // NOI18N
        FormMenu.setPreferredSize(new java.awt.Dimension(2400, 3240));
        FormMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        btnRekonsiliasiObat.setForeground(new java.awt.Color(0, 0, 0));
        btnRekonsiliasiObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_pot_pills.png"))); // NOI18N
        btnRekonsiliasiObat.setText("Rekonsiliasi Obat");
        btnRekonsiliasiObat.setIconTextGap(0);
        btnRekonsiliasiObat.setName("btnRekonsiliasiObat"); // NOI18N
        btnRekonsiliasiObat.setPreferredSize(new java.awt.Dimension(200, 90));
        btnRekonsiliasiObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekonsiliasiObatActionPerformed(evt);
            }
        });
        FormMenu.add(btnRekonsiliasiObat);

        btnPemberianObat.setForeground(new java.awt.Color(0, 0, 0));
        btnPemberianObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481001686_injection_blood.png"))); // NOI18N
        btnPemberianObat.setText("Pemberian Obat Pasien");
        btnPemberianObat.setIconTextGap(0);
        btnPemberianObat.setName("btnPemberianObat"); // NOI18N
        btnPemberianObat.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPemberianObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemberianObatActionPerformed(evt);
            }
        });
        FormMenu.add(btnPemberianObat);

        btnPetugasPelaksanaPemberianObat.setForeground(new java.awt.Color(0, 0, 0));
        btnPetugasPelaksanaPemberianObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/surgeon.png"))); // NOI18N
        btnPetugasPelaksanaPemberianObat.setText("Petugas Pelaksana Pemberian Obat");
        btnPetugasPelaksanaPemberianObat.setIconTextGap(0);
        btnPetugasPelaksanaPemberianObat.setName("btnPetugasPelaksanaPemberianObat"); // NOI18N
        btnPetugasPelaksanaPemberianObat.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPetugasPelaksanaPemberianObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetugasPelaksanaPemberianObatActionPerformed(evt);
            }
        });
        FormMenu.add(btnPetugasPelaksanaPemberianObat);

        btnIndustriFarmasi.setForeground(new java.awt.Color(0, 0, 0));
        btnIndustriFarmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486910_company.png"))); // NOI18N
        btnIndustriFarmasi.setText("Industri Farmasi");
        btnIndustriFarmasi.setIconTextGap(0);
        btnIndustriFarmasi.setName("btnIndustriFarmasi"); // NOI18N
        btnIndustriFarmasi.setPreferredSize(new java.awt.Dimension(200, 90));
        btnIndustriFarmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndustriFarmasiActionPerformed(evt);
            }
        });
        FormMenu.add(btnIndustriFarmasi);

        btnSuplier.setForeground(new java.awt.Color(0, 0, 0));
        btnSuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1485357959_truck.png"))); // NOI18N
        btnSuplier.setText("Suplier Obat/Alkes/BHP");
        btnSuplier.setIconTextGap(0);
        btnSuplier.setName("btnSuplier"); // NOI18N
        btnSuplier.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuplierActionPerformed(evt);
            }
        });
        FormMenu.add(btnSuplier);

        btnSatuan.setForeground(new java.awt.Color(0, 0, 0));
        btnSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bag1.png"))); // NOI18N
        btnSatuan.setText("Satuan Barang");
        btnSatuan.setIconTextGap(0);
        btnSatuan.setName("btnSatuan"); // NOI18N
        btnSatuan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuanActionPerformed(evt);
            }
        });
        FormMenu.add(btnSatuan);

        btnKonversi.setForeground(new java.awt.Color(0, 0, 0));
        btnKonversi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/ark2.png"))); // NOI18N
        btnKonversi.setText("Konversi Satuan");
        btnKonversi.setIconTextGap(0);
        btnKonversi.setName("btnKonversi"); // NOI18N
        btnKonversi.setPreferredSize(new java.awt.Dimension(200, 90));
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        FormMenu.add(btnKonversi);

        btnDashboardeResepRalan.setForeground(new java.awt.Color(0, 0, 0));
        btnDashboardeResepRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/monitor.png"))); // NOI18N
        btnDashboardeResepRalan.setText("Dashboard e-Resep Rawat Jalan");
        btnDashboardeResepRalan.setIconTextGap(0);
        btnDashboardeResepRalan.setName("btnDashboardeResepRalan"); // NOI18N
        btnDashboardeResepRalan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDashboardeResepRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardeResepRalanActionPerformed(evt);
            }
        });
        FormMenu.add(btnDashboardeResepRalan);

        btnDashboardeResepRanap.setForeground(new java.awt.Color(0, 0, 0));
        btnDashboardeResepRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/monitor_hijau.png"))); // NOI18N
        btnDashboardeResepRanap.setText("Dashboard e-Resep Rawat Inap");
        btnDashboardeResepRanap.setIconTextGap(0);
        btnDashboardeResepRanap.setName("btnDashboardeResepRanap"); // NOI18N
        btnDashboardeResepRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDashboardeResepRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardeResepRanapActionPerformed(evt);
            }
        });
        FormMenu.add(btnDashboardeResepRanap);

        btnJnsBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnJnsBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/Card_file.png"))); // NOI18N
        btnJnsBarang.setText("Jenis Obat, Alkes & BHP");
        btnJnsBarang.setIconTextGap(0);
        btnJnsBarang.setName("btnJnsBarang"); // NOI18N
        btnJnsBarang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnJnsBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJnsBarangActionPerformed(evt);
            }
        });
        FormMenu.add(btnJnsBarang);

        btnKategoriBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnKategoriBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/address-book.png"))); // NOI18N
        btnKategoriBarang.setText("Kategori Obat, Alkes & BHP");
        btnKategoriBarang.setIconTextGap(0);
        btnKategoriBarang.setName("btnKategoriBarang"); // NOI18N
        btnKategoriBarang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnKategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriBarangActionPerformed(evt);
            }
        });
        FormMenu.add(btnKategoriBarang);

        btnGolonganBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnGolonganBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485894_add-notes.png"))); // NOI18N
        btnGolonganBarang.setText("Golongan Obat, Alkes & BHP");
        btnGolonganBarang.setIconTextGap(0);
        btnGolonganBarang.setName("btnGolonganBarang"); // NOI18N
        btnGolonganBarang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnGolonganBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolonganBarangActionPerformed(evt);
            }
        });
        FormMenu.add(btnGolonganBarang);

        btnObat.setForeground(new java.awt.Color(0, 0, 0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360815855_laboratory.png"))); // NOI18N
        btnObat.setText("Obat, Alkes & BHP");
        btnObat.setIconTextGap(0);
        btnObat.setName("btnObat"); // NOI18N
        btnObat.setPreferredSize(new java.awt.Dimension(200, 90));
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        FormMenu.add(btnObat);

        btnResepIterBpjs.setForeground(new java.awt.Color(0, 0, 0));
        btnResepIterBpjs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487125_system-restart-panel.png"))); // NOI18N
        btnResepIterBpjs.setText("Resep Obat Iter BPJS");
        btnResepIterBpjs.setIconTextGap(0);
        btnResepIterBpjs.setName("btnResepIterBpjs"); // NOI18N
        btnResepIterBpjs.setPreferredSize(new java.awt.Dimension(200, 90));
        btnResepIterBpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResepIterBpjsActionPerformed(evt);
            }
        });
        FormMenu.add(btnResepIterBpjs);

        btnMasterAturanPakai.setForeground(new java.awt.Color(0, 0, 0));
        btnMasterAturanPakai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485030_receipt.png"))); // NOI18N
        btnMasterAturanPakai.setText("Master Aturan Pakai");
        btnMasterAturanPakai.setIconTextGap(0);
        btnMasterAturanPakai.setName("btnMasterAturanPakai"); // NOI18N
        btnMasterAturanPakai.setPreferredSize(new java.awt.Dimension(200, 90));
        btnMasterAturanPakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterAturanPakaiActionPerformed(evt);
            }
        });
        FormMenu.add(btnMasterAturanPakai);

        btnOpname.setForeground(new java.awt.Color(0, 0, 0));
        btnOpname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487078_shipping.png"))); // NOI18N
        btnOpname.setText("Stok Opname Obat & BHP");
        btnOpname.setIconTextGap(0);
        btnOpname.setName("btnOpname"); // NOI18N
        btnOpname.setPreferredSize(new java.awt.Dimension(200, 90));
        btnOpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpnameActionPerformed(evt);
            }
        });
        FormMenu.add(btnOpname);

        btnMutasiBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnMutasiBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        btnMutasiBarang.setText("Mutasi Obat & BHP");
        btnMutasiBarang.setIconTextGap(0);
        btnMutasiBarang.setName("btnMutasiBarang"); // NOI18N
        btnMutasiBarang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnMutasiBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutasiBarangActionPerformed(evt);
            }
        });
        FormMenu.add(btnMutasiBarang);

        btnLaporanFarmasi.setForeground(new java.awt.Color(0, 0, 0));
        btnLaporanFarmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        btnLaporanFarmasi.setText("Laporan Farmasi");
        btnLaporanFarmasi.setIconTextGap(0);
        btnLaporanFarmasi.setName("btnLaporanFarmasi"); // NOI18N
        btnLaporanFarmasi.setPreferredSize(new java.awt.Dimension(200, 90));
        btnLaporanFarmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanFarmasiActionPerformed(evt);
            }
        });
        FormMenu.add(btnLaporanFarmasi);

        btnStokObatPasien.setForeground(new java.awt.Color(0, 0, 0));
        btnStokObatPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487078_shipping.png"))); // NOI18N
        btnStokObatPasien.setText("Stok Obat Pasien");
        btnStokObatPasien.setIconTextGap(0);
        btnStokObatPasien.setName("btnStokObatPasien"); // NOI18N
        btnStokObatPasien.setPreferredSize(new java.awt.Dimension(200, 90));
        btnStokObatPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokObatPasienActionPerformed(evt);
            }
        });
        FormMenu.add(btnStokObatPasien);

        btnPembelian.setForeground(new java.awt.Color(0, 0, 0));
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487067_calculator.png"))); // NOI18N
        btnPembelian.setText("Pengadaan Obat & BHP");
        btnPembelian.setIconTextGap(0);
        btnPembelian.setName("btnPembelian"); // NOI18N
        btnPembelian.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });
        FormMenu.add(btnPembelian);

        btnPemesanan.setForeground(new java.awt.Color(0, 0, 0));
        btnPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kwrite.png"))); // NOI18N
        btnPemesanan.setText("Pemesanan Obat & BHP");
        btnPemesanan.setIconTextGap(0);
        btnPemesanan.setName("btnPemesanan"); // NOI18N
        btnPemesanan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });
        FormMenu.add(btnPemesanan);

        btnPenjualan.setForeground(new java.awt.Color(0, 0, 0));
        btnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/cashbox.png"))); // NOI18N
        btnPenjualan.setText("Penjualan Obat & BHP");
        btnPenjualan.setIconTextGap(0);
        btnPenjualan.setName("btnPenjualan"); // NOI18N
        btnPenjualan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });
        FormMenu.add(btnPenjualan);

        btnDaftarPermintaanResep.setForeground(new java.awt.Color(0, 0, 0));
        btnDaftarPermintaanResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485894_add-notes.png"))); // NOI18N
        btnDaftarPermintaanResep.setText("Daftar Resep Dokter");
        btnDaftarPermintaanResep.setIconTextGap(0);
        btnDaftarPermintaanResep.setName("btnDaftarPermintaanResep"); // NOI18N
        btnDaftarPermintaanResep.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDaftarPermintaanResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPermintaanResepActionPerformed(evt);
            }
        });
        FormMenu.add(btnDaftarPermintaanResep);

        btnPiutang.setForeground(new java.awt.Color(0, 0, 0));
        btnPiutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist.png"))); // NOI18N
        btnPiutang.setText("Piutang Obat & BHP");
        btnPiutang.setIconTextGap(0);
        btnPiutang.setName("btnPiutang"); // NOI18N
        btnPiutang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiutangActionPerformed(evt);
            }
        });
        FormMenu.add(btnPiutang);

        btnReturBeli.setForeground(new java.awt.Color(0, 0, 0));
        btnReturBeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        btnReturBeli.setText("Retur Ke Suplier");
        btnReturBeli.setIconTextGap(0);
        btnReturBeli.setName("btnReturBeli"); // NOI18N
        btnReturBeli.setPreferredSize(new java.awt.Dimension(200, 90));
        btnReturBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturBeliActionPerformed(evt);
            }
        });
        FormMenu.add(btnReturBeli);

        btnReturJual.setForeground(new java.awt.Color(0, 0, 0));
        btnReturJual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486142_shopping_cart.png"))); // NOI18N
        btnReturJual.setText("Retur Dari Pembeli");
        btnReturJual.setIconTextGap(0);
        btnReturJual.setName("btnReturJual"); // NOI18N
        btnReturJual.setPreferredSize(new java.awt.Dimension(200, 90));
        btnReturJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturJualActionPerformed(evt);
            }
        });
        FormMenu.add(btnReturJual);

        btnReturPasien.setForeground(new java.awt.Color(0, 0, 0));
        btnReturPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360815295_medical_case.png"))); // NOI18N
        btnReturPasien.setText("Retur Obat Ranap");
        btnReturPasien.setIconTextGap(0);
        btnReturPasien.setName("btnReturPasien"); // NOI18N
        btnReturPasien.setPreferredSize(new java.awt.Dimension(200, 90));
        btnReturPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturPasienActionPerformed(evt);
            }
        });
        FormMenu.add(btnReturPasien);

        btnReturPiutang.setForeground(new java.awt.Color(0, 0, 0));
        btnReturPiutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/custom-reports.png"))); // NOI18N
        btnReturPiutang.setText("Retur Piutang Pembeli");
        btnReturPiutang.setIconTextGap(0);
        btnReturPiutang.setName("btnReturPiutang"); // NOI18N
        btnReturPiutang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnReturPiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturPiutangActionPerformed(evt);
            }
        });
        FormMenu.add(btnReturPiutang);

        btnPengambilanUTD.setForeground(new java.awt.Color(0, 0, 0));
        btnPengambilanUTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487078_shipping.png"))); // NOI18N
        btnPengambilanUTD.setText("Pengambilan BHP UTD");
        btnPengambilanUTD.setIconTextGap(0);
        btnPengambilanUTD.setName("btnPengambilanUTD"); // NOI18N
        btnPengambilanUTD.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPengambilanUTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengambilanUTDActionPerformed(evt);
            }
        });
        FormMenu.add(btnPengambilanUTD);

        btnKeuntungan.setForeground(new java.awt.Color(0, 0, 0));
        btnKeuntungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/coins.png"))); // NOI18N
        btnKeuntungan.setText("Keuntungan Penjualan");
        btnKeuntungan.setIconTextGap(0);
        btnKeuntungan.setName("btnKeuntungan"); // NOI18N
        btnKeuntungan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnKeuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeuntunganActionPerformed(evt);
            }
        });
        FormMenu.add(btnKeuntungan);

        btnKeuntunganObatRanap.setForeground(new java.awt.Color(0, 0, 0));
        btnKeuntunganObatRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/coins.png"))); // NOI18N
        btnKeuntunganObatRanap.setText("Keuntungan Beri Obat ");
        btnKeuntunganObatRanap.setIconTextGap(0);
        btnKeuntunganObatRanap.setName("btnKeuntunganObatRanap"); // NOI18N
        btnKeuntunganObatRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        btnKeuntunganObatRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeuntunganObatRanapActionPerformed(evt);
            }
        });
        FormMenu.add(btnKeuntunganObatRanap);

        btnKeuntunganObat2.setForeground(new java.awt.Color(0, 0, 0));
        btnKeuntunganObat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/coins.png"))); // NOI18N
        btnKeuntunganObat2.setText("Keuntungan Beri Obat 2");
        btnKeuntunganObat2.setIconTextGap(0);
        btnKeuntunganObat2.setName("btnKeuntunganObat2"); // NOI18N
        btnKeuntunganObat2.setPreferredSize(new java.awt.Dimension(200, 90));
        btnKeuntunganObat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeuntunganObat2ActionPerformed(evt);
            }
        });
        FormMenu.add(btnKeuntunganObat2);

        btnSirkulasi.setForeground(new java.awt.Color(0, 0, 0));
        btnSirkulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487125_system-restart-panel.png"))); // NOI18N
        btnSirkulasi.setText("Sirkulasi Obat, Alkes & BHP");
        btnSirkulasi.setIconTextGap(0);
        btnSirkulasi.setName("btnSirkulasi"); // NOI18N
        btnSirkulasi.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSirkulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSirkulasiActionPerformed(evt);
            }
        });
        FormMenu.add(btnSirkulasi);

        btnSirkulasi2.setForeground(new java.awt.Color(0, 0, 0));
        btnSirkulasi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487125_system-restart-panel.png"))); // NOI18N
        btnSirkulasi2.setText("Sirkulasi Obat, Alkes & BHP 2");
        btnSirkulasi2.setIconTextGap(0);
        btnSirkulasi2.setName("btnSirkulasi2"); // NOI18N
        btnSirkulasi2.setPreferredSize(new java.awt.Dimension(200, 90));
        btnSirkulasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSirkulasi2ActionPerformed(evt);
            }
        });
        FormMenu.add(btnSirkulasi2);

        btnObatPerTanggal.setForeground(new java.awt.Color(0, 0, 0));
        btnObatPerTanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485865_schedule.png"))); // NOI18N
        btnObatPerTanggal.setText("Obat/Alkes/BHP Per Tanggal");
        btnObatPerTanggal.setIconTextGap(0);
        btnObatPerTanggal.setName("btnObatPerTanggal"); // NOI18N
        btnObatPerTanggal.setPreferredSize(new java.awt.Dimension(200, 90));
        btnObatPerTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatPerTanggalActionPerformed(evt);
            }
        });
        FormMenu.add(btnObatPerTanggal);

        btnPenjualanPerTanggal.setForeground(new java.awt.Color(0, 0, 0));
        btnPenjualanPerTanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485865_schedule.png"))); // NOI18N
        btnPenjualanPerTanggal.setText("Penjualan Bebas Per Tanggal");
        btnPenjualanPerTanggal.setIconTextGap(0);
        btnPenjualanPerTanggal.setName("btnPenjualanPerTanggal"); // NOI18N
        btnPenjualanPerTanggal.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPenjualanPerTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanPerTanggalActionPerformed(evt);
            }
        });
        FormMenu.add(btnPenjualanPerTanggal);

        btnRiwayatBarangMedis.setForeground(new java.awt.Color(0, 0, 0));
        btnRiwayatBarangMedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnRiwayatBarangMedis.setText("Riwayat Obat, Alkes & BHP");
        btnRiwayatBarangMedis.setIconTextGap(0);
        btnRiwayatBarangMedis.setName("btnRiwayatBarangMedis"); // NOI18N
        btnRiwayatBarangMedis.setPreferredSize(new java.awt.Dimension(200, 90));
        btnRiwayatBarangMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatBarangMedisActionPerformed(evt);
            }
        });
        FormMenu.add(btnRiwayatBarangMedis);

        btnDaruratStok.setForeground(new java.awt.Color(0, 0, 0));
        btnDaruratStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360487078_shipping.png"))); // NOI18N
        btnDaruratStok.setText("Darurat Stok");
        btnDaruratStok.setIconTextGap(0);
        btnDaruratStok.setName("btnDaruratStok"); // NOI18N
        btnDaruratStok.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDaruratStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaruratStokActionPerformed(evt);
            }
        });
        FormMenu.add(btnDaruratStok);

        scrollMenu.setViewportView(FormMenu);

        internalFrame1.add(scrollMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampilkanMenu();
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        akses.setCopyData5("");
        TCari.setText("");
        TCari.requestFocus();        
    }//GEN-LAST:event_btnClearActionPerformed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        FormMenu.removeAll();

        isTampil();
        aturTampilanTombol();
        aturLayoutMenu();

        javax.swing.SwingUtilities.invokeLater(() -> {
            FormMenu.revalidate();
            FormMenu.repaint();
            scrollMenu.getViewport().revalidate();
            scrollMenu.revalidate();
            scrollMenu.repaint();
            scrollMenu.getVerticalScrollBar().setValue(0);
        });
    }//GEN-LAST:event_ChkInputActionPerformed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ChkInputActionPerformed(null);
            akses.setCopyData5(TCari.getText());
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void btnRekonsiliasiObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekonsiliasiObatActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            RMRekonsiliasiObat aplikasi = new RMRekonsiliasiObat(formUtama, false);
            aplikasi.isCek();
            aplikasi.emptTeks();
            aplikasi.emptTeksRiwayatIGD();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnRekonsiliasiObat.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnRekonsiliasiObatActionPerformed

    private void btnPemberianObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemberianObatActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPemberianObatPasien aplikasi = new DlgPemberianObatPasien(formUtama, false);
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPemberianObat.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPemberianObatActionPerformed

    private void btnPetugasPelaksanaPemberianObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetugasPelaksanaPemberianObatActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPelaksanaPemberiObat aplikasi = new DlgPelaksanaPemberiObat(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPetugasPelaksanaPemberianObat.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPetugasPelaksanaPemberianObatActionPerformed

    private void btnIndustriFarmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndustriFarmasiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgIndustriFarmasi suplier = new DlgIndustriFarmasi(formUtama, false);
            suplier.isCek();
            suplier.emptTeks();
            suplier.awalData();
            formUtama.tampilkanDialogDiPanelUtama(suplier);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnIndustriFarmasi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnIndustriFarmasiActionPerformed

    private void btnSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuplierActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSuplier suplier = new DlgSuplier(formUtama, false);
            suplier.isCek();
            suplier.emptTeks();
            suplier.awalData();
            formUtama.tampilkanDialogDiPanelUtama(suplier);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSuplier.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSuplierActionPerformed

    private void btnSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuanActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSatuan satuan = new DlgSatuan(formUtama, false);
            satuan.emptTeks();
            satuan.awalData();
            formUtama.tampilkanDialogDiPanelUtama(satuan);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSatuan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSatuanActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgKonversi konversi = new DlgKonversi(formUtama, false);
            konversi.isCek();
            konversi.emptTeks();
            konversi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(konversi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnKonversi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnDashboardeResepRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardeResepRalanActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDashboardEresep eResep = new DlgDashboardEresep(formUtama, false);
            eResep.emptTeks();
            eResep.tampil();
            eResep.tampilResepAntibiotik();
            eResep.isCek();
            formUtama.tampilkanDialogDiPanelUtama(eResep);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDashboardeResepRalan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDashboardeResepRalanActionPerformed

    private void btnDashboardeResepRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardeResepRanapActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDashboardEresepRanap eResep = new DlgDashboardEresepRanap(formUtama, false);
            eResep.emptTeks();
            eResep.tampilAwal();
            eResep.tampilAwalAntibiotik();
            eResep.isCek();
            formUtama.tampilkanDialogDiPanelUtama(eResep);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDashboardeResepRanap.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDashboardeResepRanapActionPerformed

    private void btnJnsBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJnsBarangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgCariJenis jenis = new DlgCariJenis(formUtama, false);
            jenis.isCek();
            jenis.emptTeks();
            jenis.awalData();
            formUtama.tampilkanDialogDiPanelUtama(jenis);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnJnsBarang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnJnsBarangActionPerformed

    private void btnKategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriBarangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgKategori form = new DlgKategori(formUtama, false);
            form.isCek();
            form.emptTeks();
            form.awalData();
            formUtama.tampilkanDialogDiPanelUtama(form);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnKategoriBarang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnKategoriBarangActionPerformed

    private void btnGolonganBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolonganBarangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgGolongan form = new DlgGolongan(formUtama, false);
            form.isCek();
            form.emptTeks();
            form.awalData();
            formUtama.tampilkanDialogDiPanelUtama(form);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnGolonganBarang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnGolonganBarangActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgBarang barang = new DlgBarang(formUtama, false);
            barang.isCek();
            formUtama.tampilkanDialogDiPanelUtama(barang);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnObat.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnResepIterBpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResepIterBpjsActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgResepIterObat aplikasi = new DlgResepIterObat(formUtama, false);
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnResepIterBpjs.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnResepIterBpjsActionPerformed

    private void btnMasterAturanPakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterAturanPakaiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgAturanPakai aplikasi = new DlgAturanPakai(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnMasterAturanPakai.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnMasterAturanPakaiActionPerformed

    private void btnOpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpnameActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgInputStok opname = new DlgInputStok(formUtama, false);
            opname.tampil();
            opname.isCek();
            opname.awalData();
            formUtama.tampilkanDialogDiPanelUtama(opname);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnOpname.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnOpnameActionPerformed

    private void btnMutasiBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutasiBarangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgMutasiBarang aplikasi = new DlgMutasiBarang(formUtama, false);
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnMutasiBarang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnMutasiBarangActionPerformed

    private void btnLaporanFarmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanFarmasiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgLaporanFarmasi aplikasi = new DlgLaporanFarmasi(formUtama, false);
            aplikasi.setVisible(true);
            aplikasi.ChkInput.setSelected(true);
            aplikasi.isForm();
            aplikasi.emptTeks();
            aplikasi.tampil();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnLaporanFarmasi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnLaporanFarmasiActionPerformed

    private void btnStokObatPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokObatPasienActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgStokPasien opname = new DlgStokPasien(formUtama, false);
            opname.isCek();
            opname.awalData();
            formUtama.tampilkanDialogDiPanelUtama(opname);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnStokObatPasien.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnStokObatPasienActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPembelian pembelian = new DlgPembelian(formUtama, false);
            pembelian.isCek();
            pembelian.awalData();
            formUtama.tampilkanDialogDiPanelUtama(pembelian);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPembelian.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPemesanan pembelian = new DlgPemesanan(formUtama, false);
            pembelian.isCek();
            pembelian.awalData();
            formUtama.tampilkanDialogDiPanelUtama(pembelian);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPemesanan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPenjualan penjualan = new DlgPenjualan(formUtama, false);
            penjualan.isCek();
            penjualan.awalData();
            formUtama.tampilkanDialogDiPanelUtama(penjualan);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPenjualan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnDaftarPermintaanResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPermintaanResepActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDaftarPermintaanResep daftar = new DlgDaftarPermintaanResep(formUtama, false);
            daftar.emptTeks();
            daftar.isCek("-");
            daftar.awalData();
            formUtama.tampilkanDialogDiPanelUtama(daftar);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDaftarPermintaanResep.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDaftarPermintaanResepActionPerformed

    private void btnPiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiutangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPiutang piutang = new DlgPiutang(formUtama, false);
            piutang.emptTeks();
            piutang.isCek();
            piutang.awalData();
            formUtama.tampilkanDialogDiPanelUtama(piutang);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPiutang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPiutangActionPerformed

    private void btnReturBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturBeliActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgReturBeli returbeli = new DlgReturBeli(formUtama, false);
            returbeli.isCek();
            returbeli.emptTeks();
            returbeli.awalData();
            formUtama.tampilkanDialogDiPanelUtama(returbeli);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnReturBeli.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnReturBeliActionPerformed

    private void btnReturJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturJualActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgReturJual");
            DlgReturJual returjual = new DlgReturJual(formUtama, false);
            returjual.emptTeks();
            returjual.isCek();
            returjual.awalData();
            formUtama.tampilkanDialogDiPanelUtama(returjual);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnReturJual.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnReturJualActionPerformed

    private void btnReturPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturPasienActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgReturObatPasien returpasien = new DlgReturObatPasien(formUtama, false);
            returpasien.isCek();
            returpasien.awalData();
            formUtama.tampilkanDialogDiPanelUtama(returpasien);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnReturPasien.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnReturPasienActionPerformed

    private void btnReturPiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturPiutangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgReturPiutang returpiutang = new DlgReturPiutang(formUtama, false);
            returpiutang.isCek();
            returpiutang.emptTeks();
            returpiutang.awalData();
            formUtama.tampilkanDialogDiPanelUtama(returpiutang);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnReturPiutang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnReturPiutangActionPerformed

    private void btnPengambilanUTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengambilanUTDActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPengambilanUTD form = new DlgPengambilanUTD(formUtama, false);
            form.isCek();
            form.awalData();
            formUtama.tampilkanDialogDiPanelUtama(form);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPengambilanUTD.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPengambilanUTDActionPerformed

    private void btnKeuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuntunganActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgProyeksiJual projul = new DlgProyeksiJual(formUtama, false);
            projul.isCek();
            projul.awalData();
            formUtama.tampilkanDialogDiPanelUtama(projul);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnKeuntungan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnKeuntunganActionPerformed

    private void btnKeuntunganObatRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuntunganObatRanapActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgProyeksiBeriObat projul = new DlgProyeksiBeriObat(formUtama, false);
            projul.isCek();
            projul.awalData();
            formUtama.tampilkanDialogDiPanelUtama(projul);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnKeuntunganObatRanap.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnKeuntunganObatRanapActionPerformed

    private void btnKeuntunganObat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuntunganObat2ActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgProyeksiBeriObat2 projul = new DlgProyeksiBeriObat2(formUtama, false);
            projul.isCek();
            projul.awalData();
            formUtama.tampilkanDialogDiPanelUtama(projul);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnKeuntunganObat2.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnKeuntunganObat2ActionPerformed

    private void btnSirkulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSirkulasiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSirkulasiBarang sirkulasi = new DlgSirkulasiBarang(formUtama, false);
            sirkulasi.isCek();
            formUtama.tampilkanDialogDiPanelUtama(sirkulasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSirkulasi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSirkulasiActionPerformed

    private void btnSirkulasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSirkulasi2ActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgSirkulasiBarang2 sirkulasi = new DlgSirkulasiBarang2(formUtama, false);
            sirkulasi.isCek();
            formUtama.tampilkanDialogDiPanelUtama(sirkulasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnSirkulasi2.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnSirkulasi2ActionPerformed

    private void btnObatPerTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatPerTanggalActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgObatPerTanggal form = new DlgObatPerTanggal(formUtama, false);
            formUtama.tampilkanDialogDiPanelUtama(form);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnObatPerTanggal.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnObatPerTanggalActionPerformed

    private void btnPenjualanPerTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanPerTanggalActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPenjualanPerTanggal form = new DlgPenjualanPerTanggal(formUtama, false);
            formUtama.tampilkanDialogDiPanelUtama(form);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPenjualanPerTanggal.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPenjualanPerTanggalActionPerformed

    private void btnRiwayatBarangMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatBarangMedisActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgRiwayatBarangMedis sirkulasi = new DlgRiwayatBarangMedis(formUtama, false);
            sirkulasi.isCek();
            formUtama.tampilkanDialogDiPanelUtama(sirkulasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnRiwayatBarangMedis.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnRiwayatBarangMedisActionPerformed

    private void btnDaruratStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaruratStokActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDaruratStok aplikasi = new DlgDaruratStok(formUtama, false);
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDaruratStok.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDaruratStokActionPerformed

    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox ChkInput;
    private widget.PanelBiasa FormMenu;
    public widget.TextBox TCari;
    private widget.Button btnClear;
    private widget.ButtonBig btnDaftarPermintaanResep;
    private widget.ButtonBig btnDaruratStok;
    private widget.ButtonBig btnDashboardeResepRalan;
    private widget.ButtonBig btnDashboardeResepRanap;
    private widget.ButtonBig btnGolonganBarang;
    private widget.ButtonBig btnIndustriFarmasi;
    private widget.ButtonBig btnJnsBarang;
    private widget.ButtonBig btnKategoriBarang;
    private widget.ButtonBig btnKeuntungan;
    private widget.ButtonBig btnKeuntunganObat2;
    private widget.ButtonBig btnKeuntunganObatRanap;
    private widget.ButtonBig btnKonversi;
    private widget.ButtonBig btnLaporanFarmasi;
    private widget.ButtonBig btnMasterAturanPakai;
    private widget.ButtonBig btnMutasiBarang;
    private widget.ButtonBig btnObat;
    private widget.ButtonBig btnObatPerTanggal;
    private widget.ButtonBig btnOpname;
    private widget.ButtonBig btnPembelian;
    private widget.ButtonBig btnPemberianObat;
    private widget.ButtonBig btnPemesanan;
    private widget.ButtonBig btnPengambilanUTD;
    private widget.ButtonBig btnPenjualan;
    private widget.ButtonBig btnPenjualanPerTanggal;
    private widget.ButtonBig btnPetugasPelaksanaPemberianObat;
    private widget.ButtonBig btnPiutang;
    private widget.ButtonBig btnRekonsiliasiObat;
    private widget.ButtonBig btnResepIterBpjs;
    private widget.ButtonBig btnReturBeli;
    private widget.ButtonBig btnReturJual;
    private widget.ButtonBig btnReturPasien;
    private widget.ButtonBig btnReturPiutang;
    private widget.ButtonBig btnRiwayatBarangMedis;
    private widget.ButtonBig btnSatuan;
    private widget.ButtonBig btnSirkulasi;
    private widget.ButtonBig btnSirkulasi2;
    private widget.ButtonBig btnStokObatPasien;
    private widget.ButtonBig btnSuplier;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel3;
    private widget.ScrollPane scrollMenu;
    // End of variables declaration//GEN-END:variables

    private void isTampil() {
        jmlmenu = 0;
        String cari = TCari.getText().toLowerCase().trim();

        if (akses.getberi_obat() && btnRekonsiliasiObat.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnRekonsiliasiObat);
            jmlmenu++;
        }
        
        if (akses.getpemberian_obat() && btnPemberianObat.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPemberianObat);
            jmlmenu++;
        }
        
        if (akses.getpemberian_obat() && btnPetugasPelaksanaPemberianObat.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPetugasPelaksanaPemberianObat);
            jmlmenu++;
        }
        
        if (akses.getindustrifarmasi() && btnIndustriFarmasi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnIndustriFarmasi);
            jmlmenu++;
        }
        
        if (akses.getsuplier() && btnSuplier.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSuplier);
            jmlmenu++;
        }
        
        if (akses.getsatuan_barang() && btnSatuan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSatuan);
            jmlmenu++;
        }
        
        if (akses.getkonversi_satuan() && btnKonversi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnKonversi);
            jmlmenu++;
        }
        
        if (akses.getdashboard_eResep() && btnDashboardeResepRalan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDashboardeResepRalan);
            jmlmenu++;
        }
        
        if (akses.getdashboard_eResep() && btnDashboardeResepRanap.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDashboardeResepRanap);
            jmlmenu++;
        }
        
        if (akses.getkategori_barang() && btnKategoriBarang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnKategoriBarang);
            jmlmenu++;
        }
        
        if (akses.getgolongan_barang() && btnGolonganBarang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnGolonganBarang);
            jmlmenu++;
        }
        
        if (akses.getobat() && btnObat.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnObat);
            jmlmenu++;
        }
        
        if (akses.getobat() && btnResepIterBpjs.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnResepIterBpjs);
            jmlmenu++;
        }
        
        if (akses.getresep_obat() && btnMasterAturanPakai.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnMasterAturanPakai);
            jmlmenu++;
        }
        
        if (akses.getstok_opname_obat() && btnOpname.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnOpname);
            jmlmenu++;
        }
        
        if (akses.getmutasi_barang() && btnMutasiBarang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnMutasiBarang);
            jmlmenu++;
        }
        
        if (akses.getlaporanfarmasi() && btnLaporanFarmasi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnLaporanFarmasi);
            jmlmenu++;
        }
        
        if (akses.getstok_obat_pasien() && btnStokObatPasien.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnStokObatPasien);
            jmlmenu++;
        }
        
        if (akses.getpengadaan_obat() && btnPembelian.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPembelian);
            jmlmenu++;
        }
        
        if (akses.getpemesanan_obat() && btnPemesanan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPemesanan);
            jmlmenu++;
        }
        
        if (akses.getpenjualan_obat() && btnPenjualan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPenjualan);
            jmlmenu++;
        }
        
        if (akses.getresep_dokter() && btnDaftarPermintaanResep.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDaftarPermintaanResep);
            jmlmenu++;
        }
        
        if (akses.getpiutang_obat() && btnPiutang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPiutang);
            jmlmenu++;
        }
        
        if (akses.getretur_ke_suplier() && btnReturBeli.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnReturBeli);
            jmlmenu++;
        }
        
        if (akses.getretur_dari_pembeli() && btnReturJual.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnReturJual);
            jmlmenu++;
        }
        
        if (akses.getretur_obat_ranap() && btnReturPasien.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnReturPasien);
            jmlmenu++;
        }
        
        if (akses.getretur_piutang_pasien() && btnReturPiutang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnReturPiutang);
            jmlmenu++;
        }
        
        if (akses.getpengambilan_utd() && btnPengambilanUTD.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPengambilanUTD);
            jmlmenu++;
        }
        
        if (akses.getkeuntungan_penjualan() && btnKeuntungan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnKeuntungan);
            jmlmenu++;
        }
        
        if (akses.getkeuntungan_beri_obat() && btnKeuntunganObatRanap.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnKeuntunganObatRanap);
            jmlmenu++;
        }
        
        if (akses.getkeuntungan_beri_obat_nonpiutang() && btnKeuntunganObat2.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnKeuntunganObat2);
            jmlmenu++;
        }
        
        if (akses.getsirkulasi_obat() && btnSirkulasi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSirkulasi);
            jmlmenu++;
        }
        
        if (akses.getsirkulasi_obat2() && btnSirkulasi2.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnSirkulasi2);
            jmlmenu++;
        }
        
        if (akses.getpemberian_obat_pertanggal() && btnObatPerTanggal.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnObatPerTanggal);
            jmlmenu++;
        }
        
        if (akses.getpenjualan_obat_pertanggal() && btnPenjualanPerTanggal.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPenjualanPerTanggal);
            jmlmenu++;
        }
        
        if (akses.getriwayat_obat_alkes_bhp() && btnRiwayatBarangMedis.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnRiwayatBarangMedis);
            jmlmenu++;
        }
        
        if (akses.getdarurat_stok() && btnDaruratStok.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDaruratStok);
            jmlmenu++;
        }
    }
    
    public JPanel getFormMenu() {
        return FormMenu;
    }

    public javax.swing.JPanel getPanelUtama() {
        return internalFrame1;
    }

    public void tampilkanMenu() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            ChkInputActionPerformed(null);

            javax.swing.Timer timer
                    = new javax.swing.Timer(100, e -> {

                        ((javax.swing.Timer) e.getSource()).stop();

                        ChkInputActionPerformed(null);

                        scrollMenu.getVerticalScrollBar().setValue(0);
                    });

            timer.setRepeats(false);
            timer.start();
        });
    }

    public void terapkanHakAkses() {
        FormMenu.removeAll();
        jmlmenu = 0;      

        if (akses.getberi_obat() == true) {
            FormMenu.add(btnRekonsiliasiObat);
            jmlmenu++;
        }

        if (akses.getpemberian_obat() == true) {
            FormMenu.add(btnPemberianObat);
            jmlmenu++;
        }

        if (akses.getpemberian_obat() == true) {
            FormMenu.add(btnPetugasPelaksanaPemberianObat);
            jmlmenu++;
        }

        if (akses.getindustrifarmasi() == true) {
            FormMenu.add(btnIndustriFarmasi);
            jmlmenu++;
        }

        if (akses.getsuplier() == true) {
            FormMenu.add(btnSuplier);
            jmlmenu++;
        }

        if (akses.getsatuan_barang() == true) {
            FormMenu.add(btnSatuan);
            jmlmenu++;
        }

        if (akses.getkonversi_satuan() == true) {
            FormMenu.add(btnKonversi);
            jmlmenu++;
        }

        if (akses.getdashboard_eResep() == true) {
            FormMenu.add(btnDashboardeResepRalan);
            jmlmenu++;
        }

        if (akses.getdashboard_eResep() == true) {
            FormMenu.add(btnDashboardeResepRanap);
            jmlmenu++;
        }

        if (akses.getjenis_barang() == true) {
            FormMenu.add(btnJnsBarang);
            jmlmenu++;
        }

        if (akses.getkategori_barang() == true) {
            FormMenu.add(btnKategoriBarang);
            jmlmenu++;
        }

        if (akses.getgolongan_barang() == true) {
            FormMenu.add(btnGolonganBarang);
            jmlmenu++;
        }

        if (akses.getobat() == true) {
            FormMenu.add(btnObat);
            jmlmenu++;
        }

        if (akses.getobat() == true) {
            FormMenu.add(btnResepIterBpjs);
            jmlmenu++;
        }

        if (akses.getresep_obat() == true) {
            FormMenu.add(btnMasterAturanPakai);
            jmlmenu++;
        }

        if (akses.getstok_opname_obat() == true) {
            FormMenu.add(btnOpname);
            jmlmenu++;
        }

        if (akses.getmutasi_barang() == true) {
            FormMenu.add(btnMutasiBarang);
            jmlmenu++;
        }

        if (akses.getlaporanfarmasi() == true) {
            FormMenu.add(btnLaporanFarmasi);
            jmlmenu++;
        }

        if (akses.getstok_obat_pasien() == true) {
            FormMenu.add(btnStokObatPasien);
            jmlmenu++;
        }

        if (akses.getpengadaan_obat() == true) {
            FormMenu.add(btnPembelian);
            jmlmenu++;
        }

        if (akses.getpemesanan_obat() == true) {
            FormMenu.add(btnPemesanan);
            jmlmenu++;
        }

        if (akses.getpenjualan_obat() == true) {
            FormMenu.add(btnPenjualan);
            jmlmenu++;
        }

        if (akses.getresep_dokter() == true) {
            FormMenu.add(btnDaftarPermintaanResep);
            jmlmenu++;
        }

        if (akses.getpiutang_obat() == true) {
            FormMenu.add(btnPiutang);
            jmlmenu++;
        }

        if (akses.getretur_ke_suplier() == true) {
            FormMenu.add(btnReturBeli);
            jmlmenu++;
        }

        if (akses.getretur_dari_pembeli() == true) {
            FormMenu.add(btnReturJual);
            jmlmenu++;
        }

        if (akses.getretur_obat_ranap() == true) {
            FormMenu.add(btnReturPasien);
            jmlmenu++;
        }

        if (akses.getretur_piutang_pasien() == true) {
            FormMenu.add(btnReturPiutang);
            jmlmenu++;
        }

        if (akses.getpengambilan_utd() == true) {
            FormMenu.add(btnPengambilanUTD);
            jmlmenu++;
        }

        if (akses.getkeuntungan_penjualan() == true) {
            FormMenu.add(btnKeuntungan);
            jmlmenu++;
        }

        if (akses.getkeuntungan_beri_obat() == true) {
            FormMenu.add(btnKeuntunganObatRanap);
            jmlmenu++;
        }

        if (akses.getkeuntungan_beri_obat_nonpiutang() == true) {
            FormMenu.add(btnKeuntunganObat2);
            jmlmenu++;
        }

        if (akses.getsirkulasi_obat() == true) {
            FormMenu.add(btnSirkulasi);
            jmlmenu++;
        }

        if (akses.getsirkulasi_obat2() == true) {
            FormMenu.add(btnSirkulasi2);
            jmlmenu++;
        }

        if (akses.getpemberian_obat_pertanggal() == true) {
            FormMenu.add(btnObatPerTanggal);
            jmlmenu++;
        }

        if (akses.getpenjualan_obat_pertanggal() == true) {
            FormMenu.add(btnPenjualanPerTanggal);
            jmlmenu++;
        }

        if (akses.getriwayat_obat_alkes_bhp() == true) {
            FormMenu.add(btnRiwayatBarangMedis);
            jmlmenu++;
        }

        if (akses.getdarurat_stok() == true) {
            FormMenu.add(btnDaruratStok);
            jmlmenu++;
        }

        aturLayoutMenu();

        FormMenu.revalidate();
        FormMenu.repaint();
    }
    
    private void aturLayoutMenu() {
        int lebarViewport = scrollMenu.getViewport().getExtentSize().width;
        int tinggiViewport = scrollMenu.getViewport().getExtentSize().height;

        if (lebarViewport <= 0) {
            lebarViewport = scrollMenu.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport = scrollMenu.getHeight();
        }

        if (lebarViewport <= 0) {
            lebarViewport = internalFrame1.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport
                    = internalFrame1.getHeight() - internalFrame2.getHeight();
        }

        /*
     * Sama seperti menu frmUtama:
     * jumlah menu menentukan jumlah kolom.
         */
        if (jmlmenu <= 1) {
            grid = 1;
        } else if (jmlmenu <= 4) {
            grid = 2;
        } else if (jmlmenu <= 9) {
            grid = 3;
        } else if (jmlmenu <= 16) {
            grid = 4;
        } else {
            grid = 5;
        }

        int tinggiTombol = 120;
        int jarakHorizontal = 5;
        int jarakVertikal = 35;

        int jumlahBaris = (int) Math.ceil(
                (double) jmlmenu / grid
        );

        int tinggiIsi
                = (jumlahBaris * tinggiTombol)
                + (Math.max(0, jumlahBaris - 1) * jarakVertikal)
                + 20;

        /*
     * Jika isi lebih tinggi dari viewport,
     * scrollbar otomatis muncul.
         */
        tinggi = Math.max(tinggiViewport, tinggiIsi);

        FormMenu.setLayout(new GridLayout(
                0,
                grid,
                jarakHorizontal,
                jarakVertikal
        ));

        Dimension ukuranMenu = new Dimension(
                Math.max(lebarViewport - 10, 200),
                tinggi
        );

        FormMenu.setPreferredSize(ukuranMenu);
        FormMenu.setMinimumSize(ukuranMenu);

        scrollMenu.setVerticalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        );

        scrollMenu.setHorizontalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
        );

        scrollMenu.getVerticalScrollBar().setUnitIncrement(16);
        scrollMenu.getVerticalScrollBar().setBlockIncrement(120);

        FormMenu.revalidate();
        FormMenu.repaint();

        scrollMenu.getViewport().revalidate();
        scrollMenu.getViewport().repaint();

        scrollMenu.revalidate();
        scrollMenu.repaint();
    }

    private void aturTampilanTombol() {
        java.awt.Component[] komponen = FormMenu.getComponents();

        for (java.awt.Component komponenMenu : komponen) {
            if (komponenMenu instanceof widget.ButtonBig) {
                widget.ButtonBig tombol
                        = (widget.ButtonBig) komponenMenu;

                tombol.setHorizontalAlignment(
                        javax.swing.SwingConstants.CENTER
                );

                tombol.setVerticalAlignment(
                        javax.swing.SwingConstants.CENTER
                );
            }
        }
    }
}
