package setting;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import kepegawaian.DlgDepartemen;
import kepegawaian.DlgPegawai;
import kepegawaian.DlgPetugas;
import rekammedis.DlgMasterJabatanKomite;
import simrskhanza.DlgDokter;
import simrskhanza.DlgJabatan;
import simrskhanza.DlgMasterNomorDokumen;
import simrskhanza.frmUtama;

/**
 *
 * @author dosen
 */
public class PanelMenuUtamaC extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private String versi = "";
    private int jmlmenu = 0, grid = 0, tinggi = 0, i = 0;
    private frmUtama formUtama;
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public PanelMenuUtamaC(frmUtama parent, boolean modal) {
        super(parent, modal);
        formUtama = parent;
        initComponents();
        aturTampilanTombol();

        versi = Sequel.cariIsi("select versi_update from history_update ORDER BY tgl_update desc, jam_update desc limit 1");        
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        internalFrame2 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TCari = new widget.TextBox();
        btnClear = new widget.Button();
        ChkInput = new widget.CekBox();
        scrollMenu = new widget.ScrollPane();
        FormMenu = new widget.PanelBiasa();
        btnMasterNomorDokumen = new widget.ButtonBig();
        btnPegawai = new widget.ButtonBig();
        btnDokter = new widget.ButtonBig();
        btnDataJabatan = new widget.ButtonBig();
        btnMasterJabatanKomite = new widget.ButtonBig();
        btnDepartemen = new widget.ButtonBig();
        btnPenggajian = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(12, 39));
        internalFrame2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cari Menu C :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(jLabel3);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        internalFrame2.add(TCari);

        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        btnClear.setGlassColor(new java.awt.Color(255, 255, 255));
        btnClear.setMinimumSize(new java.awt.Dimension(28, 23));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(30, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        internalFrame2.add(btnClear);

        ChkInput.setBorder(null);
        ChkInput.setForeground(new java.awt.Color(0, 0, 0));
        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setSelected(true);
        ChkInput.setText("Pencarian");
        ChkInput.setToolTipText("Alt+C");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setOpaque(false);
        ChkInput.setPreferredSize(new java.awt.Dimension(100, 23));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        internalFrame2.add(ChkInput);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        scrollMenu.setName("scrollMenu"); // NOI18N
        scrollMenu.setPreferredSize(new java.awt.Dimension(102, 557));

        FormMenu.setBackground(new java.awt.Color(255, 255, 255));
        FormMenu.setBorder(null);
        FormMenu.setName("FormMenu"); // NOI18N
        FormMenu.setPreferredSize(new java.awt.Dimension(2400, 3240));
        FormMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        btnMasterNomorDokumen.setForeground(new java.awt.Color(0, 0, 0));
        btnMasterNomorDokumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_book_285636.png"))); // NOI18N
        btnMasterNomorDokumen.setText("Master Nomor Dokumen");
        btnMasterNomorDokumen.setIconTextGap(0);
        btnMasterNomorDokumen.setName("btnMasterNomorDokumen"); // NOI18N
        btnMasterNomorDokumen.setPreferredSize(new java.awt.Dimension(200, 90));
        btnMasterNomorDokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterNomorDokumenActionPerformed(evt);
            }
        });
        FormMenu.add(btnMasterNomorDokumen);

        btnPegawai.setForeground(new java.awt.Color(0, 0, 0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/receptionist.png"))); // NOI18N
        btnPegawai.setText("Petugas");
        btnPegawai.setIconTextGap(0);
        btnPegawai.setName("btnPegawai"); // NOI18N
        btnPegawai.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        FormMenu.add(btnPegawai);

        btnDokter.setForeground(new java.awt.Color(0, 0, 0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/doctor2.png"))); // NOI18N
        btnDokter.setText("Dokter");
        btnDokter.setIconTextGap(0);
        btnDokter.setName("btnDokter"); // NOI18N
        btnDokter.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        FormMenu.add(btnDokter);

        btnDataJabatan.setForeground(new java.awt.Color(0, 0, 0));
        btnDataJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/user3.png"))); // NOI18N
        btnDataJabatan.setText("Data Jabatan");
        btnDataJabatan.setIconTextGap(0);
        btnDataJabatan.setName("btnDataJabatan"); // NOI18N
        btnDataJabatan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDataJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataJabatanActionPerformed(evt);
            }
        });
        FormMenu.add(btnDataJabatan);

        btnMasterJabatanKomite.setForeground(new java.awt.Color(0, 0, 0));
        btnMasterJabatanKomite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/users.png"))); // NOI18N
        btnMasterJabatanKomite.setText("Master Jabatan Komite");
        btnMasterJabatanKomite.setIconTextGap(0);
        btnMasterJabatanKomite.setName("btnMasterJabatanKomite"); // NOI18N
        btnMasterJabatanKomite.setPreferredSize(new java.awt.Dimension(200, 90));
        btnMasterJabatanKomite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterJabatanKomiteActionPerformed(evt);
            }
        });
        FormMenu.add(btnMasterJabatanKomite);

        btnDepartemen.setForeground(new java.awt.Color(0, 0, 0));
        btnDepartemen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_kde-folder-public_25193.png"))); // NOI18N
        btnDepartemen.setText("Departemen & Mapping Bangsal");
        btnDepartemen.setIconTextGap(0);
        btnDepartemen.setName("btnDepartemen"); // NOI18N
        btnDepartemen.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartemenActionPerformed(evt);
            }
        });
        FormMenu.add(btnDepartemen);

        btnPenggajian.setForeground(new java.awt.Color(0, 0, 0));
        btnPenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404046603_wallet.png"))); // NOI18N
        btnPenggajian.setText("Kepegawaian");
        btnPenggajian.setIconTextGap(0);
        btnPenggajian.setName("btnPenggajian"); // NOI18N
        btnPenggajian.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggajianActionPerformed(evt);
            }
        });
        FormMenu.add(btnPenggajian);

        scrollMenu.setViewportView(FormMenu);

        internalFrame1.add(scrollMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampilkanMenu();
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        akses.setCopyData5("");
        TCari.setText("");
        TCari.requestFocus();        
    }//GEN-LAST:event_btnClearActionPerformed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        FormMenu.removeAll();

        isTampil();
        aturTampilanTombol();
        aturLayoutMenu();

        javax.swing.SwingUtilities.invokeLater(() -> {
            FormMenu.revalidate();
            FormMenu.repaint();
            scrollMenu.getViewport().revalidate();
            scrollMenu.revalidate();
            scrollMenu.repaint();
            scrollMenu.getVerticalScrollBar().setValue(0);
        });
    }//GEN-LAST:event_ChkInputActionPerformed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ChkInputActionPerformed(null);
            akses.setCopyData5(TCari.getText());
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void btnMasterNomorDokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterNomorDokumenActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgMasterNomorDokumen aplikasi = new DlgMasterNomorDokumen(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.ChkInput.setSelected(true);
            aplikasi.isForm();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnMasterNomorDokumen.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnMasterNomorDokumenActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPetugas petugas = new DlgPetugas(formUtama, false);
            petugas.isCek();
            petugas.awalData();
            formUtama.tampilkanDialogDiPanelUtama(petugas);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPegawai.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDokter dokter = new DlgDokter(formUtama, false);
            dokter.emptTeks();
            dokter.isCek();
            dokter.awalData();
            formUtama.tampilkanDialogDiPanelUtama(dokter);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDokter.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnDataJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataJabatanActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgJabatan jabatan = new DlgJabatan(formUtama, false);
            jabatan.isCek();
            jabatan.emptTeks();
            jabatan.awalData();
            formUtama.tampilkanDialogDiPanelUtama(jabatan);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDataJabatan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDataJabatanActionPerformed

    private void btnMasterJabatanKomiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterJabatanKomiteActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgMasterJabatanKomite komite = new DlgMasterJabatanKomite(formUtama, false);
            komite.isCek();
            komite.emptTeks();
            komite.ChkInput.setSelected(true);
            komite.isForm();
            formUtama.tampilkanDialogDiPanelUtama(komite);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnMasterJabatanKomite.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnMasterJabatanKomiteActionPerformed

    private void btnDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartemenActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDepartemen aplikasi = new DlgDepartemen(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnDepartemen.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnDepartemenActionPerformed

    private void btnPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggajianActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPegawai pegawai = new DlgPegawai(formUtama, false);
            pegawai.ChkInput.setSelected(true);
            pegawai.isForm();
            pegawai.isCek();
            pegawai.emptTeks();
            pegawai.TCari.setText("");
            pegawai.TCari.requestFocus();
            pegawai.awalData();
            formUtama.tampilkanDialogDiPanelUtama(pegawai);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPenggajian.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPenggajianActionPerformed

    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox ChkInput;
    private widget.PanelBiasa FormMenu;
    public widget.TextBox TCari;
    private widget.Button btnClear;
    private widget.ButtonBig btnDataJabatan;
    private widget.ButtonBig btnDepartemen;
    private widget.ButtonBig btnDokter;
    private widget.ButtonBig btnMasterJabatanKomite;
    private widget.ButtonBig btnMasterNomorDokumen;
    private widget.ButtonBig btnPegawai;
    private widget.ButtonBig btnPenggajian;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel3;
    private widget.ScrollPane scrollMenu;
    // End of variables declaration//GEN-END:variables

    private void isTampil() {
        jmlmenu = 0;
        String cari = TCari.getText().toLowerCase().trim();

        if (akses.getadmin() && btnMasterNomorDokumen.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnMasterNomorDokumen);
            jmlmenu++;
        }
        
        if (akses.getpetugas() && btnPegawai.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPegawai);
            jmlmenu++;
        }
        
        if (akses.getdokter() && btnDokter.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDokter);
            jmlmenu++;
        }
        
        if (akses.getpegawai_admin() && btnDataJabatan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDataJabatan);
            jmlmenu++;
        }
        
        if (akses.getpegawai_admin() && btnMasterJabatanKomite.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnMasterJabatanKomite);
            jmlmenu++;
        }
        
        if (akses.getadmin() && btnDepartemen.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnDepartemen);
            jmlmenu++;
        }
        
        if ((akses.getpegawai_admin() || akses.getpegawai_user()) && btnPenggajian.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPenggajian);
            jmlmenu++;
        }
    }
    
    public JPanel getFormMenu() {
        return FormMenu;
    }

    public javax.swing.JPanel getPanelUtama() {
        return internalFrame1;
    }

    public void tampilkanMenu() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            ChkInputActionPerformed(null);

            javax.swing.Timer timer
                    = new javax.swing.Timer(100, e -> {

                        ((javax.swing.Timer) e.getSource()).stop();

                        ChkInputActionPerformed(null);

                        scrollMenu.getVerticalScrollBar().setValue(0);
                    });

            timer.setRepeats(false);
            timer.start();
        });
    }

    public void terapkanHakAkses() {
        FormMenu.removeAll();
        jmlmenu = 0;      

        if (akses.getadmin() == true) {
            FormMenu.add(btnMasterNomorDokumen);
            jmlmenu++;
        }

        if (akses.getpetugas() == true) {
            FormMenu.add(btnPegawai);
            jmlmenu++;
        }

        if (akses.getdokter() == true) {
            FormMenu.add(btnDokter);
            jmlmenu++;
        }

        if (akses.getpegawai_admin() == true) {
            FormMenu.add(btnDataJabatan);
            jmlmenu++;
        }

        if (akses.getpegawai_admin() == true) {
            FormMenu.add(btnMasterJabatanKomite);
            jmlmenu++;
        }

        if (akses.getadmin() == true) {
            FormMenu.add(btnDepartemen);
            jmlmenu++;
        }

        if ((akses.getpegawai_admin() == true) || (akses.getpegawai_user() == true)) {
            FormMenu.add(btnPenggajian);
            jmlmenu++;
        }

        aturLayoutMenu();

        FormMenu.revalidate();
        FormMenu.repaint();
    }
    
    private void aturLayoutMenu() {
        int lebarViewport = scrollMenu.getViewport().getExtentSize().width;
        int tinggiViewport = scrollMenu.getViewport().getExtentSize().height;

        if (lebarViewport <= 0) {
            lebarViewport = scrollMenu.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport = scrollMenu.getHeight();
        }

        if (lebarViewport <= 0) {
            lebarViewport = internalFrame1.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport
                    = internalFrame1.getHeight() - internalFrame2.getHeight();
        }

        /*
     * Sama seperti menu frmUtama:
     * jumlah menu menentukan jumlah kolom.
         */
        if (jmlmenu <= 1) {
            grid = 1;
        } else if (jmlmenu <= 4) {
            grid = 2;
        } else if (jmlmenu <= 9) {
            grid = 3;
        } else if (jmlmenu <= 16) {
            grid = 4;
        } else {
            grid = 5;
        }

        int tinggiTombol = 120;
        int jarakHorizontal = 5;
        int jarakVertikal = 35;

        int jumlahBaris = (int) Math.ceil(
                (double) jmlmenu / grid
        );

        int tinggiIsi
                = (jumlahBaris * tinggiTombol)
                + (Math.max(0, jumlahBaris - 1) * jarakVertikal)
                + 20;

        /*
     * Jika isi lebih tinggi dari viewport,
     * scrollbar otomatis muncul.
         */
        tinggi = Math.max(tinggiViewport, tinggiIsi);

        FormMenu.setLayout(new GridLayout(
                0,
                grid,
                jarakHorizontal,
                jarakVertikal
        ));

        Dimension ukuranMenu = new Dimension(
                Math.max(lebarViewport - 10, 200),
                tinggi
        );

        FormMenu.setPreferredSize(ukuranMenu);
        FormMenu.setMinimumSize(ukuranMenu);

        scrollMenu.setVerticalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        );

        scrollMenu.setHorizontalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
        );

        scrollMenu.getVerticalScrollBar().setUnitIncrement(16);
        scrollMenu.getVerticalScrollBar().setBlockIncrement(120);

        FormMenu.revalidate();
        FormMenu.repaint();

        scrollMenu.getViewport().revalidate();
        scrollMenu.getViewport().repaint();

        scrollMenu.revalidate();
        scrollMenu.repaint();
    }

    private void aturTampilanTombol() {
        java.awt.Component[] komponen = FormMenu.getComponents();

        for (java.awt.Component komponenMenu : komponen) {
            if (komponenMenu instanceof widget.ButtonBig) {
                widget.ButtonBig tombol
                        = (widget.ButtonBig) komponenMenu;

                tombol.setHorizontalAlignment(
                        javax.swing.SwingConstants.CENTER
                );

                tombol.setVerticalAlignment(
                        javax.swing.SwingConstants.CENTER
                );
            }
        }
    }
}
