package setting;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import keuangan.DlgDetailPotongan;
import keuangan.DlgDetailTambahan;
import keuangan.DlgFeeVisitDokter;
import keuangan.DlgJaminanTransaksi;
import keuangan.DlgLhtBiaya;
import keuangan.DlgLhtPiutang;
import keuangan.DlgPaymentPoint;
import keuangan.DlgPembayaranRalan;
import keuangan.DlgPembayaranRanap;
import keuangan.DlgPengembalianJaminan;
import keuangan.DlgPiutangRalan;
import keuangan.DlgPiutangRanap;
import keuangan.DlgRBObatPercaraBayar;
import keuangan.DlgRekapPerShift;
import keuangan.DlgTransaksiPanjar;
import simrskhanza.frmUtama;

/**
 *
 * @author dosen
 */
public class PanelMenuUtamaH extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private String versi = "";
    private int jmlmenu = 0, grid = 0, tinggi = 0, i = 0;
    private frmUtama formUtama;
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public PanelMenuUtamaH(frmUtama parent, boolean modal) {
        super(parent, modal);
        formUtama = parent;
        initComponents();
        aturTampilanTombol();

        versi = Sequel.cariIsi("select versi_update from history_update ORDER BY tgl_update desc, jam_update desc limit 1");        
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        internalFrame2 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TCari = new widget.TextBox();
        btnClear = new widget.Button();
        ChkInput = new widget.CekBox();
        scrollMenu = new widget.ScrollPane();
        FormMenu = new widget.PanelBiasa();
        btnTransaksiPanjar = new widget.ButtonBig();
        BtnJaminanTransaksi = new widget.ButtonBig();
        BtnPengembalianJaminanTransaksi = new widget.ButtonBig();
        btnObatPerCaraBayar = new widget.ButtonBig();
        btnfee_visit_dokter = new widget.ButtonBig();
        btnRalanMasuk = new widget.ButtonBig();
        btnRanapMasuk = new widget.ButtonBig();
        btnLihatPiutang = new widget.ButtonBig();
        btnPiutangRalan = new widget.ButtonBig();
        btnPiutangRanap = new widget.ButtonBig();
        btnTagihanMasuk = new widget.ButtonBig();
        btnTambahanBiaya = new widget.ButtonBig();
        btnPotonganBiaya = new widget.ButtonBig();
        btnRekapPershift = new widget.ButtonBig();
        btnPaymentPoint = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(12, 39));
        internalFrame2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cari Menu H :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(jLabel3);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        internalFrame2.add(TCari);

        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        btnClear.setGlassColor(new java.awt.Color(255, 255, 255));
        btnClear.setMinimumSize(new java.awt.Dimension(28, 23));
        btnClear.setName("btnClear"); // NOI18N
        btnClear.setPreferredSize(new java.awt.Dimension(30, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        internalFrame2.add(btnClear);

        ChkInput.setBorder(null);
        ChkInput.setForeground(new java.awt.Color(0, 0, 0));
        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setMnemonic('C');
        ChkInput.setSelected(true);
        ChkInput.setText("Pencarian");
        ChkInput.setToolTipText("Alt+C");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setOpaque(false);
        ChkInput.setPreferredSize(new java.awt.Dimension(100, 23));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        internalFrame2.add(ChkInput);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        scrollMenu.setName("scrollMenu"); // NOI18N
        scrollMenu.setPreferredSize(new java.awt.Dimension(102, 557));

        FormMenu.setBackground(new java.awt.Color(255, 255, 255));
        FormMenu.setBorder(null);
        FormMenu.setName("FormMenu"); // NOI18N
        FormMenu.setPreferredSize(new java.awt.Dimension(2400, 3240));
        FormMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        btnTransaksiPanjar.setForeground(new java.awt.Color(0, 0, 0));
        btnTransaksiPanjar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404046811_money.png"))); // NOI18N
        btnTransaksiPanjar.setText("Transaksi Panjar Pasien");
        btnTransaksiPanjar.setIconTextGap(0);
        btnTransaksiPanjar.setName("btnTransaksiPanjar"); // NOI18N
        btnTransaksiPanjar.setPreferredSize(new java.awt.Dimension(200, 90));
        btnTransaksiPanjar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiPanjarActionPerformed(evt);
            }
        });
        FormMenu.add(btnTransaksiPanjar);

        BtnJaminanTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        BtnJaminanTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/money_bag.png"))); // NOI18N
        BtnJaminanTransaksi.setText("Jaminan Transaksi");
        BtnJaminanTransaksi.setIconTextGap(0);
        BtnJaminanTransaksi.setName("BtnJaminanTransaksi"); // NOI18N
        BtnJaminanTransaksi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnJaminanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJaminanTransaksiActionPerformed(evt);
            }
        });
        FormMenu.add(BtnJaminanTransaksi);

        BtnPengembalianJaminanTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        BtnPengembalianJaminanTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        BtnPengembalianJaminanTransaksi.setText("Pengembalian Jaminan Transaksi");
        BtnPengembalianJaminanTransaksi.setIconTextGap(0);
        BtnPengembalianJaminanTransaksi.setName("BtnPengembalianJaminanTransaksi"); // NOI18N
        BtnPengembalianJaminanTransaksi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPengembalianJaminanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengembalianJaminanTransaksiActionPerformed(evt);
            }
        });
        FormMenu.add(BtnPengembalianJaminanTransaksi);

        btnObatPerCaraBayar.setForeground(new java.awt.Color(0, 0, 0));
        btnObatPerCaraBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360815855_laboratory.png"))); // NOI18N
        btnObatPerCaraBayar.setText("Obat Per Cara Bayar");
        btnObatPerCaraBayar.setIconTextGap(0);
        btnObatPerCaraBayar.setName("btnObatPerCaraBayar"); // NOI18N
        btnObatPerCaraBayar.setPreferredSize(new java.awt.Dimension(200, 90));
        btnObatPerCaraBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatPerCaraBayarActionPerformed(evt);
            }
        });
        FormMenu.add(btnObatPerCaraBayar);

        btnfee_visit_dokter.setForeground(new java.awt.Color(0, 0, 0));
        btnfee_visit_dokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485865_schedule.png"))); // NOI18N
        btnfee_visit_dokter.setText("Visite Dokter Rawat Inap");
        btnfee_visit_dokter.setIconTextGap(0);
        btnfee_visit_dokter.setName("btnfee_visit_dokter"); // NOI18N
        btnfee_visit_dokter.setPreferredSize(new java.awt.Dimension(200, 90));
        btnfee_visit_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfee_visit_dokterActionPerformed(evt);
            }
        });
        FormMenu.add(btnfee_visit_dokter);

        btnRalanMasuk.setForeground(new java.awt.Color(0, 0, 0));
        btnRalanMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047007_02.png"))); // NOI18N
        btnRalanMasuk.setText("Pembayaran Ralan");
        btnRalanMasuk.setIconTextGap(0);
        btnRalanMasuk.setName("btnRalanMasuk"); // NOI18N
        btnRalanMasuk.setPreferredSize(new java.awt.Dimension(200, 90));
        btnRalanMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRalanMasukActionPerformed(evt);
            }
        });
        FormMenu.add(btnRalanMasuk);

        btnRanapMasuk.setForeground(new java.awt.Color(0, 0, 0));
        btnRanapMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047007_02.png"))); // NOI18N
        btnRanapMasuk.setText("Pembayaran Ranap");
        btnRanapMasuk.setIconTextGap(0);
        btnRanapMasuk.setName("btnRanapMasuk"); // NOI18N
        btnRanapMasuk.setPreferredSize(new java.awt.Dimension(200, 90));
        btnRanapMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRanapMasukActionPerformed(evt);
            }
        });
        FormMenu.add(btnRanapMasuk);

        btnLihatPiutang.setForeground(new java.awt.Color(0, 0, 0));
        btnLihatPiutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist_pencil-o.png"))); // NOI18N
        btnLihatPiutang.setText("Piutang Pasien");
        btnLihatPiutang.setIconTextGap(0);
        btnLihatPiutang.setName("btnLihatPiutang"); // NOI18N
        btnLihatPiutang.setPreferredSize(new java.awt.Dimension(200, 90));
        btnLihatPiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPiutangActionPerformed(evt);
            }
        });
        FormMenu.add(btnLihatPiutang);

        btnPiutangRalan.setForeground(new java.awt.Color(0, 0, 0));
        btnPiutangRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047007_02.png"))); // NOI18N
        btnPiutangRalan.setText("Piutang Ralan");
        btnPiutangRalan.setIconTextGap(0);
        btnPiutangRalan.setName("btnPiutangRalan"); // NOI18N
        btnPiutangRalan.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPiutangRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiutangRalanActionPerformed(evt);
            }
        });
        FormMenu.add(btnPiutangRalan);

        btnPiutangRanap.setForeground(new java.awt.Color(0, 0, 0));
        btnPiutangRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047007_02.png"))); // NOI18N
        btnPiutangRanap.setText("Piutang Ranap");
        btnPiutangRanap.setIconTextGap(0);
        btnPiutangRanap.setName("btnPiutangRanap"); // NOI18N
        btnPiutangRanap.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPiutangRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiutangRanapActionPerformed(evt);
            }
        });
        FormMenu.add(btnPiutangRanap);

        btnTagihanMasuk.setForeground(new java.awt.Color(0, 0, 0));
        btnTagihanMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404046800_Cash_register.png"))); // NOI18N
        btnTagihanMasuk.setText("Tagihan Masuk");
        btnTagihanMasuk.setIconTextGap(0);
        btnTagihanMasuk.setName("btnTagihanMasuk"); // NOI18N
        btnTagihanMasuk.setPreferredSize(new java.awt.Dimension(200, 90));
        btnTagihanMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagihanMasukActionPerformed(evt);
            }
        });
        FormMenu.add(btnTagihanMasuk);

        btnTambahanBiaya.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahanBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404046786_Money.png"))); // NOI18N
        btnTambahanBiaya.setText("Tambahan Biaya Pasien");
        btnTambahanBiaya.setIconTextGap(0);
        btnTambahanBiaya.setName("btnTambahanBiaya"); // NOI18N
        btnTambahanBiaya.setPreferredSize(new java.awt.Dimension(200, 90));
        btnTambahanBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahanBiayaActionPerformed(evt);
            }
        });
        FormMenu.add(btnTambahanBiaya);

        btnPotonganBiaya.setForeground(new java.awt.Color(0, 0, 0));
        btnPotonganBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404046786_Money.png"))); // NOI18N
        btnPotonganBiaya.setText("Potongan Biaya Pasien");
        btnPotonganBiaya.setIconTextGap(0);
        btnPotonganBiaya.setName("btnPotonganBiaya"); // NOI18N
        btnPotonganBiaya.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPotonganBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotonganBiayaActionPerformed(evt);
            }
        });
        FormMenu.add(btnPotonganBiaya);

        btnRekapPershift.setForeground(new java.awt.Color(0, 0, 0));
        btnRekapPershift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist.png"))); // NOI18N
        btnRekapPershift.setText("Rekap Uang Pershift");
        btnRekapPershift.setIconTextGap(0);
        btnRekapPershift.setName("btnRekapPershift"); // NOI18N
        btnRekapPershift.setPreferredSize(new java.awt.Dimension(200, 90));
        btnRekapPershift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekapPershiftActionPerformed(evt);
            }
        });
        FormMenu.add(btnRekapPershift);

        btnPaymentPoint.setForeground(new java.awt.Color(0, 0, 0));
        btnPaymentPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/coins.png"))); // NOI18N
        btnPaymentPoint.setText("Payment Point");
        btnPaymentPoint.setIconTextGap(0);
        btnPaymentPoint.setName("btnPaymentPoint"); // NOI18N
        btnPaymentPoint.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPaymentPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentPointActionPerformed(evt);
            }
        });
        FormMenu.add(btnPaymentPoint);

        scrollMenu.setViewportView(FormMenu);

        internalFrame1.add(scrollMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampilkanMenu();
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        akses.setCopyData5("");
        TCari.setText("");
        TCari.requestFocus();        
    }//GEN-LAST:event_btnClearActionPerformed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        FormMenu.removeAll();

        isTampil();
        aturTampilanTombol();
        aturLayoutMenu();

        javax.swing.SwingUtilities.invokeLater(() -> {
            FormMenu.revalidate();
            FormMenu.repaint();
            scrollMenu.getViewport().revalidate();
            scrollMenu.revalidate();
            scrollMenu.repaint();
            scrollMenu.getVerticalScrollBar().setValue(0);
        });
    }//GEN-LAST:event_ChkInputActionPerformed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ChkInputActionPerformed(null);
            akses.setCopyData5(TCari.getText());
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void btnTransaksiPanjarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiPanjarActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgTransaksiPanjar aplikasi = new DlgTransaksiPanjar(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnTransaksiPanjar.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnTransaksiPanjarActionPerformed

    private void BtnJaminanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJaminanTransaksiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgJaminanTransaksi aplikasi = new DlgJaminanTransaksi(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + BtnJaminanTransaksi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnJaminanTransaksiActionPerformed

    private void BtnPengembalianJaminanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengembalianJaminanTransaksiActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPengembalianJaminan aplikasi = new DlgPengembalianJaminan(formUtama, false);
            aplikasi.emptTeks();
            aplikasi.isCek();
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + BtnPengembalianJaminanTransaksi.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPengembalianJaminanTransaksiActionPerformed

    private void btnObatPerCaraBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatPerCaraBayarActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgRBObatPercaraBayar rbpoli = new DlgRBObatPercaraBayar(formUtama, false);
            rbpoli.awalData();
            formUtama.tampilkanDialogDiPanelUtama(rbpoli);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnObatPerCaraBayar.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnObatPerCaraBayarActionPerformed

    private void btnfee_visit_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfee_visit_dokterActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgFeeVisitDokter feevisitdokter = new DlgFeeVisitDokter(formUtama, false);
            feevisitdokter.empttext();
            feevisitdokter.awalData();
            formUtama.tampilkanDialogDiPanelUtama(feevisitdokter);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnfee_visit_dokter.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnfee_visit_dokterActionPerformed

    private void btnRalanMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRalanMasukActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPembayaranRalan billing = new DlgPembayaranRalan(formUtama, false);
            billing.setVisible(true);
            billing.fokus();
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnRalanMasuk.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnRalanMasukActionPerformed

    private void btnRanapMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRanapMasukActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPembayaranRanap billing = new DlgPembayaranRanap(formUtama, false);
            billing.setVisible(true);
            billing.fokus();
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnRanapMasuk.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnRanapMasukActionPerformed

    private void btnLihatPiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPiutangActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgLhtPiutang billing = new DlgLhtPiutang(formUtama, false);
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnLihatPiutang.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnLihatPiutangActionPerformed

    private void btnPiutangRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiutangRalanActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPiutangRalan billing = new DlgPiutangRalan(formUtama, false);
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPiutangRalan.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPiutangRalanActionPerformed

    private void btnPiutangRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiutangRanapActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPiutangRanap billing = new DlgPiutangRanap(formUtama, false);
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPiutangRanap.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPiutangRanapActionPerformed

    private void btnTagihanMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagihanMasukActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgLhtBiaya billing = new DlgLhtBiaya(formUtama, false);
            billing.awalData();
            formUtama.tampilkanDialogDiPanelUtama(billing);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnTagihanMasuk.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnTagihanMasukActionPerformed

    private void btnTambahanBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahanBiayaActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDetailTambahan pembelian = new DlgDetailTambahan(formUtama, false);
            pembelian.awalData();
            formUtama.tampilkanDialogDiPanelUtama(pembelian);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnTambahanBiaya.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnTambahanBiayaActionPerformed

    private void btnPotonganBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotonganBiayaActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgDetailPotongan pembelian = new DlgDetailPotongan(formUtama, false);
            formUtama.tampilkanDialogDiPanelUtama(pembelian);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPotonganBiaya.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPotonganBiayaActionPerformed

    private void btnRekapPershiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekapPershiftActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgRekapPerShift aplikasi = new DlgRekapPerShift(formUtama, false);
            aplikasi.awalData();
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnRekapPershift.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnRekapPershiftActionPerformed

    private void btnPaymentPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentPointActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgPaymentPoint aplikasi = new DlgPaymentPoint(formUtama, false);
            formUtama.tampilkanDialogDiPanelUtama(aplikasi);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka form " + btnPaymentPoint.getText() + ".\n" + e.getMessage());
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnPaymentPointActionPerformed

    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnJaminanTransaksi;
    private widget.ButtonBig BtnPengembalianJaminanTransaksi;
    private widget.CekBox ChkInput;
    private widget.PanelBiasa FormMenu;
    public widget.TextBox TCari;
    private widget.Button btnClear;
    private widget.ButtonBig btnLihatPiutang;
    private widget.ButtonBig btnObatPerCaraBayar;
    private widget.ButtonBig btnPaymentPoint;
    private widget.ButtonBig btnPiutangRalan;
    private widget.ButtonBig btnPiutangRanap;
    private widget.ButtonBig btnPotonganBiaya;
    private widget.ButtonBig btnRalanMasuk;
    private widget.ButtonBig btnRanapMasuk;
    private widget.ButtonBig btnRekapPershift;
    private widget.ButtonBig btnTagihanMasuk;
    private widget.ButtonBig btnTambahanBiaya;
    private widget.ButtonBig btnTransaksiPanjar;
    private widget.ButtonBig btnfee_visit_dokter;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel3;
    private widget.ScrollPane scrollMenu;
    // End of variables declaration//GEN-END:variables

    private void isTampil() {
        jmlmenu = 0;
        String cari = TCari.getText().toLowerCase().trim();

        if (akses.getbilling_ranap() && btnTransaksiPanjar.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnTransaksiPanjar);
            jmlmenu++;
        }
        
        if (akses.getbilling_ranap() && BtnJaminanTransaksi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(BtnJaminanTransaksi);
            jmlmenu++;
        }
        
        if (akses.getbilling_ranap() && BtnPengembalianJaminanTransaksi.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(BtnPengembalianJaminanTransaksi);
            jmlmenu++;
        }
        
        if (akses.getobat_per_cara_bayar() && btnObatPerCaraBayar.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnObatPerCaraBayar);
            jmlmenu++;
        }
        
        if (akses.getfee_visit_dokter() && btnfee_visit_dokter.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnfee_visit_dokter);
            jmlmenu++;
        }
        
        if (akses.getpembayaran_ralan() && btnRalanMasuk.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnRalanMasuk);
            jmlmenu++;
        }
        
        if (akses.getpembayaran_ranap() && btnRanapMasuk.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnRanapMasuk);
            jmlmenu++;
        }
        
        if (akses.getpiutang_pasien() && btnLihatPiutang.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnLihatPiutang);
            jmlmenu++;
        }
        
        if (akses.getpiutang_ralan() && btnPiutangRalan.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPiutangRalan);
            jmlmenu++;
        }
        
        if (akses.getpiutang_ranap() && btnPiutangRanap.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPiutangRanap);
            jmlmenu++;
        }
        
        if (akses.gettagihan_masuk() && btnTagihanMasuk.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnTagihanMasuk);
            jmlmenu++;
        }
        
        if (akses.gettambahan_biaya() && btnTambahanBiaya.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnTambahanBiaya);
            jmlmenu++;
        }
        
        if (akses.getpotongan_biaya() && btnPotonganBiaya.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPotonganBiaya);
            jmlmenu++;
        }
        
        if (akses.getrekap_per_shift() && btnRekapPershift.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnRekapPershift);
            jmlmenu++;
        }
        
        if (akses.getpayment_point() && btnPaymentPoint.getText().toLowerCase().trim().contains(cari)) {
            FormMenu.add(btnPaymentPoint);
            jmlmenu++;
        }
    }
    
    public JPanel getFormMenu() {
        return FormMenu;
    }

    public javax.swing.JPanel getPanelUtama() {
        return internalFrame1;
    }

    public void tampilkanMenu() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            ChkInputActionPerformed(null);

            javax.swing.Timer timer
                    = new javax.swing.Timer(100, e -> {

                        ((javax.swing.Timer) e.getSource()).stop();

                        ChkInputActionPerformed(null);

                        scrollMenu.getVerticalScrollBar().setValue(0);
                    });

            timer.setRepeats(false);
            timer.start();
        });
    }

    public void terapkanHakAkses() {
        FormMenu.removeAll();
        jmlmenu = 0;

        if (akses.getbilling_ranap() == true) {
            FormMenu.add(btnTransaksiPanjar);
            jmlmenu++;
        }

        if (akses.getbilling_ranap() == true) {
            FormMenu.add(BtnJaminanTransaksi);
            jmlmenu++;
        }

        if (akses.getbilling_ranap() == true) {
            FormMenu.add(BtnPengembalianJaminanTransaksi);
            jmlmenu++;
        }

        if (akses.getobat_per_cara_bayar() == true) {
            FormMenu.add(btnObatPerCaraBayar);
            jmlmenu++;
        }

        if (akses.getfee_visit_dokter() == true) {
            FormMenu.add(btnfee_visit_dokter);
            jmlmenu++;
        }

        if (akses.getpembayaran_ralan() == true) {
            FormMenu.add(btnRalanMasuk);
            jmlmenu++;
        }

        if (akses.getpembayaran_ranap() == true) {
            FormMenu.add(btnRanapMasuk);
            jmlmenu++;
        }

        if (akses.getpiutang_pasien() == true) {
            FormMenu.add(btnLihatPiutang);
            jmlmenu++;
        }

        if (akses.getpiutang_ralan() == true) {
            FormMenu.add(btnPiutangRalan);
            jmlmenu++;
        }

        if (akses.getpiutang_ranap() == true) {
            FormMenu.add(btnPiutangRanap);
            jmlmenu++;
        }

        if (akses.gettagihan_masuk() == true) {
            FormMenu.add(btnTagihanMasuk);
            jmlmenu++;
        }

        if (akses.gettambahan_biaya() == true) {
            FormMenu.add(btnTambahanBiaya);
            jmlmenu++;
        }

        if (akses.getpotongan_biaya() == true) {
            FormMenu.add(btnPotonganBiaya);
            jmlmenu++;
        }

        if (akses.getrekap_per_shift() == true) {
            FormMenu.add(btnRekapPershift);
            jmlmenu++;
        }

        if (akses.getpayment_point() == true) {
            FormMenu.add(btnPaymentPoint);
            jmlmenu++;
        }

        aturLayoutMenu();

        FormMenu.revalidate();
        FormMenu.repaint();
    }
    
    private void aturLayoutMenu() {
        int lebarViewport = scrollMenu.getViewport().getExtentSize().width;
        int tinggiViewport = scrollMenu.getViewport().getExtentSize().height;

        if (lebarViewport <= 0) {
            lebarViewport = scrollMenu.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport = scrollMenu.getHeight();
        }

        if (lebarViewport <= 0) {
            lebarViewport = internalFrame1.getWidth();
        }

        if (tinggiViewport <= 0) {
            tinggiViewport
                    = internalFrame1.getHeight() - internalFrame2.getHeight();
        }

        /*
     * Sama seperti menu frmUtama:
     * jumlah menu menentukan jumlah kolom.
         */
        if (jmlmenu <= 1) {
            grid = 1;
        } else if (jmlmenu <= 4) {
            grid = 2;
        } else if (jmlmenu <= 9) {
            grid = 3;
        } else if (jmlmenu <= 16) {
            grid = 4;
        } else {
            grid = 5;
        }

        int tinggiTombol = 120;
        int jarakHorizontal = 5;
        int jarakVertikal = 35;

        int jumlahBaris = (int) Math.ceil(
                (double) jmlmenu / grid
        );

        int tinggiIsi
                = (jumlahBaris * tinggiTombol)
                + (Math.max(0, jumlahBaris - 1) * jarakVertikal)
                + 20;

        /*
     * Jika isi lebih tinggi dari viewport,
     * scrollbar otomatis muncul.
         */
        tinggi = Math.max(tinggiViewport, tinggiIsi);

        FormMenu.setLayout(new GridLayout(
                0,
                grid,
                jarakHorizontal,
                jarakVertikal
        ));

        Dimension ukuranMenu = new Dimension(
                Math.max(lebarViewport - 10, 200),
                tinggi
        );

        FormMenu.setPreferredSize(ukuranMenu);
        FormMenu.setMinimumSize(ukuranMenu);

        scrollMenu.setVerticalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        );

        scrollMenu.setHorizontalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
        );

        scrollMenu.getVerticalScrollBar().setUnitIncrement(16);
        scrollMenu.getVerticalScrollBar().setBlockIncrement(120);

        FormMenu.revalidate();
        FormMenu.repaint();

        scrollMenu.getViewport().revalidate();
        scrollMenu.getViewport().repaint();

        scrollMenu.revalidate();
        scrollMenu.repaint();
    }

    private void aturTampilanTombol() {
        java.awt.Component[] komponen = FormMenu.getComponents();

        for (java.awt.Component komponenMenu : komponen) {
            if (komponenMenu instanceof widget.ButtonBig) {
                widget.ButtonBig tombol
                        = (widget.ButtonBig) komponenMenu;

                tombol.setHorizontalAlignment(
                        javax.swing.SwingConstants.CENTER
                );

                tombol.setVerticalAlignment(
                        javax.swing.SwingConstants.CENTER
                );
            }
        }
    }
}
