package rekammedis;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import simrskhanza.frmUtama;

/**
 *
 * @author dosen
 */
public class DlgHistoriIPAddressPetugasERM extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i = 0, x = 0;
    private String gedung = "";
    private frmUtama formUtama;
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgHistoriIPAddressPetugasERM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[]{
            "No. Rawat", "No. RM", "Nama Pasien", "Dokumen Rekam Medis", "Proses", "NIP/NR", "Nama Petugas", "IP Address", 
            "Ruang Rawat/Poliklinik/Inst.", "Tgl. Eksekusi", "Jam Eksekusi", "waktu_simpan"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        tbHistori.setModel(tabMode);
        tbHistori.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbHistori.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 12; i++) {
            TableColumn column = tbHistori.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(105);
            } else if (i == 1) {
                column.setPreferredWidth(65);
            } else if (i == 2) {
                column.setPreferredWidth(220);
            } else if (i == 3) {
                column.setPreferredWidth(300);
            } else if (i == 4) {
                column.setPreferredWidth(120);
            } else if (i == 5) {
                column.setPreferredWidth(130);
            } else if (i == 6) {
                column.setPreferredWidth(220);
            } else if (i == 7) {
                column.setPreferredWidth(100);
            } else if (i == 8) {
                column.setPreferredWidth(200);
            } else if (i == 9) {
                column.setPreferredWidth(80);
            } else if (i == 10) {
                column.setPreferredWidth(80);
            } else if (i == 11) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }
        tbHistori.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
        
//        if(koneksiDB.cariCepat().equals("aktif")){
//            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
//                @Override
//                public void insertUpdate(DocumentEvent e) {tampil();}
//                @Override
//                public void removeUpdate(DocumentEvent e) {tampil();}
//                @Override
//                public void changedUpdate(DocumentEvent e) {tampil();}
//            });
//        }
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnHapus = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        internalFrame2 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbHistori = new widget.Table();
        panelGlass8 = new widget.panelisi();
        jLabel19 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        jLabel21 = new widget.Label();
        DTPCari2 = new widget.Tanggal();
        jLabel8 = new widget.Label();
        cmbDokumen = new widget.ComboBox();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnHapus.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/delete-16x16.png"))); // NOI18N
        MnHapus.setText("Hapus Data");
        MnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnHapus.setIconTextGap(5);
        MnHapus.setName("MnHapus"); // NOI18N
        MnHapus.setPreferredSize(new java.awt.Dimension(110, 26));
        MnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHapusActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnHapus);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ History IP Address Petugas e-RM ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame2.setBorder(null);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbHistori.setAutoCreateRowSorter(true);
        tbHistori.setComponentPopupMenu(jPopupMenu1);
        tbHistori.setName("tbHistori"); // NOI18N
        Scroll.setViewportView(tbHistori);

        internalFrame2.add(Scroll, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Tgl. Simpan :");
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass8.add(jLabel19);

        DTPCari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-02-2025" }));
        DTPCari1.setDisplayFormat("dd-MM-yyyy");
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass8.add(DTPCari1);

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("s.d.");
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(23, 23));
        panelGlass8.add(jLabel21);

        DTPCari2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-02-2025" }));
        DTPCari2.setDisplayFormat("dd-MM-yyyy");
        DTPCari2.setName("DTPCari2"); // NOI18N
        DTPCari2.setOpaque(false);
        DTPCari2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass8.add(DTPCari2);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dokumen RM :");
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(85, 23));
        panelGlass8.add(jLabel8);

        cmbDokumen.setForeground(new java.awt.Color(0, 0, 0));
        cmbDokumen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmbDokumen.setName("cmbDokumen"); // NOI18N
        cmbDokumen.setPreferredSize(new java.awt.Dimension(270, 24));
        cmbDokumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbDokumenMouseReleased(evt);
            }
        });
        panelGlass8.add(cmbDokumen);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass8.add(jLabel6);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(200, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass8.add(TCari);

        BtnCari.setForeground(new java.awt.Color(0, 0, 0));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setText("Tampilkan Data");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnCari);

        BtnAll.setForeground(new java.awt.Color(0, 0, 0));
        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setText("Semua");
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnAll);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass8.add(jLabel7);

        LCount.setForeground(new java.awt.Color(0, 0, 0));
        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass8.add(LCount);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        frmUtama.getInstance().tutupDialogDiPanelUtama(this);
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            frmUtama.getInstance().tutupDialogDiPanelUtama(this);
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        cmbDokumen.setSelectedIndex(0);
        BtnCariActionPerformed(null);
}//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
            TCari.setText("");
        }
}//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Sequel.cariIsiComboDB("SELECT dokumen_rekam_medis FROM histori_petugas_erm GROUP BY dokumen_rekam_medis ORDER BY dokumen_rekam_medis", cmbDokumen);
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void cmbDokumenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDokumenMouseReleased
        AutoCompleteDecorator.decorate(cmbDokumen);
    }//GEN-LAST:event_cmbDokumenMouseReleased

    private void MnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHapusActionPerformed
        if (tbHistori.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, tabel masih kosong..!!");
            DTPCari1.requestFocus();
        } else {
            if (tbHistori.getSelectedRow() > -1) {
                x = JOptionPane.showConfirmDialog(rootPane, "Yakin data mau dihapus..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    if (Sequel.queryu2tf("delete from histori_petugas_erm where waktu_simpan=?", 1, new String[]{
                        tbHistori.getValueAt(tbHistori.getSelectedRow(), 11).toString()
                    }) == true) {
                        tampil();
                    } else {
                        JOptionPane.showMessageDialog(null, "Gagal menghapus data..!!");
                    }
                } else {
                    tampil();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Silahkan pilih dulu salah satu datanya pada tabel..!!");
                tbHistori.requestFocus();
            }
        }
    }//GEN-LAST:event_MnHapusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgHistoriIPAddressPetugasERM dialog = new DlgHistoriIPAddressPetugasERM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Tanggal DTPCari1;
    private widget.Tanggal DTPCari2;
    private widget.Label LCount;
    private javax.swing.JMenuItem MnHapus;
    private widget.ScrollPane Scroll;
    public widget.TextBox TCari;
    private widget.ComboBox cmbDokumen;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel19;
    private widget.Label jLabel21;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.panelisi panelGlass8;
    private widget.Table tbHistori;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        gedung = "";
        Valid.tabelKosong(tabMode);
        StringBuilder sb = new StringBuilder();
        try {
            if (cmbDokumen.getSelectedIndex() == 0) {
                sb.append("select h.*, if(h.nip_petugas='-','Admin Utama',pg.nama) nmpetugas, date_format(h.waktu_simpan,'%d/%m/%Y') tgl, ");
                sb.append("time_format(h.waktu_simpan,'%H:%i:%s') jam, p.no_rkm_medis, p.nm_pasien, rp.status_lanjut, rp.kd_poli from histori_petugas_erm h ");
                sb.append("inner join reg_periksa rp on rp.no_rawat=h.no_rawat inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis ");
                sb.append("inner join pegawai pg on pg.nik=h.nip_petugas where ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.no_rawat like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.proses_eksekusi like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.nip_petugas like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.ip_address like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and pg.nama like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and p.no_rkm_medis like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and p.nm_pasien like ? order by h.waktu_simpan desc");
                ps = koneksi.prepareStatement(sb.toString());
            } else {
                sb.append("select h.*, if(h.nip_petugas='-','Admin Utama',pg.nama) nmpetugas, date_format(h.waktu_simpan,'%d/%m/%Y') tgl, ");
                sb.append("time_format(h.waktu_simpan,'%H:%i:%s') jam, p.no_rkm_medis, p.nm_pasien, rp.status_lanjut, rp.kd_poli from histori_petugas_erm h ");
                sb.append("inner join reg_periksa rp on rp.no_rawat=h.no_rawat inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis ");
                sb.append("inner join pegawai pg on pg.nik=h.nip_petugas where ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and h.no_rawat like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and h.proses_eksekusi like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and h.nip_petugas like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and h.ip_address like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and pg.nama like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and p.no_rkm_medis like ? or ");
                sb.append("date(h.waktu_simpan) between ? and ? and h.dokumen_rekam_medis like ? and p.nm_pasien like ? order by h.waktu_simpan desc");
                ps = koneksi.prepareStatement(sb.toString());
            }
            try {
                if (cmbDokumen.getSelectedIndex() == 0) {
                    ps.setString(1, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(2, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(3, "%" + TCari.getText().trim() + "%");                    
                    ps.setString(4, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(5, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(6, "%" + TCari.getText().trim() + "%");                    
                    ps.setString(7, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(8, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(9, "%" + TCari.getText().trim() + "%");
                    ps.setString(10, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(11, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(12, "%" + TCari.getText().trim() + "%");
                    ps.setString(13, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(14, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(15, "%" + TCari.getText().trim() + "%");
                    ps.setString(16, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(17, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(18, "%" + TCari.getText().trim() + "%");
                    ps.setString(19, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(20, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(21, "%" + TCari.getText().trim() + "%");
                } else {
                    ps.setString(1, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(2, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(3, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(4, "%" + TCari.getText().trim() + "%");
                    ps.setString(5, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(6, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(7, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(8, "%" + TCari.getText().trim() + "%");                    
                    ps.setString(9, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(10, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(11, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(12, "%" + TCari.getText().trim() + "%");
                    ps.setString(13, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(14, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(15, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(16, "%" + TCari.getText().trim() + "%");
                    ps.setString(17, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(18, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(19, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(20, "%" + TCari.getText().trim() + "%");
                    ps.setString(21, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(22, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(23, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(24, "%" + TCari.getText().trim() + "%");
                    ps.setString(25, Valid.SetTgl(DTPCari1.getSelectedItem() + ""));
                    ps.setString(26, Valid.SetTgl(DTPCari2.getSelectedItem() + ""));
                    ps.setString(27, "%" + cmbDokumen.getSelectedItem().toString() + "%");
                    ps.setString(28, "%" + TCari.getText().trim() + "%");
                }
                rs = ps.executeQuery();
                while (rs.next()) {
                    if (rs.getString("status_lanjut").equals("Ralan")) {
                        gedung = Sequel.cariIsi("select nm_poli from poliklinik where kd_poli='" + rs.getString("kd_poli") + "'");
                    } else {
                        gedung = Sequel.cariIsi("select b.nm_gedung from kamar_inap ki inner join kamar k on k.kd_kamar=ki.kd_kamar inner join bangsal b on b.kd_bangsal=k.kd_bangsal "
                                + "where ki.no_rawat='" + rs.getString("no_rawat") + "' order by ki.tgl_masuk desc, ki.jam_masuk desc limit 1");
                    }
                    
                    tabMode.addRow(new String[]{
                        rs.getString("no_rawat"),
                        rs.getString("no_rkm_medis"),
                        rs.getString("nm_pasien"),
                        rs.getString("dokumen_rekam_medis"),
                        rs.getString("proses_eksekusi"),
                        rs.getString("nip_petugas"),
                        rs.getString("nmpetugas"),
                        rs.getString("ip_address"),
                        gedung,
                        rs.getString("tgl"),
                        rs.getString("jam"),
                        rs.getString("waktu_simpan")
                    });
                }                
            } catch (Exception e) {
                System.out.println("rekammedis.DlgHistoriIPAddressPetugasERM.tampil() : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (SQLException e) {
            System.out.println("Notifikasi : " + e);
        }
        LCount.setText("" + tabMode.getRowCount());
    }
    
    public void awalData() {
        Sequel.cariIsiComboDB("SELECT dokumen_rekam_medis FROM histori_petugas_erm GROUP BY dokumen_rekam_medis ORDER BY dokumen_rekam_medis", cmbDokumen);
    }
}
