package rekammedis;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import inventory.DlgCatatanResep;
import inventory.DlgPemberianObatPasien;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import permintaan.DlgSuratJawabanKonsul;
import permintaan.DlgSuratKonsulUnit;
import simrskhanza.DlgCariDokter;
import simrskhanza.DlgPemberianDiet;
import simrskhanza.DlgRingkasanPulangRanap;

/**
 *
 * @author dosen
 */
public class DlgRMEranap extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private int i = 0, x = 0;
    private DlgCariDokter dokter = new DlgCariDokter(null, false);
    private String stts = "", kdkamar = "", gedung = "";
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgRMEranap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        dokter.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {;
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (akses.getform().equals("DlgRMEranap")) {
                    if (dokter.getTable().getSelectedRow() != -1) {
                        kddpjp.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(), 0).toString());
                        nmdpjp.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(), 1).toString());
                        btnDPJP.requestFocus();                        
                    }
                }
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowDPJPranap = new javax.swing.JDialog();
        internalFrame15 = new widget.InternalFrame();
        BtnCloseIn10 = new widget.Button();
        BtnSimpan6 = new widget.Button();
        jLabel52 = new widget.Label();
        kddpjp = new widget.TextBox();
        nmdpjp = new widget.TextBox();
        btnDPJP = new widget.Button();
        internalFrame1 = new widget.InternalFrame();
        internalFrame4 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        nmUnit = new widget.TextBox();
        jLabel4 = new widget.Label();
        TtglMasuk = new widget.TextBox();
        internalFrame2 = new widget.InternalFrame();
        scrollInput = new widget.ScrollPane();
        FormInput = new widget.PanelBiasa();
        BtnAsesmenRestrain = new widget.ButtonBig();
        BtnObservasiRestrain = new widget.ButtonBig();
        BtnAsesmenMedikDewasa = new widget.ButtonBig();
        BtnAsesmenMedikAnak = new widget.ButtonBig();
        BtnAsesmenKeperawatanDewasa = new widget.ButtonBig();
        BtnAsesmenKeperawatanAnak = new widget.ButtonBig();
        BtnCPPT = new widget.ButtonBig();
        BtnResep = new widget.ButtonBig();
        BtnRingkasan = new widget.ButtonBig();
        BtnCTK = new widget.ButtonBig();
        BtnAsesmenUlangRJDewasa = new widget.ButtonBig();
        BtnAsesmenUlangRJAnak = new widget.ButtonBig();
        BtnTransferSerahTerima = new widget.ButtonBig();
        BtnLembarObservasi = new widget.ButtonBig();
        BtnPengelolaanTranfusiDarah = new widget.ButtonBig();
        BtnMonitoringEWSdewasa = new widget.ButtonBig();
        BtnMonitoringPEWSanak = new widget.ButtonBig();
        BtnJadwalObat = new widget.ButtonBig();
        BtnTransferTindakan = new widget.ButtonBig();
        BtnAsesmenPraSedasi = new widget.ButtonBig();
        BtnAsesmenPreInduksi = new widget.ButtonBig();
        BtnAsesmenKeperawatanPerioperatif = new widget.ButtonBig();
        BtnCeklisPraOperasi = new widget.ButtonBig();
        BtnCeklisKesiapanAnestesi = new widget.ButtonBig();
        BtnKonsul = new widget.ButtonBig();
        BtnJawabKonsul = new widget.ButtonBig();
        BtnPersetujuanTindakan = new widget.ButtonBig();
        BtnPantauHarianPasien = new widget.ButtonBig();
        BtnGrafikPantauHarian = new widget.ButtonBig();
        BtnProtokolKemoterapi = new widget.ButtonBig();
        BtnDokumenJangMed = new widget.ButtonBig();
        BtnSkriningUlangGizi = new widget.ButtonBig();
        BtnAsuhanGizi = new widget.ButtonBig();
        BtnMonevAsuhanGizi = new widget.ButtonBig();
        BtnAsesmenUlangGizi = new widget.ButtonBig();
        internalFrame3 = new widget.InternalFrame();
        BtnRefres = new widget.Button();
        BtnKeluar = new widget.Button();

        WindowDPJPranap.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowDPJPranap.setName("WindowDPJPranap"); // NOI18N
        WindowDPJPranap.setUndecorated(true);
        WindowDPJPranap.setResizable(false);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ DPJP Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame15.setLayout(null);

        BtnCloseIn10.setForeground(new java.awt.Color(0, 0, 0));
        BtnCloseIn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnCloseIn10.setMnemonic('U');
        BtnCloseIn10.setText("Tutup");
        BtnCloseIn10.setToolTipText("Alt+U");
        BtnCloseIn10.setName("BtnCloseIn10"); // NOI18N
        BtnCloseIn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseIn10ActionPerformed(evt);
            }
        });
        internalFrame15.add(BtnCloseIn10);
        BtnCloseIn10.setBounds(480, 60, 100, 30);

        BtnSimpan6.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan6.setMnemonic('S');
        BtnSimpan6.setText("Simpan");
        BtnSimpan6.setToolTipText("Alt+S");
        BtnSimpan6.setName("BtnSimpan6"); // NOI18N
        BtnSimpan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpan6ActionPerformed(evt);
            }
        });
        internalFrame15.add(BtnSimpan6);
        BtnSimpan6.setBounds(370, 60, 100, 30);

        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Nama DPJP :");
        jLabel52.setName("jLabel52"); // NOI18N
        internalFrame15.add(jLabel52);
        jLabel52.setBounds(0, 32, 77, 23);

        kddpjp.setEditable(false);
        kddpjp.setForeground(new java.awt.Color(0, 0, 0));
        kddpjp.setName("kddpjp"); // NOI18N
        internalFrame15.add(kddpjp);
        kddpjp.setBounds(81, 32, 100, 23);

        nmdpjp.setEditable(false);
        nmdpjp.setForeground(new java.awt.Color(0, 0, 0));
        nmdpjp.setName("nmdpjp"); // NOI18N
        internalFrame15.add(nmdpjp);
        nmdpjp.setBounds(183, 32, 380, 23);

        btnDPJP.setForeground(new java.awt.Color(0, 0, 0));
        btnDPJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnDPJP.setMnemonic('7');
        btnDPJP.setToolTipText("ALt+7");
        btnDPJP.setName("btnDPJP"); // NOI18N
        btnDPJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPJPActionPerformed(evt);
            }
        });
        internalFrame15.add(btnDPJP);
        btnDPJP.setBounds(565, 32, 28, 23);

        WindowDPJPranap.getContentPane().add(internalFrame15, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Rekam Medis Elektronik ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame4.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pasien :");
        jLabel3.setName("jLabel3"); // NOI18N
        internalFrame4.add(jLabel3);
        jLabel3.setBounds(0, 10, 103, 23);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        internalFrame4.add(TNoRW);
        TNoRW.setBounds(107, 10, 122, 23);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        internalFrame4.add(TNoRM);
        TNoRM.setBounds(233, 10, 70, 23);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        internalFrame4.add(TNmPasien);
        TNmPasien.setBounds(308, 10, 291, 23);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rg. Rawat :");
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame4.add(jLabel13);
        jLabel13.setBounds(0, 38, 103, 23);

        nmUnit.setEditable(false);
        nmUnit.setForeground(new java.awt.Color(0, 0, 0));
        nmUnit.setName("nmUnit"); // NOI18N
        internalFrame4.add(nmUnit);
        nmUnit.setBounds(107, 38, 492, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tgl. Masuk :");
        jLabel4.setName("jLabel4"); // NOI18N
        internalFrame4.add(jLabel4);
        jLabel4.setBounds(0, 66, 103, 23);

        TtglMasuk.setEditable(false);
        TtglMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TtglMasuk.setName("TtglMasuk"); // NOI18N
        internalFrame4.add(TtglMasuk);
        TtglMasuk.setBounds(107, 66, 210, 23);

        internalFrame1.add(internalFrame4, java.awt.BorderLayout.PAGE_START);

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(2800, 2800));
        internalFrame2.setLayout(new java.awt.BorderLayout());

        scrollInput.setName("scrollInput"); // NOI18N
        scrollInput.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput.setBackground(new java.awt.Color(255, 255, 255));
        FormInput.setBorder(null);
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(870, 750));
        FormInput.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAsesmenRestrain.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenRestrain.setText("Asesmen Restrain");
        BtnAsesmenRestrain.setToolTipText("");
        BtnAsesmenRestrain.setIconTextGap(0);
        BtnAsesmenRestrain.setName("BtnAsesmenRestrain"); // NOI18N
        BtnAsesmenRestrain.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenRestrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenRestrainActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenRestrain);

        BtnObservasiRestrain.setForeground(new java.awt.Color(0, 0, 0));
        BtnObservasiRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnObservasiRestrain.setText("Observasi Restrain");
        BtnObservasiRestrain.setToolTipText("");
        BtnObservasiRestrain.setIconTextGap(0);
        BtnObservasiRestrain.setName("BtnObservasiRestrain"); // NOI18N
        BtnObservasiRestrain.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnObservasiRestrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObservasiRestrainActionPerformed(evt);
            }
        });
        FormInput.add(BtnObservasiRestrain);

        BtnAsesmenMedikDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenMedikDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenMedikDewasa.setText("Asesmen Medik Dewasa");
        BtnAsesmenMedikDewasa.setToolTipText("");
        BtnAsesmenMedikDewasa.setIconTextGap(0);
        BtnAsesmenMedikDewasa.setName("BtnAsesmenMedikDewasa"); // NOI18N
        BtnAsesmenMedikDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenMedikDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenMedikDewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenMedikDewasa);

        BtnAsesmenMedikAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenMedikAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenMedikAnak.setText("Asesmen Medik Anak");
        BtnAsesmenMedikAnak.setToolTipText("");
        BtnAsesmenMedikAnak.setIconTextGap(0);
        BtnAsesmenMedikAnak.setName("BtnAsesmenMedikAnak"); // NOI18N
        BtnAsesmenMedikAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenMedikAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenMedikAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenMedikAnak);

        BtnAsesmenKeperawatanDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenKeperawatanDewasa.setText("Asesmen Keperawatan Dewasa");
        BtnAsesmenKeperawatanDewasa.setIconTextGap(0);
        BtnAsesmenKeperawatanDewasa.setName("BtnAsesmenKeperawatanDewasa"); // NOI18N
        BtnAsesmenKeperawatanDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenKeperawatanDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenKeperawatanDewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenKeperawatanDewasa);

        BtnAsesmenKeperawatanAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenKeperawatanAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenKeperawatanAnak.setText("Asesmen Keperawatan Anak");
        BtnAsesmenKeperawatanAnak.setIconTextGap(0);
        BtnAsesmenKeperawatanAnak.setName("BtnAsesmenKeperawatanAnak"); // NOI18N
        BtnAsesmenKeperawatanAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenKeperawatanAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenKeperawatanAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenKeperawatanAnak);

        BtnCPPT.setForeground(new java.awt.Color(0, 0, 0));
        BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnCPPT.setText("CPPT");
        BtnCPPT.setIconTextGap(0);
        BtnCPPT.setName("BtnCPPT"); // NOI18N
        BtnCPPT.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCPPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCPPTActionPerformed(evt);
            }
        });
        FormInput.add(BtnCPPT);

        BtnResep.setForeground(new java.awt.Color(0, 0, 0));
        BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726.png"))); // NOI18N
        BtnResep.setText("Resep Obat");
        BtnResep.setIconTextGap(0);
        BtnResep.setName("BtnResep"); // NOI18N
        BtnResep.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResepActionPerformed(evt);
            }
        });
        FormInput.add(BtnResep);

        BtnRingkasan.setForeground(new java.awt.Color(0, 0, 0));
        BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnRingkasan.setText("Ringkasan Pulang / Resume");
        BtnRingkasan.setIconTextGap(0);
        BtnRingkasan.setName("BtnRingkasan"); // NOI18N
        BtnRingkasan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRingkasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRingkasanActionPerformed(evt);
            }
        });
        FormInput.add(BtnRingkasan);

        BtnCTK.setForeground(new java.awt.Color(0, 0, 0));
        BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnCTK.setText("Catatan Tindakan Keperawatan");
        BtnCTK.setIconTextGap(0);
        BtnCTK.setName("BtnCTK"); // NOI18N
        BtnCTK.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCTKActionPerformed(evt);
            }
        });
        FormInput.add(BtnCTK);

        BtnAsesmenUlangRJDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenUlangRJDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenUlangRJDewasa.setText("Ases. Ulang Resiko Jatuh Dewasa");
        BtnAsesmenUlangRJDewasa.setIconTextGap(0);
        BtnAsesmenUlangRJDewasa.setName("BtnAsesmenUlangRJDewasa"); // NOI18N
        BtnAsesmenUlangRJDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenUlangRJDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenUlangRJDewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenUlangRJDewasa);

        BtnAsesmenUlangRJAnak.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenUlangRJAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenUlangRJAnak.setText("Ases. Ulang Resiko Jatuh Anak");
        BtnAsesmenUlangRJAnak.setIconTextGap(0);
        BtnAsesmenUlangRJAnak.setName("BtnAsesmenUlangRJAnak"); // NOI18N
        BtnAsesmenUlangRJAnak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenUlangRJAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenUlangRJAnakActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenUlangRJAnak);

        BtnTransferSerahTerima.setForeground(new java.awt.Color(0, 0, 0));
        BtnTransferSerahTerima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnTransferSerahTerima.setText("Transfer & Serah Terima Pasien");
        BtnTransferSerahTerima.setIconTextGap(0);
        BtnTransferSerahTerima.setName("BtnTransferSerahTerima"); // NOI18N
        BtnTransferSerahTerima.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTransferSerahTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferSerahTerimaActionPerformed(evt);
            }
        });
        FormInput.add(BtnTransferSerahTerima);

        BtnLembarObservasi.setForeground(new java.awt.Color(0, 0, 0));
        BtnLembarObservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist_pencil-o.png"))); // NOI18N
        BtnLembarObservasi.setText("Lembar Observasi");
        BtnLembarObservasi.setIconTextGap(0);
        BtnLembarObservasi.setName("BtnLembarObservasi"); // NOI18N
        BtnLembarObservasi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnLembarObservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLembarObservasiActionPerformed(evt);
            }
        });
        FormInput.add(BtnLembarObservasi);

        BtnPengelolaanTranfusiDarah.setForeground(new java.awt.Color(0, 0, 0));
        BtnPengelolaanTranfusiDarah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481001585_blood_drop_biru.png"))); // NOI18N
        BtnPengelolaanTranfusiDarah.setText("Pengelolaan Transfusi Darah");
        BtnPengelolaanTranfusiDarah.setIconTextGap(0);
        BtnPengelolaanTranfusiDarah.setName("BtnPengelolaanTranfusiDarah"); // NOI18N
        BtnPengelolaanTranfusiDarah.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPengelolaanTranfusiDarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengelolaanTranfusiDarahActionPerformed(evt);
            }
        });
        FormInput.add(BtnPengelolaanTranfusiDarah);

        BtnMonitoringEWSdewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringEWSdewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnMonitoringEWSdewasa.setText("Monitoring EWS Dewasa");
        BtnMonitoringEWSdewasa.setIconTextGap(0);
        BtnMonitoringEWSdewasa.setName("BtnMonitoringEWSdewasa"); // NOI18N
        BtnMonitoringEWSdewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringEWSdewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringEWSdewasaActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringEWSdewasa);

        BtnMonitoringPEWSanak.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonitoringPEWSanak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png"))); // NOI18N
        BtnMonitoringPEWSanak.setText("Monitoring Pediatric EWS");
        BtnMonitoringPEWSanak.setIconTextGap(0);
        BtnMonitoringPEWSanak.setName("BtnMonitoringPEWSanak"); // NOI18N
        BtnMonitoringPEWSanak.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonitoringPEWSanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitoringPEWSanakActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonitoringPEWSanak);

        BtnJadwalObat.setForeground(new java.awt.Color(0, 0, 0));
        BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel.png"))); // NOI18N
        BtnJadwalObat.setText("Jadwal Beri Obat Oral/Injeksi");
        BtnJadwalObat.setIconTextGap(0);
        BtnJadwalObat.setName("BtnJadwalObat"); // NOI18N
        BtnJadwalObat.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnJadwalObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJadwalObatActionPerformed(evt);
            }
        });
        FormInput.add(BtnJadwalObat);

        BtnTransferTindakan.setForeground(new java.awt.Color(0, 0, 0));
        BtnTransferTindakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481002123_wheelchair.png"))); // NOI18N
        BtnTransferTindakan.setText("Transfer Pasien Untuk Tindakan");
        BtnTransferTindakan.setIconTextGap(0);
        BtnTransferTindakan.setName("BtnTransferTindakan"); // NOI18N
        BtnTransferTindakan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnTransferTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferTindakanActionPerformed(evt);
            }
        });
        FormInput.add(BtnTransferTindakan);

        BtnAsesmenPraSedasi.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenPraSedasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/anastesi2.png"))); // NOI18N
        BtnAsesmenPraSedasi.setText("Asesmen Pra Sedasi");
        BtnAsesmenPraSedasi.setIconTextGap(0);
        BtnAsesmenPraSedasi.setName("BtnAsesmenPraSedasi"); // NOI18N
        BtnAsesmenPraSedasi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenPraSedasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenPraSedasiActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenPraSedasi);

        BtnAsesmenPreInduksi.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenPreInduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/anastesi1.png"))); // NOI18N
        BtnAsesmenPreInduksi.setText("Asesmen Pre Induksi");
        BtnAsesmenPreInduksi.setIconTextGap(0);
        BtnAsesmenPreInduksi.setName("BtnAsesmenPreInduksi"); // NOI18N
        BtnAsesmenPreInduksi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenPreInduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenPreInduksiActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenPreInduksi);

        BtnAsesmenKeperawatanPerioperatif.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenKeperawatanPerioperatif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_TextEdit_37595.png"))); // NOI18N
        BtnAsesmenKeperawatanPerioperatif.setText("Assesmen Keprwtn. Perioperatif");
        BtnAsesmenKeperawatanPerioperatif.setIconTextGap(0);
        BtnAsesmenKeperawatanPerioperatif.setName("BtnAsesmenKeperawatanPerioperatif"); // NOI18N
        BtnAsesmenKeperawatanPerioperatif.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenKeperawatanPerioperatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenKeperawatanPerioperatifActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenKeperawatanPerioperatif);

        BtnCeklisPraOperasi.setForeground(new java.awt.Color(0, 0, 0));
        BtnCeklisPraOperasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist.png"))); // NOI18N
        BtnCeklisPraOperasi.setText("Checklist Pra Operasi");
        BtnCeklisPraOperasi.setIconTextGap(0);
        BtnCeklisPraOperasi.setName("BtnCeklisPraOperasi"); // NOI18N
        BtnCeklisPraOperasi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCeklisPraOperasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCeklisPraOperasiActionPerformed(evt);
            }
        });
        FormInput.add(BtnCeklisPraOperasi);

        BtnCeklisKesiapanAnestesi.setForeground(new java.awt.Color(0, 0, 0));
        BtnCeklisKesiapanAnestesi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checklist.png"))); // NOI18N
        BtnCeklisKesiapanAnestesi.setText("Checklist Kesiapan Anestesi");
        BtnCeklisKesiapanAnestesi.setIconTextGap(0);
        BtnCeklisKesiapanAnestesi.setName("BtnCeklisKesiapanAnestesi"); // NOI18N
        BtnCeklisKesiapanAnestesi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCeklisKesiapanAnestesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCeklisKesiapanAnestesiActionPerformed(evt);
            }
        });
        FormInput.add(BtnCeklisKesiapanAnestesi);

        BtnKonsul.setForeground(new java.awt.Color(0, 0, 0));
        BtnKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/email_open.png"))); // NOI18N
        BtnKonsul.setText("Permintaan Konsul Antar Unit");
        BtnKonsul.setIconTextGap(0);
        BtnKonsul.setName("BtnKonsul"); // NOI18N
        BtnKonsul.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonsulActionPerformed(evt);
            }
        });
        FormInput.add(BtnKonsul);

        BtnJawabKonsul.setForeground(new java.awt.Color(0, 0, 0));
        BtnJawabKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kwrite.png"))); // NOI18N
        BtnJawabKonsul.setText("Jawaban Konsul Antar Unit");
        BtnJawabKonsul.setIconTextGap(0);
        BtnJawabKonsul.setName("BtnJawabKonsul"); // NOI18N
        BtnJawabKonsul.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnJawabKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJawabKonsulActionPerformed(evt);
            }
        });
        FormInput.add(BtnJawabKonsul);

        BtnPersetujuanTindakan.setForeground(new java.awt.Color(0, 0, 0));
        BtnPersetujuanTindakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_todo_list_add_17451.png"))); // NOI18N
        BtnPersetujuanTindakan.setText("Persetujuan/Penolakan Tindakan");
        BtnPersetujuanTindakan.setIconTextGap(0);
        BtnPersetujuanTindakan.setName("BtnPersetujuanTindakan"); // NOI18N
        BtnPersetujuanTindakan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPersetujuanTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPersetujuanTindakanActionPerformed(evt);
            }
        });
        FormInput.add(BtnPersetujuanTindakan);

        BtnPantauHarianPasien.setForeground(new java.awt.Color(0, 0, 0));
        BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png"))); // NOI18N
        BtnPantauHarianPasien.setText("Pemantauan Harian Pasien");
        BtnPantauHarianPasien.setIconTextGap(0);
        BtnPantauHarianPasien.setName("BtnPantauHarianPasien"); // NOI18N
        BtnPantauHarianPasien.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPantauHarianPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPantauHarianPasienActionPerformed(evt);
            }
        });
        FormInput.add(BtnPantauHarianPasien);

        BtnGrafikPantauHarian.setForeground(new java.awt.Color(0, 0, 0));
        BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png"))); // NOI18N
        BtnGrafikPantauHarian.setText("Grafik Pemantauan Harian Pasien");
        BtnGrafikPantauHarian.setIconTextGap(0);
        BtnGrafikPantauHarian.setName("BtnGrafikPantauHarian"); // NOI18N
        BtnGrafikPantauHarian.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnGrafikPantauHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrafikPantauHarianActionPerformed(evt);
            }
        });
        FormInput.add(BtnGrafikPantauHarian);

        BtnProtokolKemoterapi.setForeground(new java.awt.Color(0, 0, 0));
        BtnProtokolKemoterapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_30-Doctor_5929214.png"))); // NOI18N
        BtnProtokolKemoterapi.setText("Protokol Kemoterapi");
        BtnProtokolKemoterapi.setIconTextGap(0);
        BtnProtokolKemoterapi.setName("BtnProtokolKemoterapi"); // NOI18N
        BtnProtokolKemoterapi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnProtokolKemoterapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProtokolKemoterapiActionPerformed(evt);
            }
        });
        FormInput.add(BtnProtokolKemoterapi);

        BtnDokumenJangMed.setForeground(new java.awt.Color(0, 0, 0));
        BtnDokumenJangMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/x-office-address-book.png"))); // NOI18N
        BtnDokumenJangMed.setText("Dokumen Penunjang Medis");
        BtnDokumenJangMed.setIconTextGap(0);
        BtnDokumenJangMed.setName("BtnDokumenJangMed"); // NOI18N
        BtnDokumenJangMed.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnDokumenJangMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDokumenJangMedActionPerformed(evt);
            }
        });
        FormInput.add(BtnDokumenJangMed);

        BtnSkriningUlangGizi.setForeground(new java.awt.Color(0, 0, 0));
        BtnSkriningUlangGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/if_order-history_49596.png"))); // NOI18N
        BtnSkriningUlangGizi.setText("Skrining Gizi Ulang");
        BtnSkriningUlangGizi.setIconTextGap(0);
        BtnSkriningUlangGizi.setName("BtnSkriningUlangGizi"); // NOI18N
        BtnSkriningUlangGizi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnSkriningUlangGizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSkriningUlangGiziActionPerformed(evt);
            }
        });
        FormInput.add(BtnSkriningUlangGizi);

        BtnAsuhanGizi.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsuhanGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsuhanGizi.setText("Asuhan Gizi");
        BtnAsuhanGizi.setIconTextGap(0);
        BtnAsuhanGizi.setName("BtnAsuhanGizi"); // NOI18N
        BtnAsuhanGizi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsuhanGizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsuhanGiziActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsuhanGizi);

        BtnMonevAsuhanGizi.setForeground(new java.awt.Color(0, 0, 0));
        BtnMonevAsuhanGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        BtnMonevAsuhanGizi.setText("Monitoring Dan Evaluasi Gizi");
        BtnMonevAsuhanGizi.setIconTextGap(0);
        BtnMonevAsuhanGizi.setName("BtnMonevAsuhanGizi"); // NOI18N
        BtnMonevAsuhanGizi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnMonevAsuhanGizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonevAsuhanGiziActionPerformed(evt);
            }
        });
        FormInput.add(BtnMonevAsuhanGizi);

        BtnAsesmenUlangGizi.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenUlangGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenUlangGizi.setText("Asesmen Ulang Gizi");
        BtnAsesmenUlangGizi.setIconTextGap(0);
        BtnAsesmenUlangGizi.setName("BtnAsesmenUlangGizi"); // NOI18N
        BtnAsesmenUlangGizi.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenUlangGizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenUlangGiziActionPerformed(evt);
            }
        });
        FormInput.add(BtnAsesmenUlangGizi);

        scrollInput.setViewportView(FormInput);

        internalFrame2.add(scrollInput, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.CENTER);

        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setPreferredSize(new java.awt.Dimension(12, 44));
        internalFrame3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 9, 7));

        BtnRefres.setForeground(new java.awt.Color(0, 0, 0));
        BtnRefres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRefres.setMnemonic('R');
        BtnRefres.setText("Refresh Rekam Medis");
        BtnRefres.setToolTipText("Alt+R");
        BtnRefres.setName("BtnRefres"); // NOI18N
        BtnRefres.setPreferredSize(new java.awt.Dimension(186, 30));
        BtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefresActionPerformed(evt);
            }
        });
        internalFrame3.add(BtnRefres);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(90, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        internalFrame3.add(BtnKeluar);

        internalFrame1.add(internalFrame3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseIn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseIn10ActionPerformed
        WindowDPJPranap.dispose();
        kddpjp.setText("-");
        nmdpjp.setText("-");
    }//GEN-LAST:event_BtnCloseIn10ActionPerformed

    private void BtnSimpan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpan6ActionPerformed
        if (kddpjp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih dulu salah satu DPJP nya...!");
            btnDPJP.requestFocus();
        } else if (kddpjp.getText().equals("-") || kddpjp.getText().equals("--")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih dulu salah satu DPJP nya dengan benar...!");
            btnDPJP.requestFocus();
        } else {
            if (Sequel.cariInteger("select count(-1) from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                Sequel.menyimpan("dpjp_ranap", "'" + TNoRW.getText() + "','" + kddpjp.getText() + "'");
            }            

            akses.setform("DlgRMEranap");
            DlgRingkasanPulangRanap ringkasan = new DlgRingkasanPulangRanap(null, false);
            ringkasan.emptTeks();
            ringkasan.isCek();
            ringkasan.setPasien(TNoRW.getText());
            ringkasan.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            ringkasan.setLocationRelativeTo(internalFrame1);
            ringkasan.setVisible(true);

            BtnCloseIn10ActionPerformed(null);
        }
    }//GEN-LAST:event_BtnSimpan6ActionPerformed

    private void btnDPJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPJPActionPerformed
        akses.setform("DlgRMEranap");
        dokter.emptTeks();
        dokter.isCek();
        dokter.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        dokter.setLocationRelativeTo(internalFrame1);
        dokter.setVisible(true);
    }//GEN-LAST:event_btnDPJPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        isCek();
    }//GEN-LAST:event_formWindowOpened

    private void BtnAsesmenMedikDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenMedikDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenMedikDewasaRanap form = new RMAsesmenMedikDewasaRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenMedikDewasaActionPerformed

    private void BtnCPPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCPPTActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCPPT form = new DlgCPPT(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), stts, gedung);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCPPTActionPerformed

    private void BtnRingkasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRingkasanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                x = JOptionPane.showConfirmDialog(rootPane, "DPJP pasien ini belum ditentukan, apakah DPJP nya akan dipilih dulu..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    WindowDPJPranap.setSize(615, 110);
                    WindowDPJPranap.setLocationRelativeTo(internalFrame1);
                    WindowDPJPranap.setVisible(true);
                    kddpjp.setText(Sequel.cariIsi("select ifnull(kd_dokter,'') from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'"));
                    if (kddpjp.getText().equals("")) {
                        nmdpjp.setText("");
                    } else {
                        nmdpjp.setText(Sequel.cariIsi("select nm_dokter from dokter where kd_dokter='" + kddpjp.getText() + "'"));
                    }
                    btnDPJP.requestFocus();
                } else {
                    BtnKeluarActionPerformed(null);
                }
            } else {
                akses.setform("DlgRMEranap");
                DlgRingkasanPulangRanap ringkasan = new DlgRingkasanPulangRanap(null, false);
                ringkasan.emptTeks();
                ringkasan.isCek();
                ringkasan.setPasien(TNoRW.getText());
                ringkasan.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                ringkasan.setLocationRelativeTo(internalFrame1);
                ringkasan.setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnRingkasanActionPerformed

    private void BtnCTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCTKActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCatatanTindakanKeperawatan form = new DlgCatatanTindakanKeperawatan(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCTKActionPerformed

    private void BtnKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonsulActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgSuratKonsulUnit form = new DlgSuratKonsulUnit(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnKonsulActionPerformed

    private void BtnJawabKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJawabKonsulActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from surat_konsul_unit_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                JOptionPane.showMessageDialog(null, "Maaf, tidak ada surat konsul antar unit rawat inap yang akan dijawab...!!!");                
            } else {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                akses.setform("DlgRMEranap");
                DlgSuratJawabanKonsul form = new DlgSuratJawabanKonsul(null, false);
                form.emptTeks();
                form.isCek();
                form.setData(TNoRW.getText());
                form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                form.setLocationRelativeTo(internalFrame1);
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            }
        }
    }//GEN-LAST:event_BtnJawabKonsulActionPerformed

    private void BtnJadwalObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJadwalObatActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgPemberianObatPasien beriObat = new DlgPemberianObatPasien(null, false);
            beriObat.emptTeks();
            beriObat.isCek();
            beriObat.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), stts, nmUnit.getText());
            beriObat.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            beriObat.setLocationRelativeTo(internalFrame1);
            beriObat.setAlwaysOnTop(false);
            beriObat.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnJadwalObatActionPerformed

    private void BtnResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResepActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCatatanResep form = new DlgCatatanResep(null, false);
            form.isCek();
            form.setData(TNoRW.getText(), stts);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnResepActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        TNoRW.setText("");
        TNoRM.setText("");
        TNmPasien.setText("");
        nmUnit.setText("");
        stts = "";
        kdkamar = "";        
        gedung = "";
        TtglMasuk.setText("");
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnAsesmenKeperawatanDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenKeperawatanDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenKeperawatanDewasaRanap form = new RMAsesmenKeperawatanDewasaRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenKeperawatanDewasaActionPerformed

    private void BtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefresActionPerformed
        tombolCek(TNoRW.getText());
    }//GEN-LAST:event_BtnRefresActionPerformed

    private void BtnPantauHarianPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPantauHarianPasienActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMPemantauanHarian24Jam form = new RMPemantauanHarian24Jam(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPantauHarianPasienActionPerformed

    private void BtnGrafikPantauHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrafikPantauHarianActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMGrafikPemantauanHarian24Jam form = new RMGrafikPemantauanHarian24Jam(null, false);
            form.setData(TNoRW.getText());
            form.setSize(747, 71);
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnGrafikPantauHarianActionPerformed

    private void BtnProtokolKemoterapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProtokolKemoterapiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMProtokolKemoterapi form = new RMProtokolKemoterapi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), "Ranap");
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnProtokolKemoterapiActionPerformed

    private void BtnDokumenJangMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDokumenJangMedActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMDokumenPenunjangMedis form = new RMDokumenPenunjangMedis(null, false);
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnDokumenJangMedActionPerformed

    private void BtnAsesmenUlangRJDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenUlangRJDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenUlangResikoJatuhDewasa form = new RMAsesmenUlangResikoJatuhDewasa(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenUlangRJDewasaActionPerformed

    private void BtnPengelolaanTranfusiDarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengelolaanTranfusiDarahActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMPengelolaanTransfusiDarah form = new RMPengelolaanTransfusiDarah(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPengelolaanTranfusiDarahActionPerformed

    private void BtnMonitoringEWSdewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringEWSdewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMMonitoringEWSDewasa form = new RMMonitoringEWSDewasa(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnMonitoringEWSdewasaActionPerformed

    private void BtnTransferSerahTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferSerahTerimaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMTransferSerahTerimaIGD form = new RMTransferSerahTerimaIGD(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), new Date(), "ranap", kdkamar, nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnTransferSerahTerimaActionPerformed

    private void BtnAsesmenKeperawatanAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenKeperawatanAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenKeperawatanAnakRanap form = new RMAsesmenKeperawatanAnakRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenKeperawatanAnakActionPerformed

    private void BtnAsesmenMedikAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenMedikAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenMedikAnakRanap form = new RMAsesmenMedikAnakRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenMedikAnakActionPerformed

    private void BtnPersetujuanTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPersetujuanTindakanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMTindakanKedokteran form = new RMTindakanKedokteran(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), "Ranap");
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPersetujuanTindakanActionPerformed

    private void BtnAsesmenUlangRJAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenUlangRJAnakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenUlangResikoJatuhAnak form = new RMAsesmenUlangResikoJatuhAnak(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenUlangRJAnakActionPerformed

    private void BtnMonitoringPEWSanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitoringPEWSanakActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMMonitoringPEWSAnak form = new RMMonitoringPEWSAnak(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnMonitoringPEWSanakActionPerformed

    private void BtnAsesmenRestrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenRestrainActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenRestrain form = new RMAsesmenRestrain(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenRestrainActionPerformed

    private void BtnObservasiRestrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObservasiRestrainActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from asesmen_restrain where no_rawat='" + TNoRW.getText() + "'") > 0) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                akses.setform("DlgRMEranap");
                RMObservasiRestrain form = new RMObservasiRestrain(null, false);
                form.emptTeks();
                form.isCek();
                form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
                form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                form.setLocationRelativeTo(internalFrame1);
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(null, "Data asesmen restrain belum tersimpan untuk pasien ini...!!!");
            }
        }
    }//GEN-LAST:event_BtnObservasiRestrainActionPerformed

    private void BtnSkriningUlangGiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSkriningUlangGiziActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMSkriningUlangGizi form = new RMSkriningUlangGizi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnSkriningUlangGiziActionPerformed

    private void BtnMonevAsuhanGiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonevAsuhanGiziActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from asuhan_gizi_ranap where no_rawat='" + TNoRW.getText() + "'") > 0) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                akses.setform("DlgRMEranap");
                DlgMonevAsuhanGizi form = new DlgMonevAsuhanGizi(null, false);
                form.emptTeks();
                form.isCek();
                form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
                form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                form.setLocationRelativeTo(internalFrame1);
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(null, "Data asuhan gizi belum tersimpan untuk pasien ini...!!!");
            }
        }
    }//GEN-LAST:event_BtnMonevAsuhanGiziActionPerformed

    private void BtnAsuhanGiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsuhanGiziActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsuhanGiziRanap form = new RMAsuhanGiziRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), nmUnit.getText(), gedung, kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsuhanGiziActionPerformed

    private void BtnAsesmenUlangGiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenUlangGiziActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from asuhan_gizi_ranap where no_rawat='" + TNoRW.getText() + "'") > 0) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                akses.setform("DlgRMEranap");
                DlgAssesmenGiziUlang form = new DlgAssesmenGiziUlang(null, false);
                form.emptTeks();
                form.isCek();
                form.setData(TNoRW.getText(), nmUnit.getText(), gedung);
                form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                form.setLocationRelativeTo(internalFrame1);
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(null, "Data asuhan gizi belum tersimpan untuk pasien ini...!!!");
            }
        }
    }//GEN-LAST:event_BtnAsesmenUlangGiziActionPerformed

    private void BtnLembarObservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLembarObservasiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMLembarObservasi form = new RMLembarObservasi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnLembarObservasiActionPerformed

    private void BtnTransferTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferTindakanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMPasienUntukTindakan form = new RMPasienUntukTindakan(null, false);
            form.emptTeksSebelum();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnTransferTindakanActionPerformed

    private void BtnAsesmenPraSedasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenPraSedasiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenPraSedasi form = new RMAsesmenPraSedasi(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText(),
                    Sequel.cariIsi("select ifnull(status_lanjut,'') from reg_periksa where no_rawat='" + TNoRW.getText() + "'"));
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenPraSedasiActionPerformed

    private void BtnCeklisPraOperasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCeklisPraOperasiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMCeklisPraOperasi form = new RMCeklisPraOperasi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCeklisPraOperasiActionPerformed

    private void BtnCeklisKesiapanAnestesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCeklisKesiapanAnestesiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMCeklisKesiapanAnestesi form = new RMCeklisKesiapanAnestesi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText(), "ranap");
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCeklisKesiapanAnestesiActionPerformed

    private void BtnAsesmenPreInduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenPreInduksiActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenPreInduksi form = new RMAsesmenPreInduksi(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenPreInduksiActionPerformed

    private void BtnAsesmenKeperawatanPerioperatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenKeperawatanPerioperatifActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenKeperawatanPerioperatif form = new RMAsesmenKeperawatanPerioperatif(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenKeperawatanPerioperatifActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRMEranap dialog = new DlgRMEranap(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnAsesmenKeperawatanAnak;
    private widget.ButtonBig BtnAsesmenKeperawatanDewasa;
    private widget.ButtonBig BtnAsesmenKeperawatanPerioperatif;
    private widget.ButtonBig BtnAsesmenMedikAnak;
    private widget.ButtonBig BtnAsesmenMedikDewasa;
    private widget.ButtonBig BtnAsesmenPraSedasi;
    private widget.ButtonBig BtnAsesmenPreInduksi;
    private widget.ButtonBig BtnAsesmenRestrain;
    private widget.ButtonBig BtnAsesmenUlangGizi;
    private widget.ButtonBig BtnAsesmenUlangRJAnak;
    private widget.ButtonBig BtnAsesmenUlangRJDewasa;
    private widget.ButtonBig BtnAsuhanGizi;
    private widget.ButtonBig BtnCPPT;
    private widget.ButtonBig BtnCTK;
    private widget.ButtonBig BtnCeklisKesiapanAnestesi;
    private widget.ButtonBig BtnCeklisPraOperasi;
    private widget.Button BtnCloseIn10;
    private widget.ButtonBig BtnDokumenJangMed;
    private widget.ButtonBig BtnGrafikPantauHarian;
    private widget.ButtonBig BtnJadwalObat;
    private widget.ButtonBig BtnJawabKonsul;
    private widget.Button BtnKeluar;
    private widget.ButtonBig BtnKonsul;
    private widget.ButtonBig BtnLembarObservasi;
    private widget.ButtonBig BtnMonevAsuhanGizi;
    private widget.ButtonBig BtnMonitoringEWSdewasa;
    private widget.ButtonBig BtnMonitoringPEWSanak;
    private widget.ButtonBig BtnObservasiRestrain;
    private widget.ButtonBig BtnPantauHarianPasien;
    private widget.ButtonBig BtnPengelolaanTranfusiDarah;
    private widget.ButtonBig BtnPersetujuanTindakan;
    private widget.ButtonBig BtnProtokolKemoterapi;
    private widget.Button BtnRefres;
    private widget.ButtonBig BtnResep;
    private widget.ButtonBig BtnRingkasan;
    private widget.Button BtnSimpan6;
    private widget.ButtonBig BtnSkriningUlangGizi;
    private widget.ButtonBig BtnTransferSerahTerima;
    private widget.ButtonBig BtnTransferTindakan;
    private widget.PanelBiasa FormInput;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private widget.TextBox TtglMasuk;
    private javax.swing.JDialog WindowDPJPranap;
    private widget.Button btnDPJP;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel52;
    private widget.TextBox kddpjp;
    private widget.TextBox nmUnit;
    private widget.TextBox nmdpjp;
    private widget.ScrollPane scrollInput;
    // End of variables declaration//GEN-END:variables

    private void isCek() {
        BtnAsesmenMedikDewasa.setEnabled(akses.getasesmen_medik_dewasa_ranap());
        BtnAsesmenMedikAnak.setEnabled(akses.getasesmen_medik_anak_ranap());
        BtnAsesmenKeperawatanDewasa.setEnabled(akses.getcppt());
        BtnAsesmenKeperawatanAnak.setEnabled(akses.getcppt());
        BtnAsesmenRestrain.setEnabled(akses.getcppt());
        BtnObservasiRestrain.setEnabled(akses.getcppt());
        BtnCPPT.setEnabled(akses.getcppt());
        BtnResep.setEnabled(akses.getresep_dokter());
        BtnRingkasan.setEnabled(akses.getringkasanpulangranap());
        BtnCTK.setEnabled(akses.getcppt());
        BtnAsesmenUlangRJDewasa.setEnabled(akses.getcppt());
        BtnAsesmenUlangRJAnak.setEnabled(akses.getcppt());
        BtnJadwalObat.setEnabled(akses.getpemberian_obat());        
        BtnKonsul.setEnabled(akses.getpermintaan_lab());
        BtnJawabKonsul.setEnabled(akses.getpermintaan_lab());
        BtnPantauHarianPasien.setEnabled(akses.getcppt());
        BtnGrafikPantauHarian.setEnabled(akses.getcppt());
        BtnProtokolKemoterapi.setEnabled(akses.getkemoterapi());        
        BtnPengelolaanTranfusiDarah.setEnabled(akses.getcppt());
        BtnMonitoringEWSdewasa.setEnabled(akses.getcppt());
        BtnMonitoringPEWSanak.setEnabled(akses.getcppt());
        BtnTransferSerahTerima.setEnabled(akses.getpemberian_obat());
        BtnPersetujuanTindakan.setEnabled(akses.getpemberian_obat());
        BtnSkriningUlangGizi.setEnabled(akses.getassesmen_gizi_harian());
        BtnMonevAsuhanGizi.setEnabled(akses.getmonev_asuhan_gizi());
        BtnAsuhanGizi.setEnabled(akses.getassesmen_gizi_harian());
        BtnAsesmenUlangGizi.setEnabled(akses.getassesmen_gizi_ulang());
        BtnLembarObservasi.setEnabled(akses.getcppt());
        BtnTransferTindakan.setEnabled(akses.getcppt());
        BtnAsesmenPraSedasi.setEnabled(akses.getresep_dokter());
        BtnCeklisPraOperasi.setEnabled(akses.getkegiatan_operasi());
        BtnCeklisKesiapanAnestesi.setEnabled(akses.getkegiatan_operasi());
        BtnAsesmenPreInduksi.setEnabled(akses.getresep_dokter());
        BtnAsesmenKeperawatanPerioperatif.setEnabled(akses.getkegiatan_operasi());
    }
    
    public void setData(String norw, String norm, String nmpasien,
            String status, String kdkmr, String rgrawat, String nmgedung,
            String tglmsk) {
        
        TNoRW.setText(norw);
        TNoRM.setText(norm);
        TNmPasien.setText(nmpasien);
        nmUnit.setText(rgrawat);
        stts = status;
        kdkamar = kdkmr;        
        gedung = nmgedung;
        TtglMasuk.setText(tglmsk);
        tombolCek(norw);
    }

    private void tombolCek(String norawat) {
        if (Sequel.cariInteger("select count(-1) from asesmen_medik_dewasa_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenMedikDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenMedikDewasa.setToolTipText("Asesmen Medik Dewasa BELUM diisi oleh dokter..!!!");
        } else {
            BtnAsesmenMedikDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenMedikDewasa.setToolTipText("Asesmen Medik Dewasa SUDAH diisi oleh dokter..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_dewasa_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenKeperawatanDewasa.setToolTipText("Asesmen Keperawatan Dewasa BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenKeperawatanDewasa.setToolTipText("Asesmen Keperawatan Dewasa SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from cppt where no_rawat='" + norawat + "' and tgl_cppt=date(now()) and flag_hapus='tidak'") == 0) {
            BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnCPPT.setToolTipText("CPPT untuk tanggal hari ini BELUM diisi oleh petugas..!!!");
        } else {
            BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnCPPT.setToolTipText("CPPT untuk tanggal hari ini SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from catatan_resep_ranap where no_rawat='" + norawat + "' and tgl_perawatan=date(now())") == 0) {
            BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726_merah.png")));
            BtnResep.setToolTipText("Pada hari ini pasien tersebut BELUM diberi resep oleh dokter..!!!");
        } else {
            BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726.png")));
            BtnResep.setToolTipText("Pada hari ini pasien tersebut SUDAH diberi resep oleh dokter..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from ringkasan_pulang_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnRingkasan.setToolTipText("Ringkasan pulang rawat inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnRingkasan.setToolTipText("Ringkasan pulang rawat inap SUDAH diisi oleh dokter DPJP..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from catatan_tindakan_keperawatan where no_rawat='" + norawat + "' and tanggal=date(now())") == 0) {
            BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnCTK.setToolTipText("Catatan Tindakan Keperawatan pasien tersebut pada hari ini BELUM diisi oleh petugas..!!!");
        } else {
            BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnCTK.setToolTipText("Catatan Tindakan Keperawatan pasien tersebut pada hari ini SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from pemberian_obat where no_rawat='" + norawat + "' and tgl_pemberian=date(now())") == 0) {
            BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel_merah.png")));
            BtnJadwalObat.setToolTipText("Jadwal pemberian obat pasien tersebut pada hari ini BELUM dibikinkan oleh petugas..!!!");
        } else {
            BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel.png")));
            BtnJadwalObat.setToolTipText("Jadwal pemberian obat pasien tersebut pada hari ini SUDAH dibikinkan oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from pemantauan_harian_24jam where no_rawat='" + norawat + "' and tgl_pantau=date(now())") == 0) {
            BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20_biru.png")));
            BtnPantauHarianPasien.setToolTipText("Data pemantauan harian pasien pada hari ini BELUM dibikinkan oleh petugas..!!!");
            BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20_biru.png")));
            BtnGrafikPantauHarian.setToolTipText("Grafik hasil pemantauan harian pasien pada hari ini BELUM dibikinkan oleh petugas..!!!");
        } else {
            BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png")));
            BtnPantauHarianPasien.setToolTipText("Data pemantauan harian pasien pada hari ini SUDAH dibikinkan oleh petugas..!!!");
            BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png")));
            BtnGrafikPantauHarian.setToolTipText("Grafik hasil pemantauan harian pasien pada hari ini SUDAH dibikinkan oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from asesmen_ulang_resiko_jatuh where no_rawat='" + norawat + "' and tgl_asesmen=date(now())") == 0) {
            BtnAsesmenUlangRJDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenUlangRJDewasa.setToolTipText("Asesmen Ulang Resiko Jatuh Dewasa BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenUlangRJDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenUlangRJDewasa.setToolTipText("Asesmen Ulang Resiko Jatuh Dewasa SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from pengelolaan_transfusi_darah where no_rawat='" + norawat + "' and tanggal=date(now())") == 0) {
            BtnPengelolaanTranfusiDarah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481001585_blood_drop.png")));
            BtnPengelolaanTranfusiDarah.setToolTipText("Pengelolaan Pasien Transfusi Darah BELUM diisi oleh petugas..!!!");
        } else {
            BtnPengelolaanTranfusiDarah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1481001585_blood_drop_biru.png")));
            BtnPengelolaanTranfusiDarah.setToolTipText("Pengelolaan Pasien Transfusi Darah SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from monitoring_ews_dewasa where no_rawat='" + norawat + "' and tanggal=date(now())") == 0) {
            BtnMonitoringEWSdewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnMonitoringEWSdewasa.setToolTipText("Monitoring EWS Dewasa BELUM diisi oleh petugas..!!!");
        } else {
            BtnMonitoringEWSdewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940_biru.png")));
            BtnMonitoringEWSdewasa.setToolTipText("Monitoring EWS Dewasa SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from transfer_serah_terima_pasien_igd where no_rawat='" + norawat + "' and kd_kamar_msk<>'IGDK'") == 0) {
            BtnTransferSerahTerima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnTransferSerahTerima.setToolTipText("Data Transfer & Serah Terima Pasien BELUM diisi oleh petugas..!!!");
        } else {
            BtnTransferSerahTerima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnTransferSerahTerima.setToolTipText("Data Transfer & Serah Terima Pasien SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_anak_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenKeperawatanAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenKeperawatanAnak.setToolTipText("Asesmen Keperawatan Anak BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenKeperawatanAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenKeperawatanAnak.setToolTipText("Asesmen Keperawatan Anak SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from asesmen_medik_anak_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenMedikAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenMedikAnak.setToolTipText("Asesmen Medik Anak BELUM diisi oleh dokter..!!!");
        } else {
            BtnAsesmenMedikAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenMedikAnak.setToolTipText("Asesmen Medik Anak SUDAH diisi oleh dokter..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from asesmen_ulang_resiko_jatuh_anak where no_rawat='" + norawat + "' and tgl_asesmen=date(now())") == 0) {
            BtnAsesmenUlangRJAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenUlangRJAnak.setToolTipText("Asesmen Ulang Resiko Jatuh Anak BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenUlangRJAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenUlangRJAnak.setToolTipText("Asesmen Ulang Resiko Jatuh Anak SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from monitoring_pews_anak where no_rawat='" + norawat + "' and tanggal=date(now())") == 0) {
            BtnMonitoringPEWSanak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940.png")));
            BtnMonitoringPEWSanak.setToolTipText("Monitoring Pediatric EWS BELUM diisi oleh petugas..!!!");
        } else {
            BtnMonitoringPEWSanak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_dialog-warning_118940_biru.png")));
            BtnMonitoringPEWSanak.setToolTipText("Monitoring Pediatric EWS SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from asesmen_restrain where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenRestrain.setToolTipText("Asesmen Restrain BELUM diisi oleh perawat/bidan..!!!");
        } else {
            BtnAsesmenRestrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenRestrain.setToolTipText("Asesmen Restrain SUDAH diisi oleh perawat/bidan..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from asuhan_gizi_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsuhanGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsuhanGizi.setToolTipText("Asuhan Gizi Pasien BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsuhanGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsuhanGizi.setToolTipText("Asuhan Gizi Pasien SUDAH diisi oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from assesmen_gizi_ulang where no_rawat='" + norawat + "' and tgl_assesmen=date(now())") == 0) {
            BtnAsesmenUlangGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenUlangGizi.setToolTipText("Asesmen Ulang Gizi Pasien BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenUlangGizi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenUlangGizi.setToolTipText("Asesmen Ulang Gizi Pasien SUDAH diisi oleh petugas..!!!");
        }
    }
}
