package rekammedis;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import inventory.DlgCatatanResep;
import inventory.DlgPemberianObatPasien;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import permintaan.DlgSuratJawabanKonsul;
import permintaan.DlgSuratKonsulUnit;
import simrskhanza.DlgCariDokter;
import simrskhanza.DlgRingkasanPulangRanap;

/**
 *
 * @author dosen
 */
public class DlgRMEranap extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private int i = 0, x = 0;
    private DlgCariDokter dokter = new DlgCariDokter(null, false);
    private String stts = "", kdkamar = "", gedung = "";
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgRMEranap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        dokter.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {;
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (akses.getform().equals("DlgRMEranap")) {
                    if (dokter.getTable().getSelectedRow() != -1) {
                        kddpjp.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(), 0).toString());
                        nmdpjp.setText(dokter.getTable().getValueAt(dokter.getTable().getSelectedRow(), 1).toString());
                        btnDPJP.requestFocus();                        
                    }
                }
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowDPJPranap = new javax.swing.JDialog();
        internalFrame15 = new widget.InternalFrame();
        BtnCloseIn10 = new widget.Button();
        BtnSimpan6 = new widget.Button();
        jLabel52 = new widget.Label();
        kddpjp = new widget.TextBox();
        nmdpjp = new widget.TextBox();
        btnDPJP = new widget.Button();
        internalFrame1 = new widget.InternalFrame();
        internalFrame4 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        nmUnit = new widget.TextBox();
        jLabel4 = new widget.Label();
        TtglMasuk = new widget.TextBox();
        internalFrame2 = new widget.InternalFrame();
        BtnAsesmenMedik = new widget.ButtonBig();
        BtnAsesmenKeperawatanDewasa = new widget.ButtonBig();
        BtnCPPT = new widget.ButtonBig();
        BtnResep = new widget.ButtonBig();
        BtnRingkasan = new widget.ButtonBig();
        BtnCTK = new widget.ButtonBig();
        BtnJadwalObat = new widget.ButtonBig();
        BtnKonsul = new widget.ButtonBig();
        BtnJawabKonsul = new widget.ButtonBig();
        BtnPantauHarianPasien = new widget.ButtonBig();
        BtnGrafikPantauHarian = new widget.ButtonBig();
        internalFrame3 = new widget.InternalFrame();
        BtnRefres = new widget.Button();
        BtnKeluar = new widget.Button();

        WindowDPJPranap.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowDPJPranap.setName("WindowDPJPranap"); // NOI18N
        WindowDPJPranap.setUndecorated(true);
        WindowDPJPranap.setResizable(false);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ DPJP Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame15.setLayout(null);

        BtnCloseIn10.setForeground(new java.awt.Color(0, 0, 0));
        BtnCloseIn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnCloseIn10.setMnemonic('U');
        BtnCloseIn10.setText("Tutup");
        BtnCloseIn10.setToolTipText("Alt+U");
        BtnCloseIn10.setName("BtnCloseIn10"); // NOI18N
        BtnCloseIn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseIn10ActionPerformed(evt);
            }
        });
        internalFrame15.add(BtnCloseIn10);
        BtnCloseIn10.setBounds(480, 60, 100, 30);

        BtnSimpan6.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan6.setMnemonic('S');
        BtnSimpan6.setText("Simpan");
        BtnSimpan6.setToolTipText("Alt+S");
        BtnSimpan6.setName("BtnSimpan6"); // NOI18N
        BtnSimpan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpan6ActionPerformed(evt);
            }
        });
        internalFrame15.add(BtnSimpan6);
        BtnSimpan6.setBounds(370, 60, 100, 30);

        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Nama DPJP :");
        jLabel52.setName("jLabel52"); // NOI18N
        internalFrame15.add(jLabel52);
        jLabel52.setBounds(0, 32, 77, 23);

        kddpjp.setEditable(false);
        kddpjp.setForeground(new java.awt.Color(0, 0, 0));
        kddpjp.setName("kddpjp"); // NOI18N
        internalFrame15.add(kddpjp);
        kddpjp.setBounds(81, 32, 100, 23);

        nmdpjp.setEditable(false);
        nmdpjp.setForeground(new java.awt.Color(0, 0, 0));
        nmdpjp.setName("nmdpjp"); // NOI18N
        internalFrame15.add(nmdpjp);
        nmdpjp.setBounds(183, 32, 380, 23);

        btnDPJP.setForeground(new java.awt.Color(0, 0, 0));
        btnDPJP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnDPJP.setMnemonic('7');
        btnDPJP.setToolTipText("ALt+7");
        btnDPJP.setName("btnDPJP"); // NOI18N
        btnDPJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPJPActionPerformed(evt);
            }
        });
        internalFrame15.add(btnDPJP);
        btnDPJP.setBounds(565, 32, 28, 23);

        WindowDPJPranap.getContentPane().add(internalFrame15, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Rekam Medis Elektronik ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(12, 100));
        internalFrame4.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pasien :");
        jLabel3.setName("jLabel3"); // NOI18N
        internalFrame4.add(jLabel3);
        jLabel3.setBounds(0, 10, 103, 23);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        internalFrame4.add(TNoRW);
        TNoRW.setBounds(107, 10, 122, 23);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        internalFrame4.add(TNoRM);
        TNoRM.setBounds(233, 10, 70, 23);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        internalFrame4.add(TNmPasien);
        TNmPasien.setBounds(308, 10, 291, 23);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rg. Rawat :");
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame4.add(jLabel13);
        jLabel13.setBounds(0, 38, 103, 23);

        nmUnit.setEditable(false);
        nmUnit.setForeground(new java.awt.Color(0, 0, 0));
        nmUnit.setName("nmUnit"); // NOI18N
        internalFrame4.add(nmUnit);
        nmUnit.setBounds(107, 38, 492, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tgl. Masuk :");
        jLabel4.setName("jLabel4"); // NOI18N
        internalFrame4.add(jLabel4);
        jLabel4.setBounds(0, 66, 103, 23);

        TtglMasuk.setEditable(false);
        TtglMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TtglMasuk.setName("TtglMasuk"); // NOI18N
        internalFrame4.add(TtglMasuk);
        TtglMasuk.setBounds(107, 66, 210, 23);

        internalFrame1.add(internalFrame4, java.awt.BorderLayout.PAGE_START);

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(2800, 2800));
        internalFrame2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnAsesmenMedik.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenMedik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenMedik.setText("Asesmen Medik Dewasa");
        BtnAsesmenMedik.setToolTipText("");
        BtnAsesmenMedik.setIconTextGap(0);
        BtnAsesmenMedik.setName("BtnAsesmenMedik"); // NOI18N
        BtnAsesmenMedik.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenMedik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenMedikActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnAsesmenMedik);

        BtnAsesmenKeperawatanDewasa.setForeground(new java.awt.Color(0, 0, 0));
        BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnAsesmenKeperawatanDewasa.setText("Asesmen Keperawatan Dewasa");
        BtnAsesmenKeperawatanDewasa.setIconTextGap(0);
        BtnAsesmenKeperawatanDewasa.setName("BtnAsesmenKeperawatanDewasa"); // NOI18N
        BtnAsesmenKeperawatanDewasa.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnAsesmenKeperawatanDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsesmenKeperawatanDewasaActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnAsesmenKeperawatanDewasa);

        BtnCPPT.setForeground(new java.awt.Color(0, 0, 0));
        BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnCPPT.setText("CPPT");
        BtnCPPT.setIconTextGap(0);
        BtnCPPT.setName("BtnCPPT"); // NOI18N
        BtnCPPT.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCPPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCPPTActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnCPPT);

        BtnResep.setForeground(new java.awt.Color(0, 0, 0));
        BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726.png"))); // NOI18N
        BtnResep.setText("Resep Obat");
        BtnResep.setIconTextGap(0);
        BtnResep.setName("BtnResep"); // NOI18N
        BtnResep.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResepActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnResep);

        BtnRingkasan.setForeground(new java.awt.Color(0, 0, 0));
        BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnRingkasan.setText("Ringkasan Pulang / Resume");
        BtnRingkasan.setIconTextGap(0);
        BtnRingkasan.setName("BtnRingkasan"); // NOI18N
        BtnRingkasan.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnRingkasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRingkasanActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnRingkasan);

        BtnCTK.setForeground(new java.awt.Color(0, 0, 0));
        BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png"))); // NOI18N
        BtnCTK.setText("Catatan Tindakan Keperawatan");
        BtnCTK.setIconTextGap(0);
        BtnCTK.setName("BtnCTK"); // NOI18N
        BtnCTK.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCTKActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnCTK);

        BtnJadwalObat.setForeground(new java.awt.Color(0, 0, 0));
        BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel.png"))); // NOI18N
        BtnJadwalObat.setText("Jadwal Beri Obat Oral/Injeksi");
        BtnJadwalObat.setIconTextGap(0);
        BtnJadwalObat.setName("BtnJadwalObat"); // NOI18N
        BtnJadwalObat.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnJadwalObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJadwalObatActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnJadwalObat);

        BtnKonsul.setForeground(new java.awt.Color(0, 0, 0));
        BtnKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/email_open.png"))); // NOI18N
        BtnKonsul.setText("Permintaan Konsul Antar Unit");
        BtnKonsul.setIconTextGap(0);
        BtnKonsul.setName("BtnKonsul"); // NOI18N
        BtnKonsul.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonsulActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnKonsul);

        BtnJawabKonsul.setForeground(new java.awt.Color(0, 0, 0));
        BtnJawabKonsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kwrite.png"))); // NOI18N
        BtnJawabKonsul.setText("Jawaban Konsul Antar Unit");
        BtnJawabKonsul.setIconTextGap(0);
        BtnJawabKonsul.setName("BtnJawabKonsul"); // NOI18N
        BtnJawabKonsul.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnJawabKonsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJawabKonsulActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnJawabKonsul);

        BtnPantauHarianPasien.setForeground(new java.awt.Color(0, 0, 0));
        BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png"))); // NOI18N
        BtnPantauHarianPasien.setText("Pemantauan Harian Pasien");
        BtnPantauHarianPasien.setIconTextGap(0);
        BtnPantauHarianPasien.setName("BtnPantauHarianPasien"); // NOI18N
        BtnPantauHarianPasien.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnPantauHarianPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPantauHarianPasienActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnPantauHarianPasien);

        BtnGrafikPantauHarian.setForeground(new java.awt.Color(0, 0, 0));
        BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png"))); // NOI18N
        BtnGrafikPantauHarian.setText("Grafik Pemantauan Harian Pasien");
        BtnGrafikPantauHarian.setIconTextGap(0);
        BtnGrafikPantauHarian.setName("BtnGrafikPantauHarian"); // NOI18N
        BtnGrafikPantauHarian.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnGrafikPantauHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrafikPantauHarianActionPerformed(evt);
            }
        });
        internalFrame2.add(BtnGrafikPantauHarian);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.CENTER);

        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setPreferredSize(new java.awt.Dimension(12, 44));
        internalFrame3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 9, 7));

        BtnRefres.setForeground(new java.awt.Color(0, 0, 0));
        BtnRefres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRefres.setMnemonic('R');
        BtnRefres.setText("Refresh Rekam Medis");
        BtnRefres.setToolTipText("Alt+R");
        BtnRefres.setName("BtnRefres"); // NOI18N
        BtnRefres.setPreferredSize(new java.awt.Dimension(186, 30));
        BtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefresActionPerformed(evt);
            }
        });
        internalFrame3.add(BtnRefres);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(90, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        internalFrame3.add(BtnKeluar);

        internalFrame1.add(internalFrame3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseIn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseIn10ActionPerformed
        WindowDPJPranap.dispose();
        kddpjp.setText("");
        nmdpjp.setText("");
    }//GEN-LAST:event_BtnCloseIn10ActionPerformed

    private void BtnSimpan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpan6ActionPerformed
        if (kddpjp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih dulu salah satu DPJP nya...!");
            btnDPJP.requestFocus();
        } else {
            if (Sequel.cariInteger("select count(-1) from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                Sequel.menyimpan("dpjp_ranap", "'" + TNoRW.getText() + "','" + kddpjp.getText() + "'");
            }            

            akses.setform("DlgRMEranap");
            DlgRingkasanPulangRanap ringkasan = new DlgRingkasanPulangRanap(null, false);
            ringkasan.emptTeks();
            ringkasan.isCek();
            ringkasan.setPasien(TNoRW.getText());
            ringkasan.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            ringkasan.setLocationRelativeTo(internalFrame1);
            ringkasan.setVisible(true);

            BtnCloseIn10ActionPerformed(null);
        }
    }//GEN-LAST:event_BtnSimpan6ActionPerformed

    private void btnDPJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPJPActionPerformed
        akses.setform("DlgRMEranap");
        dokter.emptTeks();
        dokter.isCek();
        dokter.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
        dokter.setLocationRelativeTo(internalFrame1);
        dokter.setVisible(true);
    }//GEN-LAST:event_btnDPJPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        isCek();
    }//GEN-LAST:event_formWindowOpened

    private void BtnAsesmenMedikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenMedikActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenMedikDewasaRanap form = new RMAsesmenMedikDewasaRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setNoRm(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenMedikActionPerformed

    private void BtnCPPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCPPTActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCPPT form = new DlgCPPT(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), stts);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCPPTActionPerformed

    private void BtnRingkasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRingkasanActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                x = JOptionPane.showConfirmDialog(rootPane, "DPJP pasien ini belum ditentukan, apakah DPJP nya akan dipilih dulu..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    WindowDPJPranap.setSize(615, 110);
                    WindowDPJPranap.setLocationRelativeTo(internalFrame1);
                    WindowDPJPranap.setVisible(true);
                    kddpjp.setText(Sequel.cariIsi("select ifnull(kd_dokter,'') from dpjp_ranap where no_rawat='" + TNoRW.getText() + "'"));
                    if (kddpjp.getText().equals("")) {
                        nmdpjp.setText("");
                    } else {
                        nmdpjp.setText(Sequel.cariIsi("select nm_dokter from dokter where kd_dokter='" + kddpjp.getText() + "'"));
                    }
                    btnDPJP.requestFocus();
                } else {
                    BtnKeluarActionPerformed(null);
                }
            } else {
                akses.setform("DlgRMEranap");
                DlgRingkasanPulangRanap ringkasan = new DlgRingkasanPulangRanap(null, false);
                ringkasan.emptTeks();
                ringkasan.isCek();
                ringkasan.setPasien(TNoRW.getText());
                ringkasan.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                ringkasan.setLocationRelativeTo(internalFrame1);
                ringkasan.setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnRingkasanActionPerformed

    private void BtnCTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCTKActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCatatanTindakanKeperawatan form = new DlgCatatanTindakanKeperawatan(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCTKActionPerformed

    private void BtnKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonsulActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgSuratKonsulUnit form = new DlgSuratKonsulUnit(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnKonsulActionPerformed

    private void BtnJawabKonsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJawabKonsulActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            if (Sequel.cariInteger("select count(-1) from surat_konsul_unit_ranap where no_rawat='" + TNoRW.getText() + "'") == 0) {
                JOptionPane.showMessageDialog(null, "Maaf, tidak ada surat konsul antar unit rawat inap yang akan dijawab...!!!");                
            } else {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                akses.setform("DlgRMEranap");
                DlgSuratJawabanKonsul form = new DlgSuratJawabanKonsul(null, false);
                form.emptTeks();
                form.isCek();
                form.setData(TNoRW.getText());
                form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
                form.setLocationRelativeTo(internalFrame1);
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            }
        }
    }//GEN-LAST:event_BtnJawabKonsulActionPerformed

    private void BtnJadwalObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJadwalObatActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgPemberianObatPasien beriObat = new DlgPemberianObatPasien(null, false);
            beriObat.emptTeks();
            beriObat.isCek();
            beriObat.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), stts, nmUnit.getText());
            beriObat.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            beriObat.setLocationRelativeTo(internalFrame1);
            beriObat.setAlwaysOnTop(false);
            beriObat.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnJadwalObatActionPerformed

    private void BtnResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResepActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            DlgCatatanResep form = new DlgCatatanResep(null, false);
            form.isCek();
            form.setData(TNoRW.getText(), stts);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnResepActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        TNoRW.setText("");
        TNoRM.setText("");
        TNmPasien.setText("");
        nmUnit.setText("");
        stts = "";
        kdkamar = "";        
        gedung = "";
        TtglMasuk.setText("");
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnAsesmenKeperawatanDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsesmenKeperawatanDewasaActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMAsesmenKeperawatanDewasaRanap form = new RMAsesmenKeperawatanDewasaRanap(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), kdkamar);
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnAsesmenKeperawatanDewasaActionPerformed

    private void BtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefresActionPerformed
        tombolCek(TNoRW.getText());
    }//GEN-LAST:event_BtnRefresActionPerformed

    private void BtnPantauHarianPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPantauHarianPasienActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMPemantauanHarian24Jam form = new RMPemantauanHarian24Jam(null, false);
            form.emptTeks();
            form.isCek();
            form.setData(TNoRW.getText(), nmUnit.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPantauHarianPasienActionPerformed

    private void BtnGrafikPantauHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrafikPantauHarianActionPerformed
        if (TNoRW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Silahkan anda pilih dulu salah satu datanya pada tabel...!!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            akses.setform("DlgRMEranap");
            RMGrafikPemantauanHarian24Jam form = new RMGrafikPemantauanHarian24Jam(null, false);
            form.setData(TNoRW.getText(), TNoRM.getText(), TNmPasien.getText(), nmUnit.getText(), TtglMasuk.getText());
            form.setSize(internalFrame1.getWidth(), internalFrame1.getHeight());
            form.setLocationRelativeTo(internalFrame1);
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnGrafikPantauHarianActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRMEranap dialog = new DlgRMEranap(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonBig BtnAsesmenKeperawatanDewasa;
    private widget.ButtonBig BtnAsesmenMedik;
    private widget.ButtonBig BtnCPPT;
    private widget.ButtonBig BtnCTK;
    private widget.Button BtnCloseIn10;
    private widget.ButtonBig BtnGrafikPantauHarian;
    private widget.ButtonBig BtnJadwalObat;
    private widget.ButtonBig BtnJawabKonsul;
    private widget.Button BtnKeluar;
    private widget.ButtonBig BtnKonsul;
    private widget.ButtonBig BtnPantauHarianPasien;
    private widget.Button BtnRefres;
    private widget.ButtonBig BtnResep;
    private widget.ButtonBig BtnRingkasan;
    private widget.Button BtnSimpan6;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private widget.TextBox TtglMasuk;
    private javax.swing.JDialog WindowDPJPranap;
    private widget.Button btnDPJP;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.Label jLabel13;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel52;
    private widget.TextBox kddpjp;
    private widget.TextBox nmUnit;
    private widget.TextBox nmdpjp;
    // End of variables declaration//GEN-END:variables

    private void isCek() {
        BtnCPPT.setEnabled(akses.getcppt());
        BtnJadwalObat.setEnabled(akses.getpemberian_obat());
        BtnAsesmenMedik.setEnabled(akses.getasesmen_medik_dewasa_ranap());
        BtnCTK.setEnabled(akses.getcppt());
        BtnResep.setEnabled(akses.getresep_dokter());
        BtnKonsul.setEnabled(akses.getpermintaan_lab());
        BtnJawabKonsul.setEnabled(akses.getpermintaan_lab());
    }
    
    public void setData(String norw, String norm, String nmpasien,
            String status, String kdkmr, String rgrawat, String nmgedung,
            String tglmsk) {
        
        TNoRW.setText(norw);
        TNoRM.setText(norm);
        TNmPasien.setText(nmpasien);
        nmUnit.setText(rgrawat);
        stts = status;
        kdkamar = kdkmr;        
        gedung = nmgedung;
        TtglMasuk.setText(tglmsk);
        tombolCek(norw);
    }

    private void tombolCek(String norawat) {
        if (Sequel.cariInteger("select count(-1) from asesmen_medik_dewasa_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenMedik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenMedik.setToolTipText("Asesmen Medik Dewasa BELUM diisi oleh dokter..!!!");
        } else {
            BtnAsesmenMedik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenMedik.setToolTipText("Asesmen Medik Dewasa SUDAH diisi oleh dokter..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from penilaian_awal_keperawatan_dewasa_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnAsesmenKeperawatanDewasa.setToolTipText("Asesmen Keperawatan Dewasa BELUM diisi oleh petugas..!!!");
        } else {
            BtnAsesmenKeperawatanDewasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnAsesmenKeperawatanDewasa.setToolTipText("Asesmen Keperawatan Dewasa SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from cppt where no_rawat='" + norawat + "' and tgl_cppt=date(now()) and flag_hapus='tidak'") == 0) {
            BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnCPPT.setToolTipText("CPPT untuk tanggal hari ini BELUM diisi oleh petugas..!!!");
        } else {
            BtnCPPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnCPPT.setToolTipText("CPPT untuk tanggal hari ini SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from catatan_resep_ranap where no_rawat='" + norawat + "' and tgl_perawatan=date(now())") == 0) {
            BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726_merah.png")));
            BtnResep.setToolTipText("Pada hari ini pasien tersebut BELUM diberi resep oleh dokter..!!!");
        } else {
            BtnResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_basket_8726.png")));
            BtnResep.setToolTipText("Pada hari ini pasien tersebut SUDAH diberi resep oleh dokter..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from ringkasan_pulang_ranap where no_rawat='" + norawat + "'") == 0) {
            BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnRingkasan.setToolTipText("Ringkasan pulang rawat inap BELUM diisi oleh dokter DPJP..!!!");
        } else {
            BtnRingkasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnRingkasan.setToolTipText("Ringkasan pulang rawat inap SUDAH diisi oleh dokter DPJP..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from catatan_tindakan_keperawatan where no_rawat='" + norawat + "' and tanggal=date(now())") == 0) {
            BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record_merah.png")));
            BtnCTK.setToolTipText("Catatan Tindakan Keperawatan pasien tersebut pada hari ini BELUM diisi oleh petugas..!!!");
        } else {
            BtnCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/medical_record.png")));
            BtnCTK.setToolTipText("Catatan Tindakan Keperawatan pasien tersebut pada hari ini SUDAH diisi oleh petugas..!!!");
        }

        if (Sequel.cariInteger("select count(-1) from pemberian_obat where no_rawat='" + norawat + "' and tgl_pemberian=date(now())") == 0) {
            BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel_merah.png")));
            BtnJadwalObat.setToolTipText("Jadwal pemberian obat pasien tersebut pada hari ini BELUM dibikinkan oleh petugas..!!!");
        } else {
            BtnJadwalObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1404047834_application-vnd.ms-excel.png")));
            BtnJadwalObat.setToolTipText("Jadwal pemberian obat pasien tersebut pada hari ini SUDAH dibikinkan oleh petugas..!!!");
        }
        
        if (Sequel.cariInteger("select count(-1) from pemantauan_harian_24jam where no_rawat='" + norawat + "' and tgl_pantau=date(now())") == 0) {
            BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20_biru.png")));
            BtnPantauHarianPasien.setToolTipText("Data pemantauan harian pasien pada hari ini BELUM dibikinkan oleh petugas..!!!");
            BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20_biru.png")));
            BtnGrafikPantauHarian.setToolTipText("Grafik hasil pemantauan harian pasien pada hari ini BELUM dibikinkan oleh petugas..!!!");
        } else {
            BtnPantauHarianPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png")));
            BtnPantauHarianPasien.setToolTipText("Data pemantauan harian pasien pada hari ini SUDAH dibikinkan oleh petugas..!!!");
            BtnGrafikPantauHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360486822_20.png")));
            BtnGrafikPantauHarian.setToolTipText("Grafik hasil pemantauan harian pasien pada hari ini SUDAH dibikinkan oleh petugas..!!!");
        }
    }
}
