    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgSpesialis.java
 *
 * Created on May 23, 2010, 1:25:13 AM
 */

package rekammedis;
import static com.sun.org.glassfish.external.amx.AMXUtil.prop;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import static javafx.concurrent.Worker.State.FAILED;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.PopupFeatures;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.HyperlinkEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author dosen
 */
public class RMDokumenPenunjangMedis extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();    
    private ResultSet rs;
    private String link = "";
    private int urut = 0;
    
    /** Creates new form DlgSpesialis
     * @param parent
     * @param modal */
    public RMDokumenPenunjangMedis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            link = koneksiDB.HOSTport();
        } catch (Exception e) {
            System.out.println("E : " + e);
        }
        
        LoadHTML1.setEditable(true);
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML1.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(".isi td{border-right: 1px solid #edf2e8;font: 10px tahoma;height:12px;border-bottom: 1px solid #edf2e8;background: 0000000;color:0000000;}");
        Document doc = kit.createDefaultDocument();
        LoadHTML1.setDocument(doc);
        LoadHTML1.setEditable(false);
        
        LoadHTML1.addHyperlinkListener(e -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.browse(e.getURL().toURI());
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnJenisDokumen = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        panelGlass7 = new widget.panelisi();
        jLabel3 = new widget.Label();
        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TNmPasien = new widget.TextBox();
        PanelContent = new widget.panelisi();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();
        panelGlass8 = new widget.panelisi();
        ChkDokumen = new widget.CekBox();
        BtnUpload = new widget.Button();
        BtnCari = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass10 = new widget.panelisi();
        panelGlass13 = new widget.panelisi();
        PanelWallpublic = new usu.widget.glass.PanelGlass();
        panelGlass14 = new widget.panelisi();
        PanelWallwifi = new usu.widget.glass.PanelGlass();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnJenisDokumen.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnJenisDokumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnJenisDokumen.setText("Master Jenis Dokumen");
        MnJenisDokumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnJenisDokumen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnJenisDokumen.setIconTextGap(5);
        MnJenisDokumen.setName("MnJenisDokumen"); // NOI18N
        MnJenisDokumen.setPreferredSize(new java.awt.Dimension(190, 26));
        MnJenisDokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnJenisDokumenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnJenisDokumen);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Dokumen Penunjang Medis Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass7.setToolTipText("Klik kanan disini untuk menambahkan jenis dokumen penunjang baru");
        panelGlass7.setComponentPopupMenu(jPopupMenu1);
        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 45));
        panelGlass7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pasien :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass7.add(jLabel3);

        TNoRW.setEditable(false);
        TNoRW.setForeground(new java.awt.Color(0, 0, 0));
        TNoRW.setName("TNoRW"); // NOI18N
        TNoRW.setPreferredSize(new java.awt.Dimension(122, 24));
        panelGlass7.add(TNoRW);

        TNoRM.setEditable(false);
        TNoRM.setForeground(new java.awt.Color(0, 0, 0));
        TNoRM.setName("TNoRM"); // NOI18N
        TNoRM.setPreferredSize(new java.awt.Dimension(70, 24));
        panelGlass7.add(TNoRM);

        TNmPasien.setEditable(false);
        TNmPasien.setForeground(new java.awt.Color(0, 0, 0));
        TNmPasien.setName("TNmPasien"); // NOI18N
        TNmPasien.setPreferredSize(new java.awt.Dimension(291, 24));
        panelGlass7.add(TNmPasien);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.PAGE_START);

        PanelContent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "[ Preview File Dokumen Penunjang Medis ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        PanelContent.setToolTipText("Klik kanan disini untuk menambahkan jenis dokumen penunjang baru");
        PanelContent.setComponentPopupMenu(jPopupMenu1);
        PanelContent.setName("PanelContent"); // NOI18N
        PanelContent.setPreferredSize(new java.awt.Dimension(55, 55));
        PanelContent.setLayout(new java.awt.BorderLayout());

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setForeground(new java.awt.Color(0, 0, 0));
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        PanelContent.add(Scroll1, java.awt.BorderLayout.CENTER);

        panelGlass8.setToolTipText("Klik kanan disini untuk menambahkan jenis dokumen penunjang baru");
        panelGlass8.setComponentPopupMenu(jPopupMenu1);
        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 40));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 9));

        ChkDokumen.setBackground(new java.awt.Color(255, 255, 250));
        ChkDokumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        ChkDokumen.setForeground(new java.awt.Color(0, 0, 0));
        ChkDokumen.setText("Semua Dokumen Penunjang Medis");
        ChkDokumen.setBorderPainted(true);
        ChkDokumen.setBorderPaintedFlat(true);
        ChkDokumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkDokumen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkDokumen.setName("ChkDokumen"); // NOI18N
        ChkDokumen.setOpaque(false);
        ChkDokumen.setPreferredSize(new java.awt.Dimension(210, 23));
        ChkDokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkDokumenActionPerformed(evt);
            }
        });
        panelGlass8.add(ChkDokumen);

        BtnUpload.setForeground(new java.awt.Color(0, 0, 0));
        BtnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/34.png"))); // NOI18N
        BtnUpload.setMnemonic('U');
        BtnUpload.setText("Upload Dokumen");
        BtnUpload.setToolTipText("Alt+U");
        BtnUpload.setName("BtnUpload"); // NOI18N
        BtnUpload.setPreferredSize(new java.awt.Dimension(140, 23));
        BtnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUploadActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnUpload);

        BtnCari.setForeground(new java.awt.Color(0, 0, 0));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setText("Tampilkan Data");
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(130, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnCari);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(80, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        PanelContent.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelContent, java.awt.BorderLayout.CENTER);

        panelGlass10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "[ Scan QRCode Untuk Upload File ]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelGlass10.setName("panelGlass10"); // NOI18N
        panelGlass10.setPreferredSize(new java.awt.Dimension(230, 422));

        panelGlass13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2), "[ Koneksi Paket Data ]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        panelGlass13.setToolTipText("");
        panelGlass13.setComponentPopupMenu(jPopupMenu1);
        panelGlass13.setName("panelGlass13"); // NOI18N
        panelGlass13.setPreferredSize(new java.awt.Dimension(200, 200));
        panelGlass13.setLayout(new java.awt.BorderLayout());

        PanelWallpublic.setBackground(new java.awt.Color(29, 29, 29));
        PanelWallpublic.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/qrcode_upload_dok_jangmed.png"))); // NOI18N
        PanelWallpublic.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWallpublic.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWallpublic.setRound(false);
        PanelWallpublic.setToolTipText("");
        PanelWallpublic.setWarna(new java.awt.Color(110, 110, 110));
        PanelWallpublic.setLayout(null);
        panelGlass13.add(PanelWallpublic, java.awt.BorderLayout.CENTER);

        panelGlass10.add(panelGlass13);

        panelGlass14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2), "[ Koneksi Wifi RS ]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        panelGlass14.setToolTipText("");
        panelGlass14.setComponentPopupMenu(jPopupMenu1);
        panelGlass14.setName("panelGlass14"); // NOI18N
        panelGlass14.setPreferredSize(new java.awt.Dimension(200, 200));
        panelGlass14.setLayout(new java.awt.BorderLayout());

        PanelWallwifi.setBackground(new java.awt.Color(29, 29, 29));
        PanelWallwifi.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/qrcode_upload_dok_jangmed_wifi.png"))); // NOI18N
        PanelWallwifi.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWallwifi.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWallwifi.setRound(false);
        PanelWallwifi.setToolTipText("");
        PanelWallwifi.setWarna(new java.awt.Color(110, 110, 110));
        PanelWallwifi.setLayout(null);
        panelGlass14.add(PanelWallwifi, java.awt.BorderLayout.CENTER);

        panelGlass10.add(panelGlass14);

        internalFrame1.add(panelGlass10, java.awt.BorderLayout.EAST);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
        
        if (akses.getadmin() == true) {
            MnJenisDokumen.setEnabled(true);
        } else {
            MnJenisDokumen.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void BtnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUploadActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {            
            Valid.panggilUrlRME("/rmelokal/");
        } catch (Exception ex) {
            System.out.println("Notifikasi : " + ex);
        }

        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnUploadActionPerformed

    private void MnJenisDokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnJenisDokumenActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        akses.setform("RMDokumenPenunjangMedis");
        DlgMasterJenisDokumenJangMed form = new DlgMasterJenisDokumenJangMed(null, false);
        form.setSize(626, internalFrame1.getHeight() - 40);
        form.setLocationRelativeTo(internalFrame1);
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_MnJenisDokumenActionPerformed

    private void ChkDokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkDokumenActionPerformed
        tampil();
    }//GEN-LAST:event_ChkDokumenActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } 
    }//GEN-LAST:event_BtnCariKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMDokumenPenunjangMedis dialog = new RMDokumenPenunjangMedis(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnUpload;
    public widget.CekBox ChkDokumen;
    private widget.editorpane LoadHTML1;
    private javax.swing.JMenuItem MnJenisDokumen;
    private widget.panelisi PanelContent;
    private usu.widget.glass.PanelGlass PanelWallpublic;
    private usu.widget.glass.PanelGlass PanelWallwifi;
    private widget.ScrollPane Scroll1;
    private widget.TextBox TNmPasien;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.panelisi panelGlass10;
    private widget.panelisi panelGlass13;
    private widget.panelisi panelGlass14;
    private widget.panelisi panelGlass7;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            StringBuilder htmlContent = new StringBuilder();
            try {
                if (ChkDokumen.isSelected() == true) {
                    rs = koneksi.prepareStatement("SELECT rf.id_file, rf.no_rawat, rf.nama_file_ori, date_format(rf.tgl_upload,'%d/%m/%Y') tglUpload, "
                            + "time_format(rf.tgl_upload,'%H:%i') jam, rj.nama_pemeriksaan, ifnull(pg.nama,'-') nmpetugas, rf.jenis_pemeriksaan kode, "
                            + "rf.petugas nip from rme_file_upload rf inner join rme_jenis_pemeriksaan rj on rj.kode_jenis_pemeriksaan=rf.jenis_pemeriksaan "
                            + "left join pegawai pg on pg.nik=rf.petugas where rf.nomr='" + TNoRM.getText() + "' and rf.stts_data='1' "
                            + "order by rf.tgl_upload desc").executeQuery();
                } else {
                    rs = koneksi.prepareStatement("SELECT rf.id_file, rf.no_rawat, rf.nama_file_ori, date_format(rf.tgl_upload,'%d/%m/%Y') tglUpload, "
                            + "time_format(rf.tgl_upload,'%H:%i') jam, rj.nama_pemeriksaan, ifnull(pg.nama,'-') nmpetugas, rf.jenis_pemeriksaan kode, "
                            + "rf.petugas nip from rme_file_upload rf inner join rme_jenis_pemeriksaan rj on rj.kode_jenis_pemeriksaan=rf.jenis_pemeriksaan "
                            + "left join pegawai pg on pg.nik=rf.petugas where rf.no_rawat='" + TNoRW.getText() + "' and rf.stts_data='1' "
                            + "order by rf.tgl_upload desc").executeQuery();
                }

                urut = 1;
                if (rs.next()) {
                    htmlContent.append(
                            "<table width='100%' class='isi'>"
                            + "<thead>"
                            + "<tr class='isi'>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>No.</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Kode File</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Nama Pemeriksaan</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Tgl. Upload</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Jam</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Nama File</b></td>"
                            + "<td align='center' bgcolor='#f8fdf3'><b>Petugas Yang Upload</b></td>"
                            + "</tr>"
                            + "</thead>"
                            + "<tbody>"
                    );

                    rs.beforeFirst();
                    while (rs.next()) {
                        htmlContent.append(
                                "<tr class='isi'>"
                                + "<td valign='top' width='20px'>" + urut + ".</td>"
                                + "<td valign='top' align='center'>" + rs.getString("id_file") + "</td>"
                                + "<td valign='top'>" + rs.getString("nama_pemeriksaan") + "</td>"
                                + "<td valign='top' align='center'>" + rs.getString("tglUpload") + "</td>"
                                + "<td valign='top' align='center'>" + rs.getString("jam") + " Wita" + "</td>"
                                + "<td valign='top'>" + rs.getString("nama_file_ori") + " " + "<a href='" + link + "rme/view/?id=" + rs.getString("id_file") + "'>[Klik Untuk Membuka Gambar]</a></td>"
                                + "<td valign='top'>" + rs.getString("nmpetugas") + "</td>"
                                + "</tr>"
                        );
                        urut++;
                    }
                    htmlContent.append(
                            "</tbody>"
                            + "</table>"
                    );
                }
                LoadHTML1.setText(
                        "<html>"
                        + "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"
                        + htmlContent.toString()
                        + "</table>"
                        + "</html>");
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public void setData(String norw, String norm, String nmpasien) {
        TNoRW.setText(norw);
        TNoRM.setText(norm);
        TNmPasien.setText(nmpasien);
        ChkDokumen.setSelected(false);
    }
}
