    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgSpesialis.java
 *
 * Created on May 23, 2010, 1:25:13 AM
 */

package rekammedis;
import static com.sun.org.glassfish.external.amx.AMXUtil.prop;
import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Date;
import java.util.Properties;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import static javafx.concurrent.Worker.State.FAILED;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.PopupFeatures;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;
import javax.swing.JOptionPane;

/**
 *
 * @author dosen
 */
public class RMGrafikPemantauanHarian24Jam extends javax.swing.JDialog {
    private final Connection koneksi = koneksiDB.condb();
    private final Properties prop = new Properties();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private String norawat = "", host_grafik_rme = "";
    
    /** Creates new form DlgSpesialis
     * @param parent
     * @param modal */
    public RMGrafikPemantauanHarian24Jam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel3 = new widget.Label();
        tglPantau = new widget.Tanggal();
        jLabel4 = new widget.Label();
        cmbGrafik = new widget.ComboBox();
        BtnGrafik = new widget.Button();
        BtnKeluar3 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Grafik Pemantauan Harian Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tgl. Pemantauan :");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame1.add(jLabel3);

        tglPantau.setForeground(new java.awt.Color(50, 70, 50));
        tglPantau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-02-2024" }));
        tglPantau.setDisplayFormat("dd-MM-yyyy");
        tglPantau.setName("tglPantau"); // NOI18N
        tglPantau.setOpaque(false);
        tglPantau.setPreferredSize(new java.awt.Dimension(90, 23));
        internalFrame1.add(tglPantau);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jenis Grafik :");
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(85, 23));
        internalFrame1.add(jLabel4);

        cmbGrafik.setForeground(new java.awt.Color(0, 0, 0));
        cmbGrafik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Per Jam", "Per Tanggal" }));
        cmbGrafik.setName("cmbGrafik"); // NOI18N
        cmbGrafik.setPreferredSize(new java.awt.Dimension(89, 23));
        internalFrame1.add(cmbGrafik);

        BtnGrafik.setForeground(new java.awt.Color(0, 0, 0));
        BtnGrafik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Bar Chart (copy).png"))); // NOI18N
        BtnGrafik.setMnemonic('G');
        BtnGrafik.setText("Lihat Grafik");
        BtnGrafik.setToolTipText("Alt+G");
        BtnGrafik.setName("BtnGrafik"); // NOI18N
        BtnGrafik.setPreferredSize(new java.awt.Dimension(120, 23));
        BtnGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrafikActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnGrafik);

        BtnKeluar3.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar3.setMnemonic('K');
        BtnKeluar3.setText("Keluar");
        BtnKeluar3.setToolTipText("Alt+K");
        BtnKeluar3.setName("BtnKeluar3"); // NOI18N
        BtnKeluar3.setPreferredSize(new java.awt.Dimension(90, 23));
        BtnKeluar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar3ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnKeluar3);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void BtnKeluar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar3ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluar3ActionPerformed

    private void BtnGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrafikActionPerformed
        if (Sequel.cariInteger("select count(-1) from pemantauan_harian_24jam where no_rawat='" + norawat + "'") == 0) {
            JOptionPane.showMessageDialog(null, "Grafik pemantauan harian pasien dengan no. rawat " + norawat + " tidak ditemukan..!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                host_grafik_rme = Sequel.decXML(prop.getProperty("HOSTgrafikRME"), prop.getProperty("KEY"));
                if (cmbGrafik.getSelectedIndex() == 0) {
                    if (Sequel.cariInteger("select count(-1) from pemantauan_harian_24jam where no_rawat='" + norawat + "' "
                            + "and tgl_pantau='" + Valid.SetTgl(tglPantau.getSelectedItem() + "") + "'") == 0) {
                        JOptionPane.showMessageDialog(null, "Grafik pemantauan harian pasien pada tgl. "
                                + Valid.SetTglINDONESIA(Valid.SetTgl(tglPantau.getSelectedItem() + "")) + " tidak ditemukan..!!");
                        tglPantau.requestFocus();
                    } else {
                        Valid.panggilUrlRME("/rme/pemantauan/?norawat=" + norawat + "&tgl=" + Valid.SetTgl(tglPantau.getSelectedItem() + ""));
                    }
                } else {
                    Valid.panggilUrlRME("/rme/pemantauan/?norawat=" + norawat);
                }
            } catch (Exception ex) {
                System.out.println("Notifikasi : " + ex);
            }
            this.setCursor(Cursor.getDefaultCursor());
            dispose();
        }
    }//GEN-LAST:event_BtnGrafikActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMGrafikPemantauanHarian24Jam dialog = new RMGrafikPemantauanHarian24Jam(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnGrafik;
    private widget.Button BtnKeluar3;
    private widget.ComboBox cmbGrafik;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Tanggal tglPantau;
    // End of variables declaration//GEN-END:variables

    public void setData(String norw) {
        norawat = norw;
        
        if (Sequel.cariInteger("select count(-1) from pemantauan_harian_24jam where no_rawat='" + norw + "'") > 0) {
            Valid.SetTgl(tglPantau, Sequel.cariIsi("select tgl_pantau from pemantauan_harian_24jam where "
                    + "no_rawat='" + norw + "' order by tgl_pantau desc limit 1"));
            cmbGrafik.requestFocus();
        } else {
            tglPantau.setDate(new Date());
            tglPantau.requestFocus();
        }
    }
}
