package rekammedis;

import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author dosen
 */
public class RMInspeksiPemeriksaanGinekologi extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private int x = 0;
    private PreparedStatement ps;
    private ResultSet rs;
    private String vulvaNormal = "", vulvaHiperemis = "", vulvaEdema = "", vulvaAdaLesi = "", vulvaMasa = "", labiaSimetris = "", labiaTdkSimetris = "", 
            labiaAdaLuka = "", labiaAdaBenjolan = "", klitorisNormal = "", klitorisHipertrofi = "", klitorisLainya = "", perineumUtuh = "", 
            perineumAdaLuka = "", perineumBekas = "", perineumFistula = "", introitusNormal = "", introitusAdaSekret = "", introitusAdaPerdarahan = "", 
            introitusAdaRobekan = "", sekretTdkAda = "", sekretJernih = "", sekretPutih = "", sekretKuning = "", sekretBerbau = "", dindingNormal = "", 
            dindingHiperemis = "", dindingAtrofi = "", dindingAdaMasa = "", dindingAdaSekret = "", serviksBentukNormal = "", serviksBentukErosi = "", 
            serviksBentukPolip = "", serviksBentukEktropion = "", serviksWarnaNormal = "", serviksWarnaHiperemis = "", serviksWarnaPucat = "", 
            serviksPermuHalus = "", serviksPermuGranulasi = "", serviksPermuUlserasi = "", norawat = "";
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public RMInspeksiPemeriksaanGinekologi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TketKliLain.setDocument(new batasInput((int) 255).getKata(TketKliLain));
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnHapus = new widget.Button();
        BtnGanti = new widget.Button();
        BtnKeluar = new widget.Button();
        FormInput = new widget.PanelBiasa();
        jLabel365 = new widget.Label();
        chkVulNormal = new widget.CekBox();
        chkVulHiperemis = new widget.CekBox();
        chkVulEdema = new widget.CekBox();
        chkVulAdaLesi = new widget.CekBox();
        chkVulMasa = new widget.CekBox();
        jLabel366 = new widget.Label();
        chkLabSimetris = new widget.CekBox();
        chkLabTdkSimetris = new widget.CekBox();
        chkLabAdaLuka = new widget.CekBox();
        chkLabAdaBenjol = new widget.CekBox();
        jLabel367 = new widget.Label();
        chkKliNormal = new widget.CekBox();
        chkKliHiper = new widget.CekBox();
        chkKliLain = new widget.CekBox();
        TketKliLain = new widget.TextBox();
        jLabel368 = new widget.Label();
        chkPerUtuh = new widget.CekBox();
        chkPerAdaLuka = new widget.CekBox();
        chkPerBekas = new widget.CekBox();
        chkPerFistula = new widget.CekBox();
        jLabel369 = new widget.Label();
        chkIntroNormal = new widget.CekBox();
        chkIntroAdaSekret = new widget.CekBox();
        chkIntroAdaPerdarahan = new widget.CekBox();
        chkIntroAdaRobek = new widget.CekBox();
        jLabel370 = new widget.Label();
        chkSekTdkAda = new widget.CekBox();
        chkSekJernih = new widget.CekBox();
        chkSekPutih = new widget.CekBox();
        chkSekKuning = new widget.CekBox();
        chkSekBerbau = new widget.CekBox();
        jLabel371 = new widget.Label();
        cmbSekServik = new widget.ComboBox();
        jLabel372 = new widget.Label();
        chkDinNormal = new widget.CekBox();
        chkDinHiperemis = new widget.CekBox();
        chkDinAtrofi = new widget.CekBox();
        chkDinAdaMasa = new widget.CekBox();
        chkDinAdaSekret = new widget.CekBox();
        jLabel373 = new widget.Label();
        chkSerBenNormal = new widget.CekBox();
        chkSerBenErosi = new widget.CekBox();
        chkSerBenPolip = new widget.CekBox();
        chkSerBenEktro = new widget.CekBox();
        jLabel374 = new widget.Label();
        jLabel375 = new widget.Label();
        chkSerWarNormal = new widget.CekBox();
        chkSerWarHiperemis = new widget.CekBox();
        chkSerWarPucat = new widget.CekBox();
        jLabel376 = new widget.Label();
        chkSerPerHalus = new widget.CekBox();
        chkSerPerGran = new widget.CekBox();
        chkSerPerUlser = new widget.CekBox();
        jLabel377 = new widget.Label();
        cmbJmlSek = new widget.ComboBox();
        cmbSekServikAda = new widget.ComboBox();
        jLabel378 = new widget.Label();
        Ttemuan = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Inspeksi Pemeriksaan Ginekologi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnHapus.setForeground(new java.awt.Color(0, 0, 0));
        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnGanti.setForeground(new java.awt.Color(0, 0, 0));
        BtnGanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnGanti.setMnemonic('G');
        BtnGanti.setText("Ganti");
        BtnGanti.setToolTipText("Alt+G");
        BtnGanti.setName("BtnGanti"); // NOI18N
        BtnGanti.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGantiActionPerformed(evt);
            }
        });
        BtnGanti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnGantiKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnGanti);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(190, 107));
        FormInput.setLayout(null);

        jLabel365.setForeground(new java.awt.Color(0, 0, 0));
        jLabel365.setText("Vulva :");
        jLabel365.setName("jLabel365"); // NOI18N
        FormInput.add(jLabel365);
        jLabel365.setBounds(0, 10, 120, 23);

        chkVulNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkVulNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkVulNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkVulNormal.setText("Normal");
        chkVulNormal.setBorderPainted(true);
        chkVulNormal.setBorderPaintedFlat(true);
        chkVulNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkVulNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkVulNormal.setName("chkVulNormal"); // NOI18N
        chkVulNormal.setOpaque(false);
        chkVulNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkVulNormal);
        chkVulNormal.setBounds(125, 10, 60, 23);

        chkVulHiperemis.setBackground(new java.awt.Color(255, 255, 250));
        chkVulHiperemis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkVulHiperemis.setForeground(new java.awt.Color(0, 0, 0));
        chkVulHiperemis.setText("Hiperemis");
        chkVulHiperemis.setBorderPainted(true);
        chkVulHiperemis.setBorderPaintedFlat(true);
        chkVulHiperemis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkVulHiperemis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkVulHiperemis.setName("chkVulHiperemis"); // NOI18N
        chkVulHiperemis.setOpaque(false);
        chkVulHiperemis.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkVulHiperemis);
        chkVulHiperemis.setBounds(195, 10, 80, 23);

        chkVulEdema.setBackground(new java.awt.Color(255, 255, 250));
        chkVulEdema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkVulEdema.setForeground(new java.awt.Color(0, 0, 0));
        chkVulEdema.setText("Edema");
        chkVulEdema.setBorderPainted(true);
        chkVulEdema.setBorderPaintedFlat(true);
        chkVulEdema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkVulEdema.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkVulEdema.setName("chkVulEdema"); // NOI18N
        chkVulEdema.setOpaque(false);
        chkVulEdema.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkVulEdema);
        chkVulEdema.setBounds(285, 10, 60, 23);

        chkVulAdaLesi.setBackground(new java.awt.Color(255, 255, 250));
        chkVulAdaLesi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkVulAdaLesi.setForeground(new java.awt.Color(0, 0, 0));
        chkVulAdaLesi.setText("Ada lesi/ulkus");
        chkVulAdaLesi.setBorderPainted(true);
        chkVulAdaLesi.setBorderPaintedFlat(true);
        chkVulAdaLesi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkVulAdaLesi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkVulAdaLesi.setName("chkVulAdaLesi"); // NOI18N
        chkVulAdaLesi.setOpaque(false);
        chkVulAdaLesi.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkVulAdaLesi);
        chkVulAdaLesi.setBounds(355, 10, 97, 23);

        chkVulMasa.setBackground(new java.awt.Color(255, 255, 250));
        chkVulMasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkVulMasa.setForeground(new java.awt.Color(0, 0, 0));
        chkVulMasa.setText("Massa");
        chkVulMasa.setBorderPainted(true);
        chkVulMasa.setBorderPaintedFlat(true);
        chkVulMasa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkVulMasa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkVulMasa.setName("chkVulMasa"); // NOI18N
        chkVulMasa.setOpaque(false);
        chkVulMasa.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkVulMasa);
        chkVulMasa.setBounds(460, 10, 60, 23);

        jLabel366.setForeground(new java.awt.Color(0, 0, 0));
        jLabel366.setText("Labia Majora/Minora :");
        jLabel366.setName("jLabel366"); // NOI18N
        FormInput.add(jLabel366);
        jLabel366.setBounds(0, 38, 120, 23);

        chkLabSimetris.setBackground(new java.awt.Color(255, 255, 250));
        chkLabSimetris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkLabSimetris.setForeground(new java.awt.Color(0, 0, 0));
        chkLabSimetris.setText("Simetris");
        chkLabSimetris.setBorderPainted(true);
        chkLabSimetris.setBorderPaintedFlat(true);
        chkLabSimetris.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLabSimetris.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkLabSimetris.setName("chkLabSimetris"); // NOI18N
        chkLabSimetris.setOpaque(false);
        chkLabSimetris.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkLabSimetris);
        chkLabSimetris.setBounds(125, 38, 68, 23);

        chkLabTdkSimetris.setBackground(new java.awt.Color(255, 255, 250));
        chkLabTdkSimetris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkLabTdkSimetris.setForeground(new java.awt.Color(0, 0, 0));
        chkLabTdkSimetris.setText("Tidak Simetris");
        chkLabTdkSimetris.setBorderPainted(true);
        chkLabTdkSimetris.setBorderPaintedFlat(true);
        chkLabTdkSimetris.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLabTdkSimetris.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkLabTdkSimetris.setName("chkLabTdkSimetris"); // NOI18N
        chkLabTdkSimetris.setOpaque(false);
        chkLabTdkSimetris.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkLabTdkSimetris);
        chkLabTdkSimetris.setBounds(200, 38, 95, 23);

        chkLabAdaLuka.setBackground(new java.awt.Color(255, 255, 250));
        chkLabAdaLuka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkLabAdaLuka.setForeground(new java.awt.Color(0, 0, 0));
        chkLabAdaLuka.setText("Ada Luka");
        chkLabAdaLuka.setBorderPainted(true);
        chkLabAdaLuka.setBorderPaintedFlat(true);
        chkLabAdaLuka.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLabAdaLuka.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkLabAdaLuka.setName("chkLabAdaLuka"); // NOI18N
        chkLabAdaLuka.setOpaque(false);
        chkLabAdaLuka.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkLabAdaLuka);
        chkLabAdaLuka.setBounds(302, 38, 75, 23);

        chkLabAdaBenjol.setBackground(new java.awt.Color(255, 255, 250));
        chkLabAdaBenjol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkLabAdaBenjol.setForeground(new java.awt.Color(0, 0, 0));
        chkLabAdaBenjol.setText("Ada Benjolan");
        chkLabAdaBenjol.setBorderPainted(true);
        chkLabAdaBenjol.setBorderPaintedFlat(true);
        chkLabAdaBenjol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkLabAdaBenjol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkLabAdaBenjol.setName("chkLabAdaBenjol"); // NOI18N
        chkLabAdaBenjol.setOpaque(false);
        chkLabAdaBenjol.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkLabAdaBenjol);
        chkLabAdaBenjol.setBounds(387, 38, 97, 23);

        jLabel367.setForeground(new java.awt.Color(0, 0, 0));
        jLabel367.setText("Klitoris :");
        jLabel367.setName("jLabel367"); // NOI18N
        FormInput.add(jLabel367);
        jLabel367.setBounds(0, 66, 120, 23);

        chkKliNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkKliNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkKliNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkKliNormal.setText("Normal");
        chkKliNormal.setBorderPainted(true);
        chkKliNormal.setBorderPaintedFlat(true);
        chkKliNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkKliNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkKliNormal.setName("chkKliNormal"); // NOI18N
        chkKliNormal.setOpaque(false);
        chkKliNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkKliNormal);
        chkKliNormal.setBounds(125, 66, 63, 23);

        chkKliHiper.setBackground(new java.awt.Color(255, 255, 250));
        chkKliHiper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkKliHiper.setForeground(new java.awt.Color(0, 0, 0));
        chkKliHiper.setText("Hipertrofi");
        chkKliHiper.setBorderPainted(true);
        chkKliHiper.setBorderPaintedFlat(true);
        chkKliHiper.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkKliHiper.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkKliHiper.setName("chkKliHiper"); // NOI18N
        chkKliHiper.setOpaque(false);
        chkKliHiper.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkKliHiper);
        chkKliHiper.setBounds(200, 66, 80, 23);

        chkKliLain.setBackground(new java.awt.Color(255, 255, 250));
        chkKliLain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkKliLain.setForeground(new java.awt.Color(0, 0, 0));
        chkKliLain.setText("Lainnya :");
        chkKliLain.setBorderPainted(true);
        chkKliLain.setBorderPaintedFlat(true);
        chkKliLain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkKliLain.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkKliLain.setName("chkKliLain"); // NOI18N
        chkKliLain.setOpaque(false);
        chkKliLain.setPreferredSize(new java.awt.Dimension(175, 23));
        chkKliLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKliLainActionPerformed(evt);
            }
        });
        FormInput.add(chkKliLain);
        chkKliLain.setBounds(302, 66, 67, 23);

        TketKliLain.setForeground(new java.awt.Color(0, 0, 0));
        TketKliLain.setName("TketKliLain"); // NOI18N
        FormInput.add(TketKliLain);
        TketKliLain.setBounds(370, 66, 235, 23);

        jLabel368.setForeground(new java.awt.Color(0, 0, 0));
        jLabel368.setText("Perineum :");
        jLabel368.setName("jLabel368"); // NOI18N
        FormInput.add(jLabel368);
        jLabel368.setBounds(0, 94, 120, 23);

        chkPerUtuh.setBackground(new java.awt.Color(255, 255, 250));
        chkPerUtuh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkPerUtuh.setForeground(new java.awt.Color(0, 0, 0));
        chkPerUtuh.setText("Utuh");
        chkPerUtuh.setBorderPainted(true);
        chkPerUtuh.setBorderPaintedFlat(true);
        chkPerUtuh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkPerUtuh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkPerUtuh.setName("chkPerUtuh"); // NOI18N
        chkPerUtuh.setOpaque(false);
        chkPerUtuh.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkPerUtuh);
        chkPerUtuh.setBounds(125, 94, 50, 23);

        chkPerAdaLuka.setBackground(new java.awt.Color(255, 255, 250));
        chkPerAdaLuka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkPerAdaLuka.setForeground(new java.awt.Color(0, 0, 0));
        chkPerAdaLuka.setText("Ada Luka");
        chkPerAdaLuka.setBorderPainted(true);
        chkPerAdaLuka.setBorderPaintedFlat(true);
        chkPerAdaLuka.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkPerAdaLuka.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkPerAdaLuka.setName("chkPerAdaLuka"); // NOI18N
        chkPerAdaLuka.setOpaque(false);
        chkPerAdaLuka.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkPerAdaLuka);
        chkPerAdaLuka.setBounds(184, 94, 70, 23);

        chkPerBekas.setBackground(new java.awt.Color(255, 255, 250));
        chkPerBekas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkPerBekas.setForeground(new java.awt.Color(0, 0, 0));
        chkPerBekas.setText("Bekas Episiotomi");
        chkPerBekas.setBorderPainted(true);
        chkPerBekas.setBorderPaintedFlat(true);
        chkPerBekas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkPerBekas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkPerBekas.setName("chkPerBekas"); // NOI18N
        chkPerBekas.setOpaque(false);
        chkPerBekas.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkPerBekas);
        chkPerBekas.setBounds(263, 94, 110, 23);

        chkPerFistula.setBackground(new java.awt.Color(255, 255, 250));
        chkPerFistula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkPerFistula.setForeground(new java.awt.Color(0, 0, 0));
        chkPerFistula.setText("Fistula");
        chkPerFistula.setBorderPainted(true);
        chkPerFistula.setBorderPaintedFlat(true);
        chkPerFistula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkPerFistula.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkPerFistula.setName("chkPerFistula"); // NOI18N
        chkPerFistula.setOpaque(false);
        chkPerFistula.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkPerFistula);
        chkPerFistula.setBounds(387, 94, 70, 23);

        jLabel369.setForeground(new java.awt.Color(0, 0, 0));
        jLabel369.setText("Introitus Vagina :");
        jLabel369.setName("jLabel369"); // NOI18N
        FormInput.add(jLabel369);
        jLabel369.setBounds(0, 122, 120, 23);

        chkIntroNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkIntroNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkIntroNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkIntroNormal.setText("Normal");
        chkIntroNormal.setBorderPainted(true);
        chkIntroNormal.setBorderPaintedFlat(true);
        chkIntroNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkIntroNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkIntroNormal.setName("chkIntroNormal"); // NOI18N
        chkIntroNormal.setOpaque(false);
        chkIntroNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkIntroNormal);
        chkIntroNormal.setBounds(125, 122, 60, 23);

        chkIntroAdaSekret.setBackground(new java.awt.Color(255, 255, 250));
        chkIntroAdaSekret.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkIntroAdaSekret.setForeground(new java.awt.Color(0, 0, 0));
        chkIntroAdaSekret.setText("Ada Sekret");
        chkIntroAdaSekret.setBorderPainted(true);
        chkIntroAdaSekret.setBorderPaintedFlat(true);
        chkIntroAdaSekret.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkIntroAdaSekret.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkIntroAdaSekret.setName("chkIntroAdaSekret"); // NOI18N
        chkIntroAdaSekret.setOpaque(false);
        chkIntroAdaSekret.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkIntroAdaSekret);
        chkIntroAdaSekret.setBounds(192, 122, 80, 23);

        chkIntroAdaPerdarahan.setBackground(new java.awt.Color(255, 255, 250));
        chkIntroAdaPerdarahan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkIntroAdaPerdarahan.setForeground(new java.awt.Color(0, 0, 0));
        chkIntroAdaPerdarahan.setText("Ada Perdarahan");
        chkIntroAdaPerdarahan.setBorderPainted(true);
        chkIntroAdaPerdarahan.setBorderPaintedFlat(true);
        chkIntroAdaPerdarahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkIntroAdaPerdarahan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkIntroAdaPerdarahan.setName("chkIntroAdaPerdarahan"); // NOI18N
        chkIntroAdaPerdarahan.setOpaque(false);
        chkIntroAdaPerdarahan.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkIntroAdaPerdarahan);
        chkIntroAdaPerdarahan.setBounds(280, 122, 110, 23);

        chkIntroAdaRobek.setBackground(new java.awt.Color(255, 255, 250));
        chkIntroAdaRobek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkIntroAdaRobek.setForeground(new java.awt.Color(0, 0, 0));
        chkIntroAdaRobek.setText("Ada Robekan");
        chkIntroAdaRobek.setBorderPainted(true);
        chkIntroAdaRobek.setBorderPaintedFlat(true);
        chkIntroAdaRobek.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkIntroAdaRobek.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkIntroAdaRobek.setName("chkIntroAdaRobek"); // NOI18N
        chkIntroAdaRobek.setOpaque(false);
        chkIntroAdaRobek.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkIntroAdaRobek);
        chkIntroAdaRobek.setBounds(400, 122, 95, 23);

        jLabel370.setForeground(new java.awt.Color(0, 0, 0));
        jLabel370.setText("Sekret Vaginal :");
        jLabel370.setName("jLabel370"); // NOI18N
        FormInput.add(jLabel370);
        jLabel370.setBounds(0, 150, 120, 23);

        chkSekTdkAda.setBackground(new java.awt.Color(255, 255, 250));
        chkSekTdkAda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSekTdkAda.setForeground(new java.awt.Color(0, 0, 0));
        chkSekTdkAda.setText("Tidak Ada");
        chkSekTdkAda.setBorderPainted(true);
        chkSekTdkAda.setBorderPaintedFlat(true);
        chkSekTdkAda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSekTdkAda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSekTdkAda.setName("chkSekTdkAda"); // NOI18N
        chkSekTdkAda.setOpaque(false);
        chkSekTdkAda.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSekTdkAda);
        chkSekTdkAda.setBounds(125, 150, 75, 23);

        chkSekJernih.setBackground(new java.awt.Color(255, 255, 250));
        chkSekJernih.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSekJernih.setForeground(new java.awt.Color(0, 0, 0));
        chkSekJernih.setText("Jernih");
        chkSekJernih.setBorderPainted(true);
        chkSekJernih.setBorderPaintedFlat(true);
        chkSekJernih.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSekJernih.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSekJernih.setName("chkSekJernih"); // NOI18N
        chkSekJernih.setOpaque(false);
        chkSekJernih.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSekJernih);
        chkSekJernih.setBounds(207, 150, 60, 23);

        chkSekPutih.setBackground(new java.awt.Color(255, 255, 250));
        chkSekPutih.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSekPutih.setForeground(new java.awt.Color(0, 0, 0));
        chkSekPutih.setText("Putih Kental");
        chkSekPutih.setBorderPainted(true);
        chkSekPutih.setBorderPaintedFlat(true);
        chkSekPutih.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSekPutih.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSekPutih.setName("chkSekPutih"); // NOI18N
        chkSekPutih.setOpaque(false);
        chkSekPutih.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSekPutih);
        chkSekPutih.setBounds(276, 150, 88, 23);

        chkSekKuning.setBackground(new java.awt.Color(255, 255, 250));
        chkSekKuning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSekKuning.setForeground(new java.awt.Color(0, 0, 0));
        chkSekKuning.setText("Kuning Kehijauan");
        chkSekKuning.setBorderPainted(true);
        chkSekKuning.setBorderPaintedFlat(true);
        chkSekKuning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSekKuning.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSekKuning.setName("chkSekKuning"); // NOI18N
        chkSekKuning.setOpaque(false);
        chkSekKuning.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSekKuning);
        chkSekKuning.setBounds(370, 150, 110, 23);

        chkSekBerbau.setBackground(new java.awt.Color(255, 255, 250));
        chkSekBerbau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSekBerbau.setForeground(new java.awt.Color(0, 0, 0));
        chkSekBerbau.setText("Berbau");
        chkSekBerbau.setBorderPainted(true);
        chkSekBerbau.setBorderPaintedFlat(true);
        chkSekBerbau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSekBerbau.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSekBerbau.setName("chkSekBerbau"); // NOI18N
        chkSekBerbau.setOpaque(false);
        chkSekBerbau.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSekBerbau);
        chkSekBerbau.setBounds(490, 150, 60, 23);

        jLabel371.setForeground(new java.awt.Color(0, 0, 0));
        jLabel371.setText("Jumlah :");
        jLabel371.setName("jLabel371"); // NOI18N
        FormInput.add(jLabel371);
        jLabel371.setBounds(560, 150, 50, 23);

        cmbSekServik.setBackground(new java.awt.Color(245, 253, 240));
        cmbSekServik.setForeground(new java.awt.Color(0, 0, 0));
        cmbSekServik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tidak Ada", "Ada" }));
        cmbSekServik.setLightWeightPopupEnabled(false);
        cmbSekServik.setName("cmbSekServik"); // NOI18N
        cmbSekServik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSekServikActionPerformed(evt);
            }
        });
        FormInput.add(cmbSekServik);
        cmbSekServik.setBounds(125, 290, 80, 23);

        jLabel372.setForeground(new java.awt.Color(0, 0, 0));
        jLabel372.setText("Dinding Vagina :");
        jLabel372.setName("jLabel372"); // NOI18N
        FormInput.add(jLabel372);
        jLabel372.setBounds(0, 178, 120, 23);

        chkDinNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkDinNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkDinNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkDinNormal.setText("Normal");
        chkDinNormal.setBorderPainted(true);
        chkDinNormal.setBorderPaintedFlat(true);
        chkDinNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkDinNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDinNormal.setName("chkDinNormal"); // NOI18N
        chkDinNormal.setOpaque(false);
        chkDinNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkDinNormal);
        chkDinNormal.setBounds(125, 178, 65, 23);

        chkDinHiperemis.setBackground(new java.awt.Color(255, 255, 250));
        chkDinHiperemis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkDinHiperemis.setForeground(new java.awt.Color(0, 0, 0));
        chkDinHiperemis.setText("Hiperemis");
        chkDinHiperemis.setBorderPainted(true);
        chkDinHiperemis.setBorderPaintedFlat(true);
        chkDinHiperemis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkDinHiperemis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDinHiperemis.setName("chkDinHiperemis"); // NOI18N
        chkDinHiperemis.setOpaque(false);
        chkDinHiperemis.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkDinHiperemis);
        chkDinHiperemis.setBounds(197, 178, 75, 23);

        chkDinAtrofi.setBackground(new java.awt.Color(255, 255, 250));
        chkDinAtrofi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkDinAtrofi.setForeground(new java.awt.Color(0, 0, 0));
        chkDinAtrofi.setText("Atrofi");
        chkDinAtrofi.setBorderPainted(true);
        chkDinAtrofi.setBorderPaintedFlat(true);
        chkDinAtrofi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkDinAtrofi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDinAtrofi.setName("chkDinAtrofi"); // NOI18N
        chkDinAtrofi.setOpaque(false);
        chkDinAtrofi.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkDinAtrofi);
        chkDinAtrofi.setBounds(279, 178, 55, 23);

        chkDinAdaMasa.setBackground(new java.awt.Color(255, 255, 250));
        chkDinAdaMasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkDinAdaMasa.setForeground(new java.awt.Color(0, 0, 0));
        chkDinAdaMasa.setText("Ada Massa");
        chkDinAdaMasa.setBorderPainted(true);
        chkDinAdaMasa.setBorderPaintedFlat(true);
        chkDinAdaMasa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkDinAdaMasa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDinAdaMasa.setName("chkDinAdaMasa"); // NOI18N
        chkDinAdaMasa.setOpaque(false);
        chkDinAdaMasa.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkDinAdaMasa);
        chkDinAdaMasa.setBounds(343, 178, 80, 23);

        chkDinAdaSekret.setBackground(new java.awt.Color(255, 255, 250));
        chkDinAdaSekret.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkDinAdaSekret.setForeground(new java.awt.Color(0, 0, 0));
        chkDinAdaSekret.setText("Ada Sekret");
        chkDinAdaSekret.setBorderPainted(true);
        chkDinAdaSekret.setBorderPaintedFlat(true);
        chkDinAdaSekret.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkDinAdaSekret.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDinAdaSekret.setName("chkDinAdaSekret"); // NOI18N
        chkDinAdaSekret.setOpaque(false);
        chkDinAdaSekret.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkDinAdaSekret);
        chkDinAdaSekret.setBounds(430, 178, 80, 23);

        jLabel373.setForeground(new java.awt.Color(0, 0, 0));
        jLabel373.setText("Serviks Uteri :");
        jLabel373.setName("jLabel373"); // NOI18N
        FormInput.add(jLabel373);
        jLabel373.setBounds(0, 206, 120, 23);

        chkSerBenNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkSerBenNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerBenNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkSerBenNormal.setText("Normal");
        chkSerBenNormal.setBorderPainted(true);
        chkSerBenNormal.setBorderPaintedFlat(true);
        chkSerBenNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerBenNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerBenNormal.setName("chkSerBenNormal"); // NOI18N
        chkSerBenNormal.setOpaque(false);
        chkSerBenNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerBenNormal);
        chkSerBenNormal.setBounds(200, 206, 65, 23);

        chkSerBenErosi.setBackground(new java.awt.Color(255, 255, 250));
        chkSerBenErosi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerBenErosi.setForeground(new java.awt.Color(0, 0, 0));
        chkSerBenErosi.setText("Erosi");
        chkSerBenErosi.setBorderPainted(true);
        chkSerBenErosi.setBorderPaintedFlat(true);
        chkSerBenErosi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerBenErosi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerBenErosi.setName("chkSerBenErosi"); // NOI18N
        chkSerBenErosi.setOpaque(false);
        chkSerBenErosi.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerBenErosi);
        chkSerBenErosi.setBounds(276, 206, 50, 23);

        chkSerBenPolip.setBackground(new java.awt.Color(255, 255, 250));
        chkSerBenPolip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerBenPolip.setForeground(new java.awt.Color(0, 0, 0));
        chkSerBenPolip.setText("Polip");
        chkSerBenPolip.setBorderPainted(true);
        chkSerBenPolip.setBorderPaintedFlat(true);
        chkSerBenPolip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerBenPolip.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerBenPolip.setName("chkSerBenPolip"); // NOI18N
        chkSerBenPolip.setOpaque(false);
        chkSerBenPolip.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerBenPolip);
        chkSerBenPolip.setBounds(335, 206, 55, 23);

        chkSerBenEktro.setBackground(new java.awt.Color(255, 255, 250));
        chkSerBenEktro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerBenEktro.setForeground(new java.awt.Color(0, 0, 0));
        chkSerBenEktro.setText("Ektropion");
        chkSerBenEktro.setBorderPainted(true);
        chkSerBenEktro.setBorderPaintedFlat(true);
        chkSerBenEktro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerBenEktro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerBenEktro.setName("chkSerBenEktro"); // NOI18N
        chkSerBenEktro.setOpaque(false);
        chkSerBenEktro.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerBenEktro);
        chkSerBenEktro.setBounds(397, 206, 80, 23);

        jLabel374.setForeground(new java.awt.Color(0, 0, 0));
        jLabel374.setText("Bentuk :");
        jLabel374.setName("jLabel374"); // NOI18N
        FormInput.add(jLabel374);
        jLabel374.setBounds(125, 206, 70, 23);

        jLabel375.setForeground(new java.awt.Color(0, 0, 0));
        jLabel375.setText("Warna :");
        jLabel375.setName("jLabel375"); // NOI18N
        FormInput.add(jLabel375);
        jLabel375.setBounds(125, 234, 70, 23);

        chkSerWarNormal.setBackground(new java.awt.Color(255, 255, 250));
        chkSerWarNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerWarNormal.setForeground(new java.awt.Color(0, 0, 0));
        chkSerWarNormal.setText("Normal");
        chkSerWarNormal.setBorderPainted(true);
        chkSerWarNormal.setBorderPaintedFlat(true);
        chkSerWarNormal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerWarNormal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerWarNormal.setName("chkSerWarNormal"); // NOI18N
        chkSerWarNormal.setOpaque(false);
        chkSerWarNormal.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerWarNormal);
        chkSerWarNormal.setBounds(200, 234, 65, 23);

        chkSerWarHiperemis.setBackground(new java.awt.Color(255, 255, 250));
        chkSerWarHiperemis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerWarHiperemis.setForeground(new java.awt.Color(0, 0, 0));
        chkSerWarHiperemis.setText("Hiperemis");
        chkSerWarHiperemis.setBorderPainted(true);
        chkSerWarHiperemis.setBorderPaintedFlat(true);
        chkSerWarHiperemis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerWarHiperemis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerWarHiperemis.setName("chkSerWarHiperemis"); // NOI18N
        chkSerWarHiperemis.setOpaque(false);
        chkSerWarHiperemis.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerWarHiperemis);
        chkSerWarHiperemis.setBounds(276, 234, 75, 23);

        chkSerWarPucat.setBackground(new java.awt.Color(255, 255, 250));
        chkSerWarPucat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerWarPucat.setForeground(new java.awt.Color(0, 0, 0));
        chkSerWarPucat.setText("Pucat");
        chkSerWarPucat.setBorderPainted(true);
        chkSerWarPucat.setBorderPaintedFlat(true);
        chkSerWarPucat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerWarPucat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerWarPucat.setName("chkSerWarPucat"); // NOI18N
        chkSerWarPucat.setOpaque(false);
        chkSerWarPucat.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerWarPucat);
        chkSerWarPucat.setBounds(359, 234, 55, 23);

        jLabel376.setForeground(new java.awt.Color(0, 0, 0));
        jLabel376.setText("Permukaan :");
        jLabel376.setName("jLabel376"); // NOI18N
        FormInput.add(jLabel376);
        jLabel376.setBounds(125, 262, 70, 23);

        chkSerPerHalus.setBackground(new java.awt.Color(255, 255, 250));
        chkSerPerHalus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerPerHalus.setForeground(new java.awt.Color(0, 0, 0));
        chkSerPerHalus.setText("Halus");
        chkSerPerHalus.setBorderPainted(true);
        chkSerPerHalus.setBorderPaintedFlat(true);
        chkSerPerHalus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerPerHalus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerPerHalus.setName("chkSerPerHalus"); // NOI18N
        chkSerPerHalus.setOpaque(false);
        chkSerPerHalus.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerPerHalus);
        chkSerPerHalus.setBounds(200, 262, 65, 23);

        chkSerPerGran.setBackground(new java.awt.Color(255, 255, 250));
        chkSerPerGran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerPerGran.setForeground(new java.awt.Color(0, 0, 0));
        chkSerPerGran.setText("Granulasi");
        chkSerPerGran.setBorderPainted(true);
        chkSerPerGran.setBorderPaintedFlat(true);
        chkSerPerGran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerPerGran.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerPerGran.setName("chkSerPerGran"); // NOI18N
        chkSerPerGran.setOpaque(false);
        chkSerPerGran.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerPerGran);
        chkSerPerGran.setBounds(276, 262, 75, 23);

        chkSerPerUlser.setBackground(new java.awt.Color(255, 255, 250));
        chkSerPerUlser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 250)));
        chkSerPerUlser.setForeground(new java.awt.Color(0, 0, 0));
        chkSerPerUlser.setText("Ulserasi");
        chkSerPerUlser.setBorderPainted(true);
        chkSerPerUlser.setBorderPaintedFlat(true);
        chkSerPerUlser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSerPerUlser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSerPerUlser.setName("chkSerPerUlser"); // NOI18N
        chkSerPerUlser.setOpaque(false);
        chkSerPerUlser.setPreferredSize(new java.awt.Dimension(175, 23));
        FormInput.add(chkSerPerUlser);
        chkSerPerUlser.setBounds(359, 262, 70, 23);

        jLabel377.setForeground(new java.awt.Color(0, 0, 0));
        jLabel377.setText("Sekret Serviks :");
        jLabel377.setName("jLabel377"); // NOI18N
        FormInput.add(jLabel377);
        jLabel377.setBounds(0, 290, 120, 23);

        cmbJmlSek.setBackground(new java.awt.Color(245, 253, 240));
        cmbJmlSek.setForeground(new java.awt.Color(0, 0, 0));
        cmbJmlSek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Sedikit", "Sedang", "Banyak" }));
        cmbJmlSek.setLightWeightPopupEnabled(false);
        cmbJmlSek.setName("cmbJmlSek"); // NOI18N
        FormInput.add(cmbJmlSek);
        cmbJmlSek.setBounds(617, 150, 70, 23);

        cmbSekServikAda.setBackground(new java.awt.Color(245, 253, 240));
        cmbSekServikAda.setForeground(new java.awt.Color(0, 0, 0));
        cmbSekServikAda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Jernih", "Keruh", "Bernanah", "Berdarah" }));
        cmbSekServikAda.setLightWeightPopupEnabled(false);
        cmbSekServikAda.setName("cmbSekServikAda"); // NOI18N
        FormInput.add(cmbSekServikAda);
        cmbSekServikAda.setBounds(213, 290, 80, 23);

        jLabel378.setForeground(new java.awt.Color(0, 0, 0));
        jLabel378.setText("Temuan Tambahan :");
        jLabel378.setName("jLabel378"); // NOI18N
        FormInput.add(jLabel378);
        jLabel378.setBounds(0, 318, 120, 23);

        Ttemuan.setForeground(new java.awt.Color(0, 0, 0));
        Ttemuan.setName("Ttemuan"); // NOI18N
        FormInput.add(Ttemuan);
        Ttemuan.setBounds(125, 318, 600, 23);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (norawat.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih dulu data pasiennya ....!!");
        } else {
            cekData();
            if (Sequel.menyimpantf("inspeksi_ginekologi_awal_kebidanan", "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", "inspeksi pemeriksaan ginekologi", 47, new String[]{
                norawat, vulvaNormal, vulvaHiperemis, vulvaEdema, vulvaAdaLesi, vulvaMasa, labiaSimetris, labiaTdkSimetris, labiaAdaLuka, labiaAdaBenjolan, klitorisNormal,
                klitorisHipertrofi, klitorisLainya, TketKliLain.getText(), perineumUtuh, perineumAdaLuka, perineumBekas, perineumFistula, introitusNormal, introitusAdaSekret,
                introitusAdaPerdarahan, introitusAdaRobekan, sekretTdkAda, sekretJernih, sekretPutih, sekretKuning, sekretBerbau, cmbJmlSek.getSelectedItem().toString(),
                dindingNormal, dindingHiperemis, dindingAtrofi, dindingAdaMasa, dindingAdaSekret, serviksBentukNormal, serviksBentukErosi, serviksBentukPolip, serviksBentukEktropion,
                serviksWarnaNormal, serviksWarnaHiperemis, serviksWarnaPucat, serviksPermuHalus, serviksPermuGranulasi, serviksPermuUlserasi, cmbSekServik.getSelectedItem().toString(),
                cmbSekServikAda.getSelectedItem().toString(), Ttemuan.getText(), Sequel.cariIsi("select now()")
            }) == true) {
                dispose();
            }
        }
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGantiActionPerformed
        if (norawat.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih dulu data pasiennya ....!!");
        } else {
            cekData();
            if (Sequel.mengedittf("inspeksi_ginekologi_awal_kebidanan", "no_rawat=?", "vulva_normal=?, vulva_hiperemis=?, vulva_edema=?, vulva_ada_lesi=?, vulva_masa=?, "
                    + "labia_simetris=?, labia_tdk_simetris=?, labia_ada_luka=?, labia_ada_benjolan=?, klitoris_normal=?, klitoris_hipertrofi=?, klitoris_lainya=?, "
                    + "ket_klitoris_lain=?, perineum_utuh=?, perineum_ada_luka=?, perineum_bekas=?, perineum_fistula=?, introitus_normal=?, introitus_ada_sekret=?, "
                    + "introitus_ada_perdarahan=?, introitus_ada_robekan=?, sekret_tdk_ada=?, sekret_jernih=?, sekret_putih=?, sekret_kuning=?, sekret_berbau=?, "
                    + "jumlah_sekret=?, dinding_normal=?, dinding_hiperemis=?, dinding_atrofi=?, dinding_ada_masa=?, dinding_ada_sekret=?, serviks_bentuk_normal=?, "
                    + "serviks_bentuk_erosi=?, serviks_bentuk_polip=?, serviks_bentuk_ektropion=?, serviks_warna_normal=?, serviks_warna_hiperemis=?, serviks_warna_pucat=?, "
                    + "serviks_permu_halus=?, serviks_permu_granulasi=?, serviks_permu_ulserasi=?, sekret_serviks=?, sekret_serviks_ada=?, temuan_tambahan=?", 46, new String[]{
                        vulvaNormal, vulvaHiperemis, vulvaEdema, vulvaAdaLesi, vulvaMasa, labiaSimetris, labiaTdkSimetris, labiaAdaLuka, labiaAdaBenjolan, klitorisNormal,
                        klitorisHipertrofi, klitorisLainya, TketKliLain.getText(), perineumUtuh, perineumAdaLuka, perineumBekas, perineumFistula, introitusNormal, introitusAdaSekret,
                        introitusAdaPerdarahan, introitusAdaRobekan, sekretTdkAda, sekretJernih, sekretPutih, sekretKuning, sekretBerbau, cmbJmlSek.getSelectedItem().toString(),
                        dindingNormal, dindingHiperemis, dindingAtrofi, dindingAdaMasa, dindingAdaSekret, serviksBentukNormal, serviksBentukErosi, serviksBentukPolip, serviksBentukEktropion,
                        serviksWarnaNormal, serviksWarnaHiperemis, serviksWarnaPucat, serviksPermuHalus, serviksPermuGranulasi, serviksPermuUlserasi, cmbSekServik.getSelectedItem().toString(),
                        cmbSekServikAda.getSelectedItem().toString(), Ttemuan.getText(), norawat
                    }) == true) {
                JOptionPane.showMessageDialog(rootPane, "Data inspeksi pemeriksaan ginekologi pasien ini berhasil diperbaiki ....!!");
                dispose();
            }
        }
}//GEN-LAST:event_BtnGantiActionPerformed

    private void BtnGantiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGantiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnGantiActionPerformed(null);
        }
}//GEN-LAST:event_BtnGantiKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void chkKliLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKliLainActionPerformed
        TketKliLain.setText("");
        if (chkKliLain.isSelected() == true) {
            TketKliLain.setEnabled(true);
            TketKliLain.requestFocus();
        } else {
            TketKliLain.setEnabled(false);
        }
    }//GEN-LAST:event_chkKliLainActionPerformed

    private void cmbSekServikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSekServikActionPerformed
        cmbSekServikAda.setSelectedIndex(0);
        if (cmbSekServik.getSelectedIndex() == 1) {
            cmbSekServikAda.setEnabled(true);
            cmbSekServikAda.requestFocus();
        } else {
            cmbSekServikAda.setEnabled(false);
        }
    }//GEN-LAST:event_cmbSekServikActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (norawat.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih dulu data pasiennya ....!!");
        } else {
            x = JOptionPane.showConfirmDialog(rootPane, "Yakin data inspeksi pemeriksaan ginekologi mau dihapus..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                if (Sequel.queryu2tf("delete from inspeksi_ginekologi_awal_kebidanan where no_rawat=?", 1, new String[]{norawat}) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Data inspeksi pemeriksaan ginekologi pasien ini berhasil dihapus ....!!");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus..!!");
                }
            }
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnHapusActionPerformed(null);
        }
    }//GEN-LAST:event_BtnHapusKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMInspeksiPemeriksaanGinekologi dialog = new RMInspeksiPemeriksaanGinekologi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public widget.Button BtnGanti;
    public widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    public widget.Button BtnSimpan;
    private widget.PanelBiasa FormInput;
    private widget.TextBox TketKliLain;
    private widget.TextBox Ttemuan;
    public widget.CekBox chkDinAdaMasa;
    public widget.CekBox chkDinAdaSekret;
    public widget.CekBox chkDinAtrofi;
    public widget.CekBox chkDinHiperemis;
    public widget.CekBox chkDinNormal;
    public widget.CekBox chkIntroAdaPerdarahan;
    public widget.CekBox chkIntroAdaRobek;
    public widget.CekBox chkIntroAdaSekret;
    public widget.CekBox chkIntroNormal;
    public widget.CekBox chkKliHiper;
    public widget.CekBox chkKliLain;
    public widget.CekBox chkKliNormal;
    public widget.CekBox chkLabAdaBenjol;
    public widget.CekBox chkLabAdaLuka;
    public widget.CekBox chkLabSimetris;
    public widget.CekBox chkLabTdkSimetris;
    public widget.CekBox chkPerAdaLuka;
    public widget.CekBox chkPerBekas;
    public widget.CekBox chkPerFistula;
    public widget.CekBox chkPerUtuh;
    public widget.CekBox chkSekBerbau;
    public widget.CekBox chkSekJernih;
    public widget.CekBox chkSekKuning;
    public widget.CekBox chkSekPutih;
    public widget.CekBox chkSekTdkAda;
    public widget.CekBox chkSerBenEktro;
    public widget.CekBox chkSerBenErosi;
    public widget.CekBox chkSerBenNormal;
    public widget.CekBox chkSerBenPolip;
    public widget.CekBox chkSerPerGran;
    public widget.CekBox chkSerPerHalus;
    public widget.CekBox chkSerPerUlser;
    public widget.CekBox chkSerWarHiperemis;
    public widget.CekBox chkSerWarNormal;
    public widget.CekBox chkSerWarPucat;
    public widget.CekBox chkVulAdaLesi;
    public widget.CekBox chkVulEdema;
    public widget.CekBox chkVulHiperemis;
    public widget.CekBox chkVulMasa;
    public widget.CekBox chkVulNormal;
    private widget.ComboBox cmbJmlSek;
    private widget.ComboBox cmbSekServik;
    private widget.ComboBox cmbSekServikAda;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel365;
    private widget.Label jLabel366;
    private widget.Label jLabel367;
    private widget.Label jLabel368;
    private widget.Label jLabel369;
    private widget.Label jLabel370;
    private widget.Label jLabel371;
    private widget.Label jLabel372;
    private widget.Label jLabel373;
    private widget.Label jLabel374;
    private widget.Label jLabel375;
    private widget.Label jLabel376;
    private widget.Label jLabel377;
    private widget.Label jLabel378;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

    public void emptTeks() {
        chkVulNormal.setSelected(false);
        chkVulHiperemis.setSelected(false);
        chkVulEdema.setSelected(false);
        chkVulAdaLesi.setSelected(false);
        chkVulMasa.setSelected(false);
        chkLabSimetris.setSelected(false);
        chkLabTdkSimetris.setSelected(false);
        chkLabAdaLuka.setSelected(false);
        chkLabAdaBenjol.setSelected(false);
        chkKliNormal.setSelected(false);
        chkKliHiper.setSelected(false);
        chkKliLain.setSelected(false);
        TketKliLain.setEnabled(false);
        TketKliLain.setText("");
        chkPerUtuh.setSelected(false);
        chkPerAdaLuka.setSelected(false);
        chkPerBekas.setSelected(false);
        chkPerFistula.setSelected(false);
        chkIntroNormal.setSelected(false);
        chkIntroAdaSekret.setSelected(false);
        chkIntroAdaPerdarahan.setSelected(false);
        chkIntroAdaRobek.setSelected(false);
        chkSekTdkAda.setSelected(false);
        chkSekJernih.setSelected(false);
        chkSekPutih.setSelected(false);
        chkSekKuning.setSelected(false);
        chkSekBerbau.setSelected(false);
        cmbJmlSek.setSelectedIndex(0);
        chkDinNormal.setSelected(false);
        chkDinHiperemis.setSelected(false);
        chkDinAtrofi.setSelected(false);
        chkDinAdaMasa.setSelected(false);
        chkDinAdaSekret.setSelected(false);
        chkSerBenNormal.setSelected(false);
        chkSerBenErosi.setSelected(false);
        chkSerBenPolip.setSelected(false);
        chkSerBenEktro.setSelected(false);
        chkSerWarNormal.setSelected(false);
        chkSerWarHiperemis.setSelected(false);
        chkSerWarPucat.setSelected(false);
        chkSerPerHalus.setSelected(false);
        chkSerPerGran.setSelected(false);
        chkSerPerUlser.setSelected(false);
        cmbSekServik.setSelectedIndex(0);
        cmbSekServikAda.setSelectedIndex(0);
        cmbSekServikAda.setEnabled(false);
        Ttemuan.setText("");
    }

    private void cekData() {
        if (chkVulNormal.isSelected() == true) {
            vulvaNormal = "ya";
        } else {
            vulvaNormal = "tidak";
        }

        if (chkVulHiperemis.isSelected() == true) {
            vulvaHiperemis = "ya";
        } else {
            vulvaHiperemis = "tidak";
        }

        if (chkVulEdema.isSelected() == true) {
            vulvaEdema = "ya";
        } else {
            vulvaEdema = "tidak";
        }

        if (chkVulAdaLesi.isSelected() == true) {
            vulvaAdaLesi = "ya";
        } else {
            vulvaAdaLesi = "tidak";
        }

        if (chkVulMasa.isSelected() == true) {
            vulvaMasa = "ya";
        } else {
            vulvaMasa = "tidak";
        }

        if (chkLabSimetris.isSelected() == true) {
            labiaSimetris = "ya";
        } else {
            labiaSimetris = "tidak";
        }

        if (chkLabTdkSimetris.isSelected() == true) {
            labiaTdkSimetris = "ya";
        } else {
            labiaTdkSimetris = "tidak";
        }

        if (chkLabAdaLuka.isSelected() == true) {
            labiaAdaLuka = "ya";
        } else {
            labiaAdaLuka = "tidak";
        }
        
        if (chkLabAdaBenjol.isSelected() == true) {
            labiaAdaBenjolan = "ya";
        } else {
            labiaAdaBenjolan = "tidak";
        }
        
        if (chkKliNormal.isSelected() == true) {
            klitorisNormal = "ya";
        } else {
            klitorisNormal = "tidak";
        }
        
        if (chkKliHiper.isSelected() == true) {
            klitorisHipertrofi = "ya";
        } else {
            klitorisHipertrofi = "tidak";
        }
        
        if (chkKliLain.isSelected() == true) {
            klitorisLainya = "ya";
        } else {
            klitorisLainya = "tidak";
        }
        
        if (chkPerUtuh.isSelected() == true) {
            perineumUtuh = "ya";
        } else {
            perineumUtuh = "tidak";
        }
        
        if (chkPerAdaLuka.isSelected() == true) {
            perineumAdaLuka = "ya";
        } else {
            perineumAdaLuka = "tidak";
        }
        
        if (chkPerBekas.isSelected() == true) {
            perineumBekas = "ya";
        } else {
            perineumBekas = "tidak";
        }
        
        if (chkPerFistula.isSelected() == true) {
            perineumFistula = "ya";
        } else {
            perineumFistula = "tidak";
        }
        
        if (chkIntroNormal.isSelected() == true) {
            introitusNormal = "ya";
        } else {
            introitusNormal = "tidak";
        }
        
        if (chkIntroAdaSekret.isSelected() == true) {
            introitusAdaSekret = "ya";
        } else {
            introitusAdaSekret = "tidak";
        }
        
        if (chkIntroAdaPerdarahan.isSelected() == true) {
            introitusAdaPerdarahan = "ya";
        } else {
            introitusAdaPerdarahan = "tidak";
        }
        
        if (chkIntroAdaRobek.isSelected() == true) {
            introitusAdaRobekan = "ya";
        } else {
            introitusAdaRobekan = "tidak";
        }
        
        if (chkSekTdkAda.isSelected() == true) {
            sekretTdkAda = "ya";
        } else {
            sekretTdkAda = "tidak";
        }
        
        if (chkSekJernih.isSelected() == true) {
            sekretJernih = "ya";
        } else {
            sekretJernih = "tidak";
        }
        
        if (chkSekPutih.isSelected() == true) {
            sekretPutih = "ya";
        } else {
            sekretPutih = "tidak";
        }
        
        if (chkSekKuning.isSelected() == true) {
            sekretKuning = "ya";
        } else {
            sekretKuning = "tidak";
        }
        
        if (chkSekBerbau.isSelected() == true) {
            sekretBerbau = "ya";
        } else {
            sekretBerbau = "tidak";
        }
        
        if (chkDinNormal.isSelected() == true) {
            dindingNormal = "ya";
        } else {
            dindingNormal = "tidak";
        }
        
        if (chkDinHiperemis.isSelected() == true) {
            dindingHiperemis = "ya";
        } else {
            dindingHiperemis = "tidak";
        }
        
        if (chkDinAtrofi.isSelected() == true) {
            dindingAtrofi = "ya";
        } else {
            dindingAtrofi = "tidak";
        }
        
        if (chkDinAdaMasa.isSelected() == true) {
            dindingAdaMasa = "ya";
        } else {
            dindingAdaMasa = "tidak";
        }
        
        if (chkDinAdaSekret.isSelected() == true) {
            dindingAdaSekret = "ya";
        } else {
            dindingAdaSekret = "tidak";
        }
        
        if (chkSerBenNormal.isSelected() == true) {
            serviksBentukNormal = "ya";
        } else {
            serviksBentukNormal = "tidak";
        }
        
        if (chkSerBenErosi.isSelected() == true) {
            serviksBentukErosi = "ya";
        } else {
            serviksBentukErosi = "tidak";
        }
        
        if (chkSerBenPolip.isSelected() == true) {
            serviksBentukPolip = "ya";
        } else {
            serviksBentukPolip = "tidak";
        }
        
        if (chkSerBenEktro.isSelected() == true) {
            serviksBentukEktropion = "ya";
        } else {
            serviksBentukEktropion = "tidak";
        }
        
        if (chkSerWarNormal.isSelected() == true) {
            serviksWarnaNormal = "ya";
        } else {
            serviksWarnaNormal = "tidak";
        }
        
        if (chkSerWarHiperemis.isSelected() == true) {
            serviksWarnaHiperemis = "ya";
        } else {
            serviksWarnaHiperemis = "tidak";
        }
        
        if (chkSerWarPucat.isSelected() == true) {
            serviksWarnaPucat = "ya";
        } else {
            serviksWarnaPucat = "tidak";
        }
        
        if (chkSerPerHalus.isSelected() == true) {
            serviksPermuHalus = "ya";
        } else {
            serviksPermuHalus = "tidak";
        }
        
        if (chkSerPerGran.isSelected() == true) {
            serviksPermuGranulasi = "ya";
        } else {
            serviksPermuGranulasi = "tidak";
        }
        
        if (chkSerPerUlser.isSelected() == true) {
            serviksPermuUlserasi = "ya";
        } else {
            serviksPermuUlserasi = "tidak";
        }
    }
    
    private void dataCek() {
        if (vulvaNormal.equals("ya")) {
            chkVulNormal.setSelected(true);
        } else {
            chkVulNormal.setSelected(false);
        }
        
        if (vulvaHiperemis.equals("ya")) {
            chkVulHiperemis.setSelected(true);
        } else {
            chkVulHiperemis.setSelected(false);
        }
        
        if (vulvaEdema.equals("ya")) {
            chkVulEdema.setSelected(true);
        } else {
            chkVulEdema.setSelected(false);
        }
        
        if (vulvaAdaLesi.equals("ya")) {
            chkVulAdaLesi.setSelected(true);
        } else {
            chkVulAdaLesi.setSelected(false);
        }
        
        if (vulvaMasa.equals("ya")) {
            chkVulMasa.setSelected(true);
        } else {
            chkVulMasa.setSelected(false);
        }
        
        if (labiaSimetris.equals("ya")) {
            chkLabSimetris.setSelected(true);
        } else {
            chkLabSimetris.setSelected(false);
        }
        
        if (labiaTdkSimetris.equals("ya")) {
            chkLabTdkSimetris.setSelected(true);
        } else {
            chkLabTdkSimetris.setSelected(false);
        }
        
        if (labiaAdaLuka.equals("ya")) {
            chkLabAdaLuka.setSelected(true);
        } else {
            chkLabAdaLuka.setSelected(false);
        }
        
        if (labiaAdaBenjolan.equals("ya")) {
            chkLabAdaBenjol.setSelected(true);
        } else {
            chkLabAdaBenjol.setSelected(false);
        }
        
        if (klitorisNormal.equals("ya")) {
            chkKliNormal.setSelected(true);
        } else {
            chkKliNormal.setSelected(false);
        }
        
        if (klitorisHipertrofi.equals("ya")) {
            chkKliHiper.setSelected(true);
        } else {
            chkKliHiper.setSelected(false);
        }
        
        if (klitorisLainya.equals("ya")) {
            chkKliLain.setSelected(true);
            TketKliLain.setEnabled(true);
        } else {
            chkKliLain.setSelected(false);
            TketKliLain.setEnabled(false);
        }
        
        if (perineumUtuh.equals("ya")) {
            chkPerUtuh.setSelected(true);
        } else {
            chkPerUtuh.setSelected(false);
        }
        
        if (perineumAdaLuka.equals("ya")) {
            chkPerAdaLuka.setSelected(true);
        } else {
            chkPerAdaLuka.setSelected(false);
        }
        
        if (perineumBekas.equals("ya")) {
            chkPerBekas.setSelected(true);
        } else {
            chkPerBekas.setSelected(false);
        }
        
        if (perineumFistula.equals("ya")) {
            chkPerFistula.setSelected(true);
        } else {
            chkPerFistula.setSelected(false);
        }
        
        if (introitusNormal.equals("ya")) {
            chkIntroNormal.setSelected(true);
        } else {
            chkIntroNormal.setSelected(false);
        }
        
        if (introitusAdaSekret.equals("ya")) {
            chkIntroAdaSekret.setSelected(true);
        } else {
            chkIntroAdaSekret.setSelected(false);
        }
        
        if (introitusAdaPerdarahan.equals("ya")) {
            chkIntroAdaPerdarahan.setSelected(true);
        } else {
            chkIntroAdaPerdarahan.setSelected(false);
        }
        
        if (introitusAdaRobekan.equals("ya")) {
            chkIntroAdaRobek.setSelected(true);
        } else {
            chkIntroAdaRobek.setSelected(false);
        }
        
        if (sekretTdkAda.equals("ya")) {
            chkSekTdkAda.setSelected(true);
        } else {
            chkSekTdkAda.setSelected(false);
        }
        
        if (sekretJernih.equals("ya")) {
            chkSekJernih.setSelected(true);
        } else {
            chkSekJernih.setSelected(false);
        }
        
        if (sekretPutih.equals("ya")) {
            chkSekPutih.setSelected(true);
        } else {
            chkSekPutih.setSelected(false);
        }
        
        if (sekretKuning.equals("ya")) {
            chkSekKuning.setSelected(true);
        } else {
            chkSekKuning.setSelected(false);
        }
        
        if (sekretBerbau.equals("ya")) {
            chkSekBerbau.setSelected(true);
        } else {
            chkSekBerbau.setSelected(false);
        }
        
        if (dindingNormal.equals("ya")) {
            chkDinNormal.setSelected(true);
        } else {
            chkDinNormal.setSelected(false);
        }
        
        if (dindingHiperemis.equals("ya")) {
            chkDinHiperemis.setSelected(true);
        } else {
            chkDinHiperemis.setSelected(false);
        }
        
        if (dindingAtrofi.equals("ya")) {
            chkDinAtrofi.setSelected(true);
        } else {
            chkDinAtrofi.setSelected(false);
        }
        
        if (dindingAdaMasa.equals("ya")) {
            chkDinAdaMasa.setSelected(true);
        } else {
            chkDinAdaMasa.setSelected(false);
        }
        
        if (dindingAdaSekret.equals("ya")) {
            chkDinAdaSekret.setSelected(true);
        } else {
            chkDinAdaSekret.setSelected(false);
        }
        
        if (serviksBentukNormal.equals("ya")) {
            chkSerBenNormal.setSelected(true);
        } else {
            chkSerBenNormal.setSelected(false);
        }
        
        if (serviksBentukErosi.equals("ya")) {
            chkSerBenErosi.setSelected(true);
        } else {
            chkSerBenErosi.setSelected(false);
        }
        
        if (serviksBentukPolip.equals("ya")) {
            chkSerBenPolip.setSelected(true);
        } else {
            chkSerBenPolip.setSelected(false);
        }
        
        if (serviksBentukEktropion.equals("ya")) {
            chkSerBenEktro.setSelected(true);
        } else {
            chkSerBenEktro.setSelected(false);
        }
        
        if (serviksWarnaNormal.equals("ya")) {
            chkSerWarNormal.setSelected(true);
        } else {
            chkSerWarNormal.setSelected(false);
        }
        
        if (serviksWarnaHiperemis.equals("ya")) {
            chkSerWarHiperemis.setSelected(true);
        } else {
            chkSerWarHiperemis.setSelected(false);
        }
        
        if (serviksWarnaPucat.equals("ya")) {
            chkSerWarPucat.setSelected(true);
        } else {
            chkSerWarPucat.setSelected(false);
        }
        
        if (serviksPermuHalus.equals("ya")) {
            chkSerPerHalus.setSelected(true);
        } else {
            chkSerPerHalus.setSelected(false);
        }
        
        if (serviksPermuGranulasi.equals("ya")) {
            chkSerPerGran.setSelected(true);
        } else {
            chkSerPerGran.setSelected(false);
        }
        
        if (serviksPermuUlserasi.equals("ya")) {
            chkSerPerUlser.setSelected(true);
        } else {
            chkSerPerUlser.setSelected(false);
        }
        
        if (cmbSekServik.getSelectedIndex() == 1) {
            cmbSekServikAda.setEnabled(true);
        } else {
            cmbSekServikAda.setEnabled(false);
        }
    }
    
    public void setData(String norw) {
        norawat = norw;
    }
    
    public void tampil() {
        try {
            ps = koneksi.prepareStatement("select * from inspeksi_ginekologi_awal_kebidanan where no_rawat='" + norawat + "'");
            try {
                rs = ps.executeQuery();
                while (rs.next()) {
                    vulvaNormal = rs.getString("vulva_normal");
                    vulvaHiperemis = rs.getString("vulva_hiperemis");
                    vulvaEdema = rs.getString("vulva_edema");
                    vulvaAdaLesi = rs.getString("vulva_ada_lesi");
                    vulvaMasa = rs.getString("vulva_masa");
                    
                    labiaSimetris = rs.getString("labia_simetris");
                    labiaTdkSimetris = rs.getString("labia_tdk_simetris");
                    labiaAdaLuka = rs.getString("labia_ada_luka");
                    labiaAdaBenjolan = rs.getString("labia_ada_benjolan");
                    
                    klitorisNormal = rs.getString("klitoris_normal");
                    klitorisHipertrofi = rs.getString("klitoris_hipertrofi");
                    klitorisLainya = rs.getString("klitoris_lainya");
                    TketKliLain.setText(rs.getString("ket_klitoris_lain"));
                    
                    perineumUtuh = rs.getString("perineum_utuh");
                    perineumAdaLuka = rs.getString("perineum_ada_luka");
                    perineumBekas = rs.getString("perineum_bekas");
                    perineumFistula = rs.getString("perineum_fistula");
                    
                    introitusNormal = rs.getString("introitus_normal");
                    introitusAdaSekret = rs.getString("introitus_ada_sekret");
                    introitusAdaPerdarahan = rs.getString("introitus_ada_perdarahan");
                    introitusAdaRobekan = rs.getString("introitus_ada_robekan");
                    
                    sekretTdkAda = rs.getString("sekret_tdk_ada");
                    sekretJernih = rs.getString("sekret_jernih");
                    sekretPutih = rs.getString("sekret_putih");
                    sekretKuning = rs.getString("sekret_kuning");
                    sekretBerbau = rs.getString("sekret_berbau");
                    cmbJmlSek.setSelectedItem(rs.getString("jumlah_sekret").toString());
                    
                    dindingNormal = rs.getString("dinding_normal");
                    dindingHiperemis = rs.getString("dinding_hiperemis");
                    dindingAtrofi = rs.getString("dinding_atrofi");
                    dindingAdaMasa = rs.getString("dinding_ada_masa");
                    dindingAdaSekret = rs.getString("dinding_ada_sekret");
                    
                    serviksBentukNormal = rs.getString("serviks_bentuk_normal");
                    serviksBentukErosi = rs.getString("serviks_bentuk_erosi");
                    serviksBentukPolip = rs.getString("serviks_bentuk_polip");
                    serviksBentukEktropion = rs.getString("serviks_bentuk_ektropion");
                    
                    serviksWarnaNormal = rs.getString("serviks_warna_normal");
                    serviksWarnaHiperemis = rs.getString("serviks_warna_hiperemis");
                    serviksWarnaPucat = rs.getString("serviks_warna_pucat");
                    
                    serviksPermuHalus = rs.getString("serviks_permu_halus");
                    serviksPermuGranulasi = rs.getString("serviks_permu_granulasi");
                    serviksPermuUlserasi = rs.getString("serviks_permu_ulserasi");
                    
                    cmbSekServik.setSelectedItem(rs.getString("sekret_serviks").toString());
                    cmbSekServikAda.setSelectedItem(rs.getString("sekret_serviks_ada").toString());
                    Ttemuan.setText(rs.getString("temuan_tambahan"));
                    dataCek();
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
    }
}
