package laporan;

import bridging.ApiWhatapp;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public class DlgKirimWhatsapp extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private PreparedStatement ps;
    private ApiWhatapp wa = new ApiWhatapp();
    private ResultSet rs;
    private int i = 0;
    private String nmDokumen = "", norawat = "", waktuSimpan = "";
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgKirimWhatsapp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        
        TnoWa.setDocument(new batasInput((byte) 13).getOnlyAngka(TnoWa));
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        PanelInput = new javax.swing.JPanel();
        FormInput = new widget.PanelBiasa();
        jLabel55 = new widget.Label();
        TPesan = new widget.TextBox();
        jLabel56 = new widget.Label();
        TnoWa = new widget.TextBox();
        jLabel57 = new widget.Label();
        TnmFile = new widget.TextBox();
        panelGlass8 = new widget.panelisi();
        BtnKirimWA = new widget.Button();
        BtnCloseIn = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Kirim Hasil Pemeriksaan Lab. Patologi Anatomi Ke WhatsApp Tujuan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setWarnaAtas(new java.awt.Color(204, 255, 204));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(192, 95));
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(190, 107));
        FormInput.setWarnaAtas(new java.awt.Color(204, 255, 204));
        FormInput.setLayout(null);

        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Pesan : ");
        jLabel55.setName("jLabel55"); // NOI18N
        FormInput.add(jLabel55);
        jLabel55.setBounds(0, 10, 135, 23);

        TPesan.setForeground(new java.awt.Color(0, 0, 0));
        TPesan.setName("TPesan"); // NOI18N
        FormInput.add(TPesan);
        TPesan.setBounds(135, 10, 640, 23);

        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("No. WhatsApp Tujuan : ");
        jLabel56.setName("jLabel56"); // NOI18N
        FormInput.add(jLabel56);
        jLabel56.setBounds(0, 38, 135, 23);

        TnoWa.setForeground(new java.awt.Color(0, 0, 0));
        TnoWa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TnoWa.setName("TnoWa"); // NOI18N
        FormInput.add(TnoWa);
        TnoWa.setBounds(135, 38, 160, 23);

        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Nama File  : ");
        jLabel57.setName("jLabel57"); // NOI18N
        FormInput.add(jLabel57);
        jLabel57.setBounds(0, 66, 135, 23);

        TnmFile.setEditable(false);
        TnmFile.setForeground(new java.awt.Color(0, 0, 0));
        TnmFile.setName("TnmFile"); // NOI18N
        FormInput.add(TnmFile);
        TnmFile.setBounds(135, 66, 430, 23);

        PanelInput.add(FormInput, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 48));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        BtnKirimWA.setForeground(new java.awt.Color(0, 0, 0));
        BtnKirimWA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/whatsapp.png"))); // NOI18N
        BtnKirimWA.setText("Kirim Ke Nomor WA Tujuan");
        BtnKirimWA.setGlassColor(new java.awt.Color(153, 255, 153));
        BtnKirimWA.setName("BtnKirimWA"); // NOI18N
        BtnKirimWA.setPreferredSize(new java.awt.Dimension(200, 30));
        BtnKirimWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimWAActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnKirimWA);

        BtnCloseIn.setForeground(new java.awt.Color(0, 0, 0));
        BtnCloseIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnCloseIn.setMnemonic('U');
        BtnCloseIn.setText("Keluar");
        BtnCloseIn.setToolTipText("Alt+U");
        BtnCloseIn.setName("BtnCloseIn"); // NOI18N
        BtnCloseIn.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCloseIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseInActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnCloseIn);

        PanelInput.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKirimWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimWAActionPerformed
        if (TPesan.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf, pesan tidak boleh dikosongkan, jika tidak ada isi dengan -  ");
            TPesan.requestFocus();
        } else if (TnoWa.getText().equals("") || TnoWa.getText().length() <= 10) {
            JOptionPane.showMessageDialog(rootPane, "Maaf, nomor whatsapp tujuan kurang jumlah digit angkanya..!");
            TPesan.requestFocus();
        } else {
            if (wa.ngirimTeks(TPesan.getText(), TnoWa.getText()) == true) {
                String filePath = Sequel.cariFolderTte() + File.separator + TnmFile.getText() + ".pdf";
                String base64String = sekuel.convertPdfToBase64(filePath);
         
                if (base64String != null) {
                    if (wa.ngirimFile(TnoWa.getText(), TnmFile.getText(), base64String) == true) {
                        Sequel.hapusIisiFolder(Sequel.cariFolderTte() + File.separator);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Proses mengirim data gagal, silahkan ulangi lagi..!");
                        dispose();
                    }                    
                } else {
                    System.out.println("Gagal mengubah file PDF menjadi data Base64.");
                }
            }
        }
    }//GEN-LAST:event_BtnKirimWAActionPerformed

    private void BtnCloseInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseInActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCloseInActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgKirimWhatsapp dialog = new DlgKirimWhatsapp(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCloseIn;
    private widget.Button BtnKirimWA;
    private widget.PanelBiasa FormInput;
    private javax.swing.JPanel PanelInput;
    private widget.TextBox TPesan;
    private widget.TextBox TnmFile;
    private widget.TextBox TnoWa;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel55;
    private widget.Label jLabel56;
    private widget.Label jLabel57;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

    public void emptTeks() {  
        TPesan.setText("");
        TnoWa.setText("");
        TnmFile.setText("");
        TnoWa.requestFocus();
    }
    
    public void setData(String jnsDokumen, String norw, String wktSimpan) {
        nmDokumen = jnsDokumen;
        norawat = norw;
        waktuSimpan = wktSimpan;
        dataKirim();
    }
    
    private void dataKirim() {
        if (nmDokumen.equals("hasil patologi anatomi")) {
            try {
                ps = koneksi.prepareStatement("select hp.*, p.no_rkm_medis, p.nm_pasien, p.tgl_lahir, p.jk, pg1.nama drPengirim, p.no_tlp, "
                        + "ifnull(d.no_ijn_praktek,'-') nosip, pg2.nama drPatologi, date_format(hp.waktu_simpan,'%d/%m/%Y') tgl, time(hp.waktu_simpan) jam "
                        + "from hasil_patologi_anatomi hp inner join reg_periksa rp on rp.no_rawat=hp.no_rawat "
                        + "inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis inner join pegawai pg1 on pg1.nik=hp.nip_perujuk "
                        + "inner join pegawai pg2 on pg2.nik=hp.nip_dokter_pa left join dokter d on d.kd_dokter=hp.nip_dokter_pa "
                        + "where hp.waktu_simpan='" + waktuSimpan + "'");
                try {
                    rs = ps.executeQuery();
                    while (rs.next()) {
                        Map<String, Object> param = new HashMap<>();
                        param.put("namars", akses.getnamars());
                        param.put("alamatrs", akses.getalamatrs());
                        param.put("kotars", akses.getkabupatenrs());
                        param.put("propinsirs", akses.getpropinsirs());
                        param.put("kontakrs", akses.getkontakrs());
                        param.put("emailrs", akses.getemailrs());
                        param.put("logo", Sequel.cariGambar("select logo from setting"));
                        
                        param.put("noPA", rs.getString("no_pa"));
                        param.put("norm", rs.getString("no_rkm_medis"));
                        param.put("nmpasien", rs.getString("nm_pasien"));
                        param.put("tgllahir", Valid.SetTglINDONESIA(rs.getString("tgl_lahir")));
                        param.put("jenkel", rs.getString("jk").replaceAll("L", "Laki-laki").replaceAll("P", "Perempuan"));
                        param.put("drPengirim", rs.getString("drPengirim"));
                        param.put("unit", rs.getString("nm_unit"));
                        param.put("tglperiksa", Valid.SetTglINDONESIA(rs.getString("tgl_periksa")));
                        param.put("tglhasil", Valid.SetTglINDONESIA(rs.getString("tgl_hasil")));
                        param.put("lokasi", rs.getString("lokasi_organ") + "\n");
                        param.put("makros", rs.getString("makroskopik").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                        param.put("italicmakros", rs.getString("italic_makroskopik"));
                        param.put("mikros", rs.getString("mikroskopik").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                        param.put("italicmikros", rs.getString("italic_mikroskopik"));
                        param.put("kesimpulan", rs.getString("kesimpulan").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                        param.put("italickesimpulan", rs.getString("italic_kesimpulan"));
                        param.put("anjuran", rs.getString("anjuran").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                        param.put("italicanjuran", rs.getString("italic_anjuran"));
                        param.put("sip", rs.getString("nosip"));
                        param.put("nmDokterpa", rs.getString("drPatologi"));

                        try {
                            String gambarnya = "", ipGambarnya = "";
                            try {
                                //cek atau ping ip addres
                                ipGambarnya = "192.168.0.230";
                                InetAddress inet = InetAddress.getByName(ipGambarnya);

                                //ping sukses timeout 100 ms (0.1 detik)
                                if (inet.isReachable(100)) {
                                    if (rs.getString("kd_gambar").equals("")) {
                                        gambarnya = "http://192.168.0.230:7183/img-rme/gambar_tidak_ditemukan.jpg";
                                    } else {
                                        gambarnya = "http://192.168.0.230:7183/rme/download.php?id=" + rs.getString("kd_gambar");
                                    }
                                    //ping gagal
                                } else {
                                    gambarnya = "https://raw.githubusercontent.com/bibing-raza/gambar_online/main/gambar_tidak_ditemukan.jpg";
                                }
                            } catch (Exception e) {
                                System.out.println("Notif : " + e);
                                gambarnya = "https://raw.githubusercontent.com/bibing-raza/gambar_online/main/gambar_tidak_ditemukan.jpg";
                            }

                            param.put("gambarPA", gambarnya);
                        } catch (Exception e) {
                            System.out.println("Notifikasi : " + e);
                        }

                        String isi = "", nmFile = "";
                        nmFile = rs.getString("no_rawat").replaceAll("/", "") + rs.getString("tgl_hasil").replaceAll("-", "");
                        isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                                + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='006'"),
                                        "Hasil Pemeriksaan Lab. (Patologi Anatomi)", rs.getString("drPatologi"),
                                        rs.getString("tgl"), rs.getString("jam")) + "') from kalimat_tte where kode='006'");

                        Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
                        Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
                        Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Lab. Patologi Anatomi", Sequel.cariFolderPrintTte());
                        param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
                        param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='006'"));
                        Valid.MyReportToPDF("rptPeriksaPatologiAnatomiQr.jasper", "report", "::[ Lembar Hasil Pemeriksaan Patologi Anatomi ]::", "SELECT now() tgl",
                                param, Sequel.cariFolderTte(), nmFile);
                        
                        TPesan.setText("Hasil Pemeriksaan Lab. Patologi Anatomi " + akses.getnamars());
                        TnoWa.setText(rs.getString("no_tlp"));
                        TnmFile.setText(nmFile);
                        TnoWa.requestFocus();
                    }
                } catch (Exception e) {
                    System.out.println("Notifikasi : " + e);
                } finally {
                    if (rs != null) {
                        rs.close();
                    }
                    if (ps != null) {
                        ps.close();
                    }
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            }
        }
    }
}
