package laporan;

import bridging.ApiWhatapp;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public class DlgKirimWhatsapp extends javax.swing.JDialog {
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Properties prop = new Properties();
    private PreparedStatement ps, ps1, ps2, ps3, ps4, ps5;
    private ResultSet rs, rs1, rs2, rs3, rs4, rs5;
    private ApiWhatapp wa = new ApiWhatapp();    
    private int i = 0, jmlNota = 0;
    private double ttl = 0, item = 0;
    private String nmDokumen = "", norawat = "", waktuSimpan = "", cekPiutang = "", crbyr = "", isi = "", nmFile = "",
            judulReport = "", judulBanyak = "", judulTunggal = "", tanggal = "", nmPemberiJT = "", noTelpJT = "", jmlNominalJT = "",
            namaPasJT = "", norkmJT = "", noPanjarP = "", keterP = "", notelpP = "", sttsP = "", angkaNomP = "", userP = "", nmpetgs = "";
    
    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgKirimWhatsapp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        
        TnoWa.setDocument(new batasInput((byte) 13).getOnlyAngka(TnoWa));
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        PanelInput = new javax.swing.JPanel();
        FormInput = new widget.PanelBiasa();
        jLabel55 = new widget.Label();
        TPesan = new widget.TextBox();
        jLabel56 = new widget.Label();
        TnoWa = new widget.TextBox();
        jLabel57 = new widget.Label();
        TnmFile = new widget.TextBox();
        panelGlass8 = new widget.panelisi();
        BtnKirimWA = new widget.Button();
        BtnCloseIn = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Kirim File PDF Ke Nomor WhatsApp Tujuan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setWarnaAtas(new java.awt.Color(204, 255, 204));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(192, 95));
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(190, 107));
        FormInput.setWarnaAtas(new java.awt.Color(204, 255, 204));
        FormInput.setLayout(null);

        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Pesan : ");
        jLabel55.setName("jLabel55"); // NOI18N
        FormInput.add(jLabel55);
        jLabel55.setBounds(0, 10, 135, 23);

        TPesan.setForeground(new java.awt.Color(0, 0, 0));
        TPesan.setName("TPesan"); // NOI18N
        FormInput.add(TPesan);
        TPesan.setBounds(135, 10, 640, 23);

        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("No. WhatsApp Tujuan : ");
        jLabel56.setName("jLabel56"); // NOI18N
        FormInput.add(jLabel56);
        jLabel56.setBounds(0, 38, 135, 23);

        TnoWa.setForeground(new java.awt.Color(0, 0, 0));
        TnoWa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TnoWa.setName("TnoWa"); // NOI18N
        FormInput.add(TnoWa);
        TnoWa.setBounds(135, 38, 160, 23);

        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Nama File  : ");
        jLabel57.setName("jLabel57"); // NOI18N
        FormInput.add(jLabel57);
        jLabel57.setBounds(0, 66, 135, 23);

        TnmFile.setEditable(false);
        TnmFile.setForeground(new java.awt.Color(0, 0, 0));
        TnmFile.setName("TnmFile"); // NOI18N
        FormInput.add(TnmFile);
        TnmFile.setBounds(135, 66, 360, 23);

        PanelInput.add(FormInput, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 48));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        BtnKirimWA.setForeground(new java.awt.Color(0, 0, 0));
        BtnKirimWA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/whatsapp.png"))); // NOI18N
        BtnKirimWA.setText("Kirim Ke Nomor WA Tujuan");
        BtnKirimWA.setGlassColor(new java.awt.Color(153, 255, 153));
        BtnKirimWA.setName("BtnKirimWA"); // NOI18N
        BtnKirimWA.setPreferredSize(new java.awt.Dimension(200, 30));
        BtnKirimWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimWAActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnKirimWA);

        BtnCloseIn.setForeground(new java.awt.Color(0, 0, 0));
        BtnCloseIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnCloseIn.setMnemonic('U');
        BtnCloseIn.setText("Keluar");
        BtnCloseIn.setToolTipText("Alt+U");
        BtnCloseIn.setName("BtnCloseIn"); // NOI18N
        BtnCloseIn.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCloseIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseInActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnCloseIn);

        PanelInput.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKirimWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimWAActionPerformed
        if (TPesan.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf, pesan tidak boleh dikosongkan, jika tidak ada isi dengan -  ");
            TPesan.requestFocus();
        } else if (TnoWa.getText().equals("") || TnoWa.getText().length() <= 10) {
            JOptionPane.showMessageDialog(rootPane, "Maaf, nomor whatsapp tujuan kurang jumlah digit angkanya..!");
            TPesan.requestFocus();
        } else {
            if (wa.ngirimTeks(TPesan.getText(), TnoWa.getText()) == true) {
                String filePath = Sequel.cariFolderTte() + File.separator + TnmFile.getText() + ".pdf";
                String base64String = sekuel.convertPdfToBase64(filePath);
         
                if (base64String != null) {
                    if (wa.ngirimFile(TnoWa.getText(), TnmFile.getText(), base64String) == true) {
                        Sequel.hapusIisiFolder(Sequel.cariFolderTte() + File.separator);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Proses mengirim data gagal, silahkan ulangi lagi..!");
                        dispose();
                    }                    
                } else {
                    System.out.println("Gagal mengubah file PDF menjadi data Base64.");
                }
            }
        }
    }//GEN-LAST:event_BtnKirimWAActionPerformed

    private void BtnCloseInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseInActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCloseInActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgKirimWhatsapp dialog = new DlgKirimWhatsapp(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCloseIn;
    private widget.Button BtnKirimWA;
    private widget.PanelBiasa FormInput;
    private javax.swing.JPanel PanelInput;
    private widget.TextBox TPesan;
    private widget.TextBox TnmFile;
    private widget.TextBox TnoWa;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel55;
    private widget.Label jLabel56;
    private widget.Label jLabel57;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

    public void emptTeks() {  
        TPesan.setText("");
        TnoWa.setText("");
        TnmFile.setText("");
        TnoWa.requestFocus();
    }
    
    public void setData(String jnsDokumen, String norw, String wktSimpan) {
        nmDokumen = jnsDokumen;
        norawat = norw;
        waktuSimpan = wktSimpan;
    }

    public void dataKirim() {        
        if (nmDokumen.equals("hasil patologi anatomi")) {
            hasilPatologiAnatomi();
        } else if (nmDokumen.equals("kasir nota ranap")) {
            if (cekPiutang.equals("tidak")) {
                notaRanap();
            } else if (cekPiutang.equals("ya")) {
                notaRanapPiutang();
            }
        } else if (nmDokumen.equals("kasir kuitansi ranap")) {
            if (cekPiutang.equals("tidak")) {
                kuitansiRanap();
            } else if (cekPiutang.equals("ya")) {
                kuitansiPiutangRanap();
            }
        } else if (nmDokumen.equals("kasir nota ralan")) {
            notaRalan();
        } else if (nmDokumen.equals("kasir kuitansi ralan")) {
            if (cekPiutang.equals("tidak")) {
                kuitansiRalan();
            } else if (cekPiutang.equals("ya")) {
                kuitansiRalanPiutang();
            }
        } else if (nmDokumen.equals("jaminan transaksi")) {
            jaminanTransaksi();
        } else if (nmDokumen.equals("panjar")) {
            panjar();
        } else if (nmDokumen.equals("nota lab")) {
            notaLab();
        } else if (nmDokumen.equals("nota radiologi")) {
            notaRadiologi();
        }
    }
    
    public void setTransaksi(String piutang, String judulnya, String tglnota) {
        cekPiutang = piutang;
        judulReport = judulnya;
        tanggal = tglnota;
    }
    
    public void jaminanTrans(String nmPemberi, String notelp, String jmlnominal, String nmPasien, String norkm, String noPanjar, 
            String ketPanjar, String notelp2, String sttsPanjar, String angkaNomPanjar, String userPanjar) {
        nmPemberiJT = nmPemberi;
        noTelpJT = notelp;
        jmlNominalJT = jmlnominal;
        namaPasJT = nmPasien;
        norkmJT = norkm;
        noPanjarP = noPanjar;
        keterP = ketPanjar;
        notelpP = notelp2;
        sttsP = sttsPanjar;
        angkaNomP = angkaNomPanjar;
        userP = userPanjar;
    }
    
    public void isPiutang(String TtlSemua, String besarppn, String TagihanPPn, String Deposit, String bayar, String kembali, String Piutang) {        
        if (cekPiutang.equals("tidak")) {
            Sequel.menyimpan("temporary_bayar_ranap", "'0','TOTAL TAGIHAN',':','','','','','" + TtlSemua + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','PPN',':','','','','','" + besarppn + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','TAGIHAN+PPN',':','','','','','" + TagihanPPn + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','DEPOSIT',':','','','','','" + Deposit + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','BAYAR',':','','','','','" + bayar + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','Kembali',':','','','','','" + kembali + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
        } else if (cekPiutang.equals("ya")) {
            Sequel.menyimpan("temporary_bayar_ranap", "'0','TOTAL TAGIHAN',':','','','','','" + TtlSemua + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','PPN',':','','','','','" + besarppn + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','TAGIHAN + PPN',':','','','','','" + TagihanPPn + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','DEPOSIT',':','','','','','" + Deposit + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','UANG MUKA',':','','','','','" + bayar + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
            Sequel.menyimpan("temporary_bayar_ranap", "'0','SISA PIUTANG',':','','','','','" + Piutang + "','Tagihan','','','','','','','','',''", "Rekap Harian Tindakan Dokter");
        }
    }

    private void hasilPatologiAnatomi() {
        try {
            ps = koneksi.prepareStatement("select hp.*, p.no_rkm_medis, p.nm_pasien, p.tgl_lahir, p.jk, pg1.nama drPengirim, p.no_tlp, "
                    + "ifnull(d.no_ijn_praktek,'-') nosip, pg2.nama drPatologi, date_format(hp.waktu_simpan,'%d/%m/%Y') tgl, time(hp.waktu_simpan) jam "
                    + "from hasil_patologi_anatomi hp inner join reg_periksa rp on rp.no_rawat=hp.no_rawat "
                    + "inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis inner join pegawai pg1 on pg1.nik=hp.nip_perujuk "
                    + "inner join pegawai pg2 on pg2.nik=hp.nip_dokter_pa left join dokter d on d.kd_dokter=hp.nip_dokter_pa "
                    + "where hp.waktu_simpan='" + waktuSimpan + "'");
            try {
                rs = ps.executeQuery();
                while (rs.next()) {
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars", akses.getnamars());
                    param.put("alamatrs", akses.getalamatrs());
                    param.put("kotars", akses.getkabupatenrs());
                    param.put("propinsirs", akses.getpropinsirs());
                    param.put("kontakrs", akses.getkontakrs());
                    param.put("emailrs", akses.getemailrs());
                    param.put("logo", Sequel.cariGambar("select logo from setting"));

                    param.put("noPA", rs.getString("no_pa"));
                    param.put("norm", rs.getString("no_rkm_medis"));
                    param.put("nmpasien", rs.getString("nm_pasien"));
                    param.put("tgllahir", Valid.SetTglINDONESIA(rs.getString("tgl_lahir")));
                    param.put("jenkel", rs.getString("jk").replaceAll("L", "Laki-laki").replaceAll("P", "Perempuan"));
                    param.put("drPengirim", rs.getString("drPengirim"));
                    param.put("unit", rs.getString("nm_unit"));
                    param.put("tglperiksa", Valid.SetTglINDONESIA(rs.getString("tgl_periksa")));
                    param.put("tglhasil", Valid.SetTglINDONESIA(rs.getString("tgl_hasil")));
                    param.put("lokasi", rs.getString("lokasi_organ") + "\n");
                    param.put("makros", rs.getString("makroskopik").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                    param.put("italicmakros", rs.getString("italic_makroskopik"));
                    param.put("mikros", rs.getString("mikroskopik").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                    param.put("italicmikros", rs.getString("italic_mikroskopik"));
                    param.put("kesimpulan", rs.getString("kesimpulan").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                    param.put("italickesimpulan", rs.getString("italic_kesimpulan"));
                    param.put("anjuran", rs.getString("anjuran").replace("\r\n", "<br/>").replace("\n", "<br/>").replace("\r", "<br/>"));
                    param.put("italicanjuran", rs.getString("italic_anjuran"));
                    param.put("sip", rs.getString("nosip"));
                    param.put("nmDokterpa", rs.getString("drPatologi"));

                    try {
                        String gambarnya = "", ipGambarnya = "";
                        try {
                            //cek atau ping ip addres
                            ipGambarnya = "192.168.0.230";
                            InetAddress inet = InetAddress.getByName(ipGambarnya);

                            //ping sukses timeout 100 ms (0.1 detik)
                            if (inet.isReachable(100)) {
                                if (rs.getString("kd_gambar").equals("")) {
                                    gambarnya = "http://192.168.0.230:7183/img-rme/gambar_tidak_ditemukan.jpg";
                                } else {
                                    gambarnya = "http://192.168.0.230:7183/rme/download.php?id=" + rs.getString("kd_gambar");
                                }
                                //ping gagal
                            } else {
                                gambarnya = "https://raw.githubusercontent.com/bibing-raza/gambar_online/main/gambar_tidak_ditemukan.jpg";
                            }
                        } catch (Exception e) {
                            System.out.println("Notif : " + e);
                            gambarnya = "https://raw.githubusercontent.com/bibing-raza/gambar_online/main/gambar_tidak_ditemukan.jpg";
                        }

                        param.put("gambarPA", gambarnya);
                    } catch (Exception e) {
                        System.out.println("Notifikasi : " + e);
                    }

                    nmFile = rs.getString("no_pa").replaceAll("-", "");
                    isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                            + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='006'"),
                                    "Hasil Pemeriksaan Lab. (Patologi Anatomi)", rs.getString("drPatologi"),
                                    rs.getString("tgl"), rs.getString("jam")) + "') from kalimat_tte where kode='006'");

                    Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
                    Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
                    Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Lab. Patologi Anatomi", Sequel.cariFolderPrintTte());
                    param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
                    param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='006'"));
                    Valid.MyReportToPDF("rptPeriksaPatologiAnatomiQr.jasper", "report", "::[ Lembar Hasil Pemeriksaan Patologi Anatomi ]::", "SELECT now() tgl",
                            param, Sequel.cariFolderTte(), nmFile);

                    TPesan.setText("Hasil Pemeriksaan Lab. Patologi Anatomi " + akses.getnamars());
                    TnoWa.setText(rs.getString("no_tlp"));
                    TnmFile.setText(nmFile);
                    TnoWa.requestFocus();
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
    }
    
    private void notaRanap() {
        crbyr = Sequel.cariIsi("select pj.png_jawab from reg_periksa r inner join penjab pj on pj.kd_pj=r.kd_pj where r.no_rawat='" + norawat + "'");
        nmFile = "Nota Pembayaran " + norawat.replaceAll("/", "");

        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("cara_byr", crbyr);
        param.put("tglNota", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ................... )");
        } else if (akses.getbilling_ranap()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptNotaRanap.jasper", "report", "::[ Nota Pembayaran - LUNAS (Rawat Inap) ]::",
                    "SELECT temp1, temp2, temp3, temp4, temp5, IF(temp6='0','',temp6) temp6, temp7, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='No.Nota' LIMIT 1) no_nota, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Bangsal/Kamar' LIMIT 1) bangsal, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Tgl. Perawatan' LIMIT 1) tgl_rawat, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Pasien' LIMIT 1) pasien, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Alamat Pasien' LIMIT 1) alamat_pasien, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='total tagihan' LIMIT 1) tot_tagihan, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='ppn' LIMIT 1) ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='tagihan+ppn' LIMIT 1) tagihan_ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='deposit' LIMIT 1) deposit, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='bayar' LIMIT 1) bayar, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='kembali' LIMIT 1) kembali FROM temporary_bayar_ranap WHERE "
                    + "temp1 NOT IN ('TOTAL TAGIHAN','TAGIHAN+PPN','PPN','DEPOSIT','BAYAR','Kembali', 'No.Nota','Bangsal/Kamar','Tgl. Perawatan','Pasien','Alamat Pasien')",
                    param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Nota Pembayaran (" + crbyr + ")", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Nota Pembayaran", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptNotaRanapQr.jasper", "report", "::[ Nota Pembayaran - LUNAS (Rawat Inap) ]::",
                    "SELECT temp1, temp2, temp3, temp4, temp5, IF(temp6='0','',temp6) temp6, temp7, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='No.Nota' LIMIT 1) no_nota, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Bangsal/Kamar' LIMIT 1) bangsal, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Tgl. Perawatan' LIMIT 1) tgl_rawat, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Pasien' LIMIT 1) pasien, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Alamat Pasien' LIMIT 1) alamat_pasien, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='total tagihan' LIMIT 1) tot_tagihan, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='ppn' LIMIT 1) ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='tagihan+ppn' LIMIT 1) tagihan_ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='deposit' LIMIT 1) deposit, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='bayar' LIMIT 1) bayar, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='kembali' LIMIT 1) kembali FROM temporary_bayar_ranap WHERE "
                    + "temp1 NOT IN ('TOTAL TAGIHAN','TAGIHAN+PPN','PPN','DEPOSIT','BAYAR','Kembali', 'No.Nota','Bangsal/Kamar','Tgl. Perawatan','Pasien','Alamat Pasien')",
                    param, Sequel.cariFolderTte(), nmFile);
        }

        TPesan.setText("Nota Pembayaran Rawat Inap (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }

    private void notaRanapPiutang() {
        crbyr = Sequel.cariIsi("select pj.png_jawab from reg_periksa r inner join penjab pj on pj.kd_pj=r.kd_pj where r.no_rawat='" + norawat + "'");
        nmFile = "Nota Pembayaran Piutang " + norawat.replaceAll("/", "");
        
        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("cara_byr", crbyr);
        param.put("tglNota", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ................... )");
        } else if (akses.getbilling_ranap()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptNotaRanapPiutang.jasper", "report", "::[ Nota Pembayaran - PIUTANG (Rawat Inap) ]::",
                    "SELECT temp1, temp2, temp3, temp4, temp5, IF(temp6='0','',temp6) temp6, temp7, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='No.Nota' LIMIT 1) no_nota, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Bangsal/Kamar' LIMIT 1) bangsal, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Tgl. Perawatan' LIMIT 1) tgl_rawat, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Pasien' LIMIT 1) pasien, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Alamat Pasien' LIMIT 1) alamat_pasien, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='total tagihan' LIMIT 1) tot_tagihan, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='ppn' LIMIT 1) ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='tagihan + ppn' LIMIT 1) tagihan_ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='deposit' LIMIT 1) deposit, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='uang muka' LIMIT 1) uang_muka, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='sisa piutang' LIMIT 1) sisa_piutang FROM temporary_bayar_ranap WHERE "
                    + "temp1 NOT IN('TOTAL TAGIHAN','TAGIHAN + PPN','PPN','DEPOSIT','UANG MUKA','SISA PIUTANG', 'No.Nota','Bangsal/Kamar','Tgl. Perawatan','Pasien','Alamat Pasien')",
                    param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Nota Pembayaran Piutang (" + crbyr + ")", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Nota Pembayaran", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptNotaRanapPiutangQr.jasper", "report", "::[ Nota Pembayaran - PIUTANG (Rawat Inap) ]::",
                    "SELECT temp1, temp2, temp3, temp4, temp5, IF(temp6='0','',temp6) temp6, temp7, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='No.Nota' LIMIT 1) no_nota, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Bangsal/Kamar' LIMIT 1) bangsal, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Tgl. Perawatan' LIMIT 1) tgl_rawat, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Pasien' LIMIT 1) pasien, "
                    + "(SELECT temp2 FROM temporary_bayar_ranap WHERE temp1='Alamat Pasien' LIMIT 1) alamat_pasien, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='total tagihan' LIMIT 1) tot_tagihan, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='ppn' LIMIT 1) ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='tagihan + ppn' LIMIT 1) tagihan_ppn, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='deposit' LIMIT 1) deposit, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='uang muka' LIMIT 1) uang_muka, "
                    + "(SELECT temp7 FROM temporary_bayar_ranap WHERE temp1='sisa piutang' LIMIT 1) sisa_piutang FROM temporary_bayar_ranap WHERE "
                    + "temp1 NOT IN('TOTAL TAGIHAN','TAGIHAN + PPN','PPN','DEPOSIT','UANG MUKA','SISA PIUTANG', 'No.Nota','Bangsal/Kamar','Tgl. Perawatan','Pasien','Alamat Pasien')",
                    param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Nota Pembayaran Piutang Rawat Inap (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void kuitansiRanap() {
        nmFile = "Kuitansi Pembayaran " + norawat.replaceAll("/", "");
        
        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("no_kwitansi", Sequel.cariIsi("SELECT REPLACE(temp2,': ','') no_kwitansi FROM temporary_bayar_ranap WHERE temp1='No.Nota'"));
        param.put("telah_terima", Sequel.cariIsi("select concat(rp.p_jawab,' (No. Telp./HP. ',p.no_tlp,')') from reg_periksa rp "
                + "inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis where rp.no_rawat='" + norawat + "'"));
        param.put("uang_sebanyak", Sequel.Terbilang(Sequel.cariIsiAngka("SELECT REPLACE(REPLACE(temp7,'.',''),',','') tot_bayar FROM temporary_bayar_ranap WHERE temp1='BAYAR'")) + " Rupiah.");
        param.put("untuk_byr", "Pelayanan Kesehatan Rawat Inap di " + Sequel.cariIsi("select nama_instansi from setting") + " ruang perawatan " + Sequel.cariIsi("select b.nm_bangsal from kamar_inap ki "
                + "inner join kamar k on k.kd_kamar=ki.kd_kamar inner join bangsal b on b.kd_bangsal=k.kd_bangsal where "
                + "ki.no_rawat='" + norawat + "' order by ki.tgl_masuk desc, ki.jam_masuk desc limit 1") + " a/n "
                + Sequel.cariIsi("SELECT REPLACE(temp2,': ','') pasien FROM temporary_bayar_ranap WHERE temp1='Pasien'"));
        param.put("terbilang", Sequel.cariIsi("SELECT concat('Terbilang Rp. ',REPLACE(REPLACE(temp7,'.','.'),',','.')) terbilang FROM temporary_bayar_ranap WHERE temp1='BAYAR'"));
        param.put("tglNota", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ____________________ )");
        } else if (akses.getbilling_ranap()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiRanap.jasper", "report", "::[ Kwitansi Pembayaran - LUNAS (Rawat Inap) ]::",
                    " SELECT * FROM temporary_bayar_ranap ", param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Kuitansi", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiRanapQr.jasper", "report", "::[ Kwitansi Pembayaran - LUNAS (Rawat Inap) ]::",
                    " SELECT * FROM temporary_bayar_ranap ", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Pembayaran Rawat Inap (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }

    private void kuitansiPiutangRanap() {
        nmFile = "Kuitansi Pembayaran Piutang " + norawat.replaceAll("/", "");

        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("no_kwitansi", Sequel.cariIsi("SELECT REPLACE(temp2,': ','') no_kwitansi FROM temporary_bayar_ranap WHERE temp1='No.Nota'"));
        param.put("telah_terima", Sequel.cariIsi("select concat(rp.p_jawab,' (No. Telp./HP. ',p.no_tlp,')') from reg_periksa rp "
                + "inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis where rp.no_rawat='" + norawat + "'"));
        param.put("uang_sebanyak", Sequel.Terbilang(Sequel.cariIsiAngka("SELECT REPLACE(REPLACE(temp7,'.',''),',','') tot_bayar FROM temporary_bayar_ranap WHERE temp1='UANG MUKA'")) + " Rupiah.");
        param.put("untuk_byr", "Pelayanan Kesehatan Rawat Inap di " + Sequel.cariIsi("select nama_instansi from setting") + " a/n "
                + Sequel.cariIsi("SELECT REPLACE(temp2,': ','') pasien FROM temporary_bayar_ranap WHERE temp1='Pasien'") + " sebagai uang muka.");
        param.put("terbilang", Sequel.cariIsi("SELECT concat('Terbilang Rp. ',REPLACE(REPLACE(temp7,'.','.'),',','.')) terbilang FROM temporary_bayar_ranap WHERE temp1='UANG MUKA'"));
        param.put("tglNota", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ____________________ )");
        } else if (akses.getbilling_ranap()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiRanap.jasper", "report", "::[ Kwitansi Pembayaran - PIUTANG (Rawat Inap) ]::",
                    " SELECT * FROM temporary_bayar_ranap ", param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Kuitansi", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiRanapQr.jasper", "report", "::[ Kwitansi Pembayaran - PIUTANG (Rawat Inap) ]::",
                    " SELECT * FROM temporary_bayar_ranap ", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Pembayaran Piutang Rawat Inap (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void notaRalan() {
        jmlNota = 0;
        jmlNota = Sequel.cariInteger("SELECT count(-1) cek FROM temporary_bayar_ralan WHERE temp1='No. Nota'");
        crbyr = Sequel.cariIsi("select p.png_jawab from reg_periksa r inner join penjab p on p.kd_pj=r.kd_pj where r.no_rawat='" + norawat + "'");        

        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("cara_byr", crbyr);
        param.put("tot_bayar", Sequel.cariIsi("select REPLACE(REPLACE(temp7,'.','.'),',','.') from temporary_bayar_ralan where temp1='TOTAL BAYAR'"));
        param.put("tglNota", "Martapura, " + tanggal);

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ................... )");
        } else if (akses.getbilling_ralan()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (judulReport.equals("nota")) {
            param.put("judul", "NOTA PEMBAYARAN (" + crbyr + ")");
            judulBanyak = "::[ Nota Pembayaran Banyak - LUNAS (Rawat Jalan) ]::";
            judulTunggal = "::[ Nota Pembayaran - LUNAS (Rawat Jalan) ]::";
            nmFile = "Nota Pembayaran " + norawat.replaceAll("/", "");
        } else if (judulReport.equals("kwitansi_nota")) {
            param.put("judul", "KUITANSI PEMBAYARAN (" + crbyr + ")");
            judulBanyak = "::[ Kuitansi Pembayaran Banyak - LUNAS (Rawat Jalan) ]::";
            judulTunggal = "::[ Kuitansi Pembayaran - LUNAS (Rawat Jalan) ]::";
            nmFile = "Kuitansi Pembayaran Transaksi " + norawat.replaceAll("/", "");
        }

        if (akses.getadmin() == true) {
            if (jmlNota > 1) {
                Valid.MyReportToPDF("rptNotaRalanBanyak.jasper", "report", judulBanyak,
                        " SELECT temp1, temp2, temp5, temp7 FROM temporary_bayar_ralan WHERE temp1 <> 'TOTAL BAYAR'", param, Sequel.cariFolderTte(), nmFile);
            } else if (jmlNota <= 1) {
                Valid.MyReportToPDF("rptNotaRalan.jasper", "report", judulTunggal,
                        "SELECT temp1, temp2, temp5, temp7 , "
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='No. Nota') no_nota,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Poliklinik/Inst.') poli,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Tanggal & Jam') tgl_jam,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Pasien') pasien,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Alamat Pasien') alamat "
                        + "FROM temporary_bayar_ralan WHERE temp1 not in ('No. Nota','Poliklinik/Inst.','Tanggal & Jam','Pasien','Alamat Pasien')",
                        param, Sequel.cariFolderTte(), nmFile);
            }
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Kuitansi Pembayaran (" + crbyr + ")",
                            Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            if (jmlNota > 1) {
                Valid.MyReportToPDF("rptNotaRalanBanyakQr.jasper", "report", judulBanyak,
                        " SELECT temp1, temp2, temp5, temp7 FROM temporary_bayar_ralan WHERE temp1 <> 'TOTAL BAYAR'", param, Sequel.cariFolderTte(), nmFile);
            } else if (jmlNota <= 1) {
                Valid.MyReportToPDF("rptNotaRalanQr.jasper", "report", judulTunggal,
                        "SELECT temp1, temp2, temp5, temp7 , "
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='No. Nota') no_nota,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Poliklinik/Inst.') poli,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Tanggal & Jam') tgl_jam,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Pasien') pasien,"
                        + "(SELECT REPLACE(temp2,': ','') FROM temporary_bayar_ralan WHERE temp1='Alamat Pasien') alamat "
                        + "FROM temporary_bayar_ralan WHERE temp1 not in ('No. Nota','Poliklinik/Inst.','Tanggal & Jam','Pasien','Alamat Pasien')",
                        param, Sequel.cariFolderTte(), nmFile);
            }
        }
        
        TPesan.setText("Nota Pembayaran Rawat Jalan (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void kuitansiRalan() {
        nmFile = "Kuitansi Pembayaran " + norawat.replaceAll("/", "");
        
        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("no_kwitansi", Sequel.cariIsi("SELECT REPLACE(temp2,': ','') no_nota FROM temporary_bayar_ralan WHERE temp1='No. Nota'"));
        param.put("telah_terima", Sequel.cariIsi("select p_jawab from reg_periksa where no_rawat='" + norawat + "'"));
        param.put("uang_sebanyak", Sequel.Terbilang(Sequel.cariIsiAngka("SELECT REPLACE(REPLACE(temp7,'.',''),',','') tot_bayar FROM temporary_bayar_ralan WHERE temp1='TOTAL BAYAR'")) + " Rupiah.");
        param.put("untuk_byr", "Pelayanan Kesehatan Rawat Jalan di " + Sequel.cariIsi("select nama_instansi from setting") + " a/n "
                + Sequel.cariIsi("SELECT REPLACE(temp2,': ','') pasien FROM temporary_bayar_ralan WHERE temp1='Pasien'"));
        param.put("terbilang", Sequel.cariIsi("SELECT concat('Terbilang Rp. ',REPLACE(REPLACE(temp7,'.','.'),',','.')) terbilang FROM temporary_bayar_ralan WHERE temp1='TOTAL BAYAR'"));
        param.put("tglNota", "Martapura, " + tanggal);

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ____________________ )");
        } else if (akses.getbilling_ralan()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiRalan.jasper", "report", "::[ Kwitansi Pembayaran - LUNAS (Rawat Jalan) ]::",
                    " SELECT * FROM temporary_bayar_ralan ", param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "KUITANSI", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiRalanQr.jasper", "report", "::[ Kwitansi Pembayaran - LUNAS (Rawat Jalan) ]::",
                    " SELECT * FROM temporary_bayar_ralan ", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Pembayaran Rawat Jalan (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void kuitansiRalanPiutang() {
        nmFile = "Kuitansi Pembayaran Piutang " + norawat.replaceAll("/", "");
        
        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("no_kwitansi", Sequel.cariIsi("SELECT REPLACE(temp2,': ','') no_nota FROM temporary_bayar_ralan WHERE temp1='No. Nota'"));
        param.put("telah_terima", Sequel.cariIsi("select p_jawab from reg_periksa where no_rawat='" + norawat + "'"));
        param.put("uang_sebanyak", Sequel.Terbilang(Sequel.cariIsiAngka("SELECT REPLACE(REPLACE(temp7,'.',''),',','') tot_bayar FROM temporary_bayar_ralan WHERE temp1='UANG MUKA'")) + " Rupiah.");
        param.put("untuk_byr", "Pelayanan Kesehatan Rawat Jalan di " + Sequel.cariIsi("select nama_instansi from setting") + " a/n "
                + Sequel.cariIsi("SELECT REPLACE(temp2,': ','') pasien FROM temporary_bayar_ralan WHERE temp1='Pasien'") + " sebagai uang muka.");
        param.put("terbilang", Sequel.cariIsi("SELECT concat('Terbilang Rp. ',REPLACE(REPLACE(temp7,'.','.'),',','.')) terbilang FROM temporary_bayar_ralan WHERE temp1='UANG MUKA'"));
        param.put("tglNota", "Martapura, " + tanggal);

        if (akses.getadmin() == true) {
            param.put("petugas_ksr", "( ____________________ )");
        } else if (akses.getbilling_ralan()) {
            param.put("petugas_ksr", "( " + Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'") + " )");
        }

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiRalanPiutang.jasper", "report", "::[ Kwitansi Pembayaran - PIUTANG (Rawat Jalan) ]::",
                    " SELECT * FROM temporary_bayar_ralan ", param, Sequel.cariFolderTte(), nmFile);
        } else {
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "KUITANSI", Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'"),
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiRalanPiutangQr.jasper", "report", "::[ Kwitansi Pembayaran - PIUTANG (Rawat Jalan) ]::",
                    " SELECT * FROM temporary_bayar_ralan ", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Pembayaran Piutang Rawat Jalan (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }

    private void jaminanTransaksi() {
        String user = "";
        nmFile = "Kuitansi Pembayaran Jaminan " + norawat.replaceAll("/", "");

        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("kontakrs", akses.getkontakrs());
        param.put("emailrs", akses.getemailrs());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("no_kwitansi", norawat);
        param.put("telah_terima", nmPemberiJT + " (No. Telp./HP. " + noTelpJT + ")");
        param.put("uang_sebanyak", Sequel.Terbilang(Double.parseDouble(jmlNominalJT)) + " Rupiah.");
        param.put("untuk_byr", "Jaminan transaksi pelayanan Kesehatan Rawat Inap di " + Sequel.cariIsi("select nama_instansi from setting") + " ruang perawatan\n"
                + Sequel.cariIsi("select b.nm_bangsal from kamar_inap ki inner join kamar k on k.kd_kamar=ki.kd_kamar inner join bangsal b on b.kd_bangsal=k.kd_bangsal where "
                        + "ki.no_rawat='" + norawat + "' order by ki.tgl_masuk desc, ki.jam_masuk desc limit 1") + " a.n " + namaPasJT + " (No. RM : " + norkmJT + ")");
        param.put("terbilang", "Terbilang Rp. " + Valid.SetAngka(Double.parseDouble(jmlNominalJT)).replaceAll(",", "."));
        param.put("tglNota", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (akses.getadmin() == true) {
            user = "____________________";
        } else if (akses.getbilling_ranap()) {
            user = Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'");
        }

        param.put("petugas_ksr", "( " + user + " )");

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiJaminan.jasper", "report", "::[ Kwitansi Jaminan Transaksi (Rawat Inap) ]::",
                    "SELECT now() tgl", param, Sequel.cariFolderTte(), nmFile);
        } else {
            String isi = "";
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Kuitansi Jaminan", user, Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiJaminanQr.jasper", "report", "::[ Kwitansi Jaminan Transaksi (Rawat Inap) ]::",
                    "SELECT now() tgl", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Jaminan (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void panjar() {
        String user = "";
        nmFile = "Kuitansi Pembayaran Panjar " + norawat.replaceAll("/", "");

        Map<String, Object> param = new HashMap<>();
        param.put("namars", akses.getnamars());
        param.put("logo", Sequel.cariGambar("select logo from setting"));
        param.put("alamatrs", akses.getalamatrs());
        param.put("kotars", akses.getkabupatenrs());
        param.put("propinsirs", akses.getpropinsirs());
        param.put("emailrs", akses.getemailrs());
        param.put("norm", norkmJT);
        param.put("nmpasien", namaPasJT);
        param.put("nopanjar", noPanjarP);
        param.put("telahTerima", nmPemberiJT);
        param.put("keterangan", keterP + "\nNo. Hp/Telp. yang bisa dihubungi " + noTelpJT + " / " + notelpP);
        param.put("tanggal", "Martapura, " + Valid.SetTglINDONESIA(waktuSimpan));

        if (sttsP.equals("Kurang Bayar") || sttsP.equals("Lebih Bayar")) {
            param.put("terbilang", Sequel.Terbilang(Double.parseDouble(jmlNominalJT)).toUpperCase() + " RUPIAH");
            param.put("nominal", angkaNomP.replaceAll(",", "."));
            user = userP.toString();
        } else {
            param.put("terbilang", Sequel.Terbilang(Double.parseDouble(jmlNominalJT)).toUpperCase() + " RUPIAH");
            param.put("nominal", angkaNomP.replaceAll(",", "."));
            user = userP.toString();
        }

        param.put("petugas", "(" + user + ")");

        if (akses.getadmin() == true) {
            Valid.MyReportToPDF("rptKwitansiPanjar.jasper", "report", "::[ Kuitansi Transaksi Panjar ]::",
                    "SELECT now() tanggal", param, Sequel.cariFolderTte(), nmFile);
        } else {
            String isi = "";
            isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                    + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                            "Kuitansi Pembayaran Panjar", user,
                            Sequel.cariIsi("select date_format('" + waktuSimpan + "','%d/%m/%Y')"),
                            Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

            Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
            Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
            Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Kuitansi", Sequel.cariFolderPrintTte());
            param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
            param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

            Valid.MyReportToPDF("rptKwitansiPanjarQr.jasper", "report", "::[ Kuitansi Transaksi Panjar ]::",
                    "SELECT now() tanggal", param, Sequel.cariFolderTte(), nmFile);
        }
        
        TPesan.setText("Kuitansi Panjar (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
        TnoWa.setText("");
        TnmFile.setText(nmFile);
        TnoWa.requestFocus();
    }
    
    private void notaLab() {
        try {
            StringBuilder sb1 = new StringBuilder();
            sb1.append("SELECT pl.no_rawat, IFNULL(lr.no_lab,'-') no_lab, rp.no_rkm_medis, p.nm_pasien, CONCAT(rp.umurdaftar,' ',rp.sttsumur,'.') AS umur_thn, ");
            sb1.append("pt.nama, pl.tgl_periksa, pl.jam, pl.dokter_perujuk, pl.kd_dokter, d.nm_dokter,IF(ifnull(h.no_lab,'-')='-','Belum','Sudah') hasil, rp.kd_pj, pj.png_jawab, ");
            sb1.append("CASE WHEN rp.kd_pj='U01' THEN IF(COUNT(bl.no_rawat) > 0, 'Sudah Lunas', 'Belum Bayar') ");
            sb1.append("ELSE IF(COUNT(pp.no_rawat) > 0, 'Piutang', 'Transaksi Belum Selesai') END cekBayar ");
            sb1.append("FROM periksa_lab pl INNER JOIN reg_periksa rp on rp.no_rawat=pl.no_rawat INNER JOIN pasien p on p.no_rkm_medis=rp.no_rkm_medis ");
            sb1.append("INNER JOIN petugas pt on pt.nip=pl.nip INNER JOIN dokter d on d.kd_dokter=pl.kd_dokter INNER JOIN penjab pj on pj.kd_pj=rp.kd_pj ");
            sb1.append("LEFT JOIN lis_reg lr on lr.no_rawat=pl.no_rawat and lr.tgl_periksa=pl.tgl_periksa AND lr.jam_periksa=pl.jam ");
            sb1.append("left join lis_hasil_periksa_lab h on h.no_lab = lr.no_lab LEFT JOIN billing bl ON bl.no_rawat=pl.no_rawat LEFT JOIN piutang_pasien pp ON pp.no_rawat=pl.no_rawat WHERE ");
            sb1.append("pl.tgl_periksa BETWEEN '" + Valid.SetTgl(namaPasJT) + "' AND '" + Valid.SetTgl(norkmJT) + "' AND (" + noPanjarP + ") ");
            sb1.append("GROUP BY concat(pl.no_rawat, pl.tgl_periksa, pl.jam) " + keterP + " order by pl.tgl_periksa desc, pl.jam desc");
            ps1 = koneksi.prepareStatement(sb1.toString());

            StringBuilder sb2 = new StringBuilder();
            sb2.append("SELECT jpl.kd_jenis_prw, jpl.nm_perawatan, pl.biaya FROM periksa_lab pl ");
            sb2.append("INNER JOIN jns_perawatan_lab jpl ON jpl.kd_jenis_prw=pl.kd_jenis_prw WHERE pl.no_rawat =? AND pl.tgl_periksa =? AND pl.jam =?");
            ps2 = koneksi.prepareStatement(sb2.toString());

            StringBuilder sb3 = new StringBuilder();
            sb3.append("SELECT tl.Pemeriksaan, dpl.nilai, tl.satuan, dpl.nilai_rujukan, dpl.biaya_item, dpl.keterangan, ");
            sb3.append("dpl.kd_jenis_prw FROM detail_periksa_lab dpl INNER JOIN template_laboratorium tl ON tl.id_template=dpl.id_template ");
            sb3.append("WHERE dpl.no_rawat =? AND dpl.kd_jenis_prw =? AND dpl.tgl_periksa =? AND dpl.jam =?");
            ps3 = koneksi.prepareStatement(sb3.toString());

            StringBuilder sb4 = new StringBuilder();
            sb4.append("SELECT pl.no_rawat, IFNULL(lr.no_lab,'-') no_lab, rp.no_rkm_medis, p.nm_pasien, p.jk, p.umur, pt.nama, ");
            sb4.append("DATE_FORMAT(pl.tgl_periksa,'%d-%m-%Y') AS tgl_periksa, pl.jam, pl.dokter_perujuk, pl.kd_dokter, p.alamat, d.nm_dokter, ");
            sb4.append("DATE_FORMAT(p.tgl_lahir,'%d-%m-%Y') AS lahir FROM periksa_lab pl INNER JOIN reg_periksa rp on rp.no_rawat=pl.no_rawat ");
            sb4.append("INNER JOIN pasien p ON p.no_rkm_medis=rp.no_rkm_medis INNER JOIN petugas pt ON pt.nip=pl.nip INNER JOIN dokter d ON d.kd_dokter=pl.kd_dokter ");
            sb4.append("LEFT JOIN lis_reg lr on lr.no_rawat=pl.no_rawat and lr.tgl_periksa=pl.tgl_periksa AND lr.jam_periksa=pl.jam ");
            sb4.append("WHERE pl.tgl_periksa =? AND pl.jam =? AND pl.no_rawat =? GROUP BY concat(pl.no_rawat, pl.tgl_periksa, pl.jam)");
            ps4 = koneksi.prepareStatement(sb4.toString());

        } catch (Exception e) {
            System.out.println(e);
        }
       
        try {
            Sequel.AutoComitFalse();
            ps4.setString(1, nmPemberiJT);
            ps4.setString(2, noTelpJT);
            ps4.setString(3, norawat);
            rs = ps4.executeQuery();
            if (rs.next()) {
                Sequel.queryu("delete from temporary");
                ps2.setString(1, rs.getString("no_rawat"));
                ps2.setString(2, Valid.SetTgl(rs.getString("tgl_periksa")));
                ps2.setString(3, rs.getString("jam"));
                rs2 = ps2.executeQuery();
                ttl = 0;
                while (rs2.next()) {
                    item = rs2.getDouble("biaya");//Sequel.cariIsiAngka("select sum(biaya_item) from template_laboratorium where kd_jenis_prw=?",rs2.getString("kd_jenis_prw"));
                    ttl = ttl + item;
                    Sequel.menyimpan("temporary", "'0','" + rs2.getString("kd_jenis_prw") + "','" + rs2.getString("nm_perawatan") + "','','Pemeriksaan','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Transaksi Biaya Lab");
                    ps3.setString(1, rs.getString("no_rawat"));
                    ps3.setString(2, rs2.getString("kd_jenis_prw"));
                    ps3.setString(3, Valid.SetTgl(rs.getString("tgl_periksa")));
                    ps3.setString(4, rs.getString("jam"));
                    rs3 = ps3.executeQuery();
                    while (rs3.next()) {
                        item = rs3.getDouble("biaya_item");
                        ttl = ttl + item;
                        Sequel.menyimpan("temporary", "'0','" + rs3.getString("kd_jenis_prw") + "','   " + rs3.getString("Pemeriksaan") + "','" + item + "','Detail Pemeriksaan','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Transaksi Biaya Lab");
                    }
                }
                Sequel.menyimpan("temporary", "'0','','Total Biaya Pemeriksaan Lab','" + ttl + "','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Transaksi Biaya Lab");
                
                //proses data ke nota pdf
                crbyr = Sequel.cariIsi("select p.png_jawab from reg_periksa r inner join penjab p on p.kd_pj=r.kd_pj where r.no_rawat='" + norawat + "'");
                nmFile = "Nota Transaksi Laboratorium " + norawat.replaceAll("/", "");

                Map<String, Object> param = new HashMap<>();
                param.put("namars", akses.getnamars());
                param.put("alamatrs", akses.getalamatrs());
                param.put("kotars", akses.getkabupatenrs());
                param.put("propinsirs", akses.getpropinsirs());
                param.put("kontakrs", akses.getkontakrs());
                param.put("emailrs", akses.getemailrs());
                param.put("logo", Sequel.cariGambar("select logo from setting"));
                param.put("norm", Sequel.cariIsi("select p.no_rkm_medis from reg_periksa r inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'"));
                param.put("nmpasien", Sequel.cariIsi("select p.nm_pasien from reg_periksa r inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'"));
                param.put("tglPeriksa", nmPemberiJT + ", Pukul : " + noTelpJT);
                param.put("drLab", jmlNominalJT);
                param.put("cara_byr", crbyr);
                param.put("tglNota", "Martapura, " + waktuSimpan);

                if (akses.getadmin() == true) {
                    nmpetgs = "...................";
                } else {
                    nmpetgs = Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'");
                }

                param.put("petugas_ksr", "( " + nmpetgs + " )");

                if (akses.getadmin() == true) {
                    Valid.MyReportToPDF("rptNotaLaboratorium.jasper", "report", "::[ Nota Transaksi Laboratorium ]::",
                            "SELECT temp2, IF(FORMAT(temp3,0)='0','',FORMAT(temp3,0)) biaya, (select FORMAT(temp3,0) from temporary where "
                            + "temp2='Total Biaya Pemeriksaan Lab') tot_byr FROM temporary WHERE temp2 not LIKE '%biaya%'", param, Sequel.cariFolderTte(), nmFile);
                } else {
                    isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                            + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                                    "Nota Transaksi Laboratorium (" + crbyr + ")", nmpetgs,
                                    Sequel.cariIsi("select date_format('" + Valid.SetTgl(waktuSimpan + "") + "','%d/%m/%Y')"),
                                    Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

                    Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
                    Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
                    Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Nota Transaksi Lab.", Sequel.cariFolderPrintTte());
                    param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
                    param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

                    Valid.MyReportToPDF("rptNotaLaboratoriumQr.jasper", "report", "::[ Nota Transaksi Laboratorium ]::",
                            " SELECT temp2, IF(FORMAT(temp3,0)='0','',FORMAT(temp3,0)) biaya, (select FORMAT(temp3,0) from temporary where "
                            + "temp2='Total Biaya Pemeriksaan Lab') tot_byr FROM temporary WHERE temp2 not LIKE '%biaya%'", param, Sequel.cariFolderTte(), nmFile);
                }

                TPesan.setText("Nota Pembayaran Pemeriksaan Laboratorium (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                        + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
                TnoWa.setText("");
                TnmFile.setText(nmFile);
                TnoWa.requestFocus();
                //------------------------------------------
            }
            Sequel.AutoComitTrue();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void notaRadiologi() {
        try {
            if (sttsP.equals("ya")) {
                StringBuilder sb1 = new StringBuilder();
                sb1.append("select pr.no_rawat, rp.no_rkm_medis, p.nm_pasien, CONCAT(rp.umurdaftar,' ',rp.sttsumur) as umur_thn, pt.nama, pr.tgl_periksa, pr.jam, ");
                sb1.append("pr.dokter_perujuk, pr.kd_dokter, d.nm_dokter, rp.status_lanjut, pr.nip, pj.png_jawab, rp.kd_pj, pl.nm_poli, '-' nmBangsal, ");
                sb1.append("CASE WHEN rp.kd_pj='U01' THEN IF(COUNT(bl.no_rawat) > 0, 'Sudah Lunas', 'Belum Bayar') ");
                sb1.append("ELSE IF(COUNT(pp.no_rawat) > 0, 'Piutang', 'Transaksi Belum Selesai') END cekBayar, IFNULL(CASE WHEN pr.berat_badan = '' THEN '-' ");
                sb1.append("WHEN LOWER(pr.berat_badan) LIKE '%kg%' OR LOWER(pr.berat_badan) LIKE '%gram%' THEN pr.berat_badan ");
                sb1.append("WHEN LENGTH(pr.berat_badan) >= 4 THEN CONCAT(pr.berat_badan, ' gram') ");
                sb1.append("ELSE CONCAT(pr.berat_badan, ' kg') END,'-') bb ");
                sb1.append("from periksa_radiologi pr inner join reg_periksa rp on rp.no_rawat=pr.no_rawat inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis ");
                sb1.append("inner join petugas pt on pt.nip=pr.nip inner join dokter d on d.kd_dokter=pr.kd_dokter inner join penjab pj on pj.kd_pj=rp.kd_pj ");
                sb1.append("inner join jns_perawatan_radiologi jpr on jpr.kd_jenis_prw=pr.kd_jenis_prw inner join poliklinik pl on pl.kd_poli=rp.kd_poli ");
                sb1.append("LEFT JOIN billing bl ON bl.no_rawat=pr.no_rawat LEFT JOIN piutang_pasien pp ON pp.no_rawat=pr.no_rawat where ");
                sb1.append("pr.tgl_periksa BETWEEN '" + Valid.SetTgl(namaPasJT) + "' AND '" + Valid.SetTgl(norkmJT) + "' AND rp.kd_poli = 'igdk' AND (" + notelpP + ") ");
                sb1.append("group by concat(pr.no_rawat,pr.tgl_periksa,pr.jam) " + keterP + " order by pr.tgl_periksa desc, pr.jam desc");
                ps1 = koneksi.prepareStatement(sb1.toString());
            } else {
                StringBuilder sb1 = new StringBuilder();
                sb1.append("select pr.no_rawat, rp.no_rkm_medis, p.nm_pasien, CONCAT(rp.umurdaftar,' ',rp.sttsumur) as umur_thn, pt.nama, pr.tgl_periksa, pr.jam, ");
                sb1.append("pr.dokter_perujuk, pr.kd_dokter, d.nm_dokter, rp.status_lanjut, pr.nip, pj.png_jawab, rp.kd_pj, pl.nm_poli, ifnull(b.nm_bangsal,'-') nmBangsal, ");
                sb1.append("CASE WHEN rp.kd_pj='U01' THEN IF(COUNT(bl.no_rawat) > 0, 'Sudah Lunas', 'Belum Bayar') ");
                sb1.append("ELSE IF(COUNT(pp.no_rawat) > 0, 'Piutang', 'Transaksi Belum Selesai') END cekBayar, IFNULL(CASE WHEN pr.berat_badan = '' THEN '-' ");
                sb1.append("WHEN LOWER(pr.berat_badan) LIKE '%kg%' OR LOWER(pr.berat_badan) LIKE '%gram%' THEN pr.berat_badan ");
                sb1.append("WHEN LENGTH(pr.berat_badan) >= 4 THEN CONCAT(pr.berat_badan, ' gram') ");
                sb1.append("ELSE CONCAT(pr.berat_badan, ' kg') END,'-') bb ");
                sb1.append("from periksa_radiologi pr inner join reg_periksa rp on rp.no_rawat=pr.no_rawat inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis ");
                sb1.append("inner join petugas pt on pt.nip=pr.nip inner join dokter d on d.kd_dokter=pr.kd_dokter inner join penjab pj on pj.kd_pj=rp.kd_pj ");
                sb1.append("inner join jns_perawatan_radiologi jpr on jpr.kd_jenis_prw=pr.kd_jenis_prw inner join poliklinik pl on pl.kd_poli=rp.kd_poli ");
                sb1.append("left join kamar_inap ki on ki.no_rawat=pr.no_rawat left join kamar k on k.kd_kamar=ki.kd_kamar ");
                sb1.append("left join bangsal b on b.kd_bangsal=k.kd_bangsal LEFT JOIN billing bl ON bl.no_rawat=pr.no_rawat ");
                sb1.append("LEFT JOIN piutang_pasien pp ON pp.no_rawat=pr.no_rawat where ");
                sb1.append("pr.tgl_periksa BETWEEN '" + Valid.SetTgl(namaPasJT) + "' AND '" + Valid.SetTgl(norkmJT) + "' AND (" + noPanjarP + ") ");
                sb1.append("group by concat(pr.no_rawat,pr.tgl_periksa,pr.jam) " + keterP + " order by pr.tgl_periksa desc, pr.jam desc");
                ps1 = koneksi.prepareStatement(sb1.toString());
            }
      
            StringBuilder sb2 = new StringBuilder();
            sb2.append("select jns_perawatan_radiologi.kd_jenis_prw,jns_perawatan_radiologi.nm_perawatan,periksa_radiologi.biaya ");
            sb2.append("from periksa_radiologi inner join jns_perawatan_radiologi on periksa_radiologi.kd_jenis_prw=jns_perawatan_radiologi.kd_jenis_prw where ");
            sb2.append("periksa_radiologi.no_rawat like ? and periksa_radiologi.tgl_periksa like ? and periksa_radiologi.jam like ?");
            ps2 = koneksi.prepareStatement(sb2.toString());

            StringBuilder sb3 = new StringBuilder();
            sb3.append("select beri_bhp_radiologi.kode_brng,ipsrsbarang.nama_brng,beri_bhp_radiologi.kode_sat,beri_bhp_radiologi.jumlah, ");
            sb3.append("beri_bhp_radiologi.total from beri_bhp_radiologi inner join ipsrsbarang on ipsrsbarang.kode_brng=beri_bhp_radiologi.kode_brng ");
            sb3.append("where beri_bhp_radiologi.no_rawat like ? and beri_bhp_radiologi.tgl_periksa like ? and beri_bhp_radiologi.jam like ?");
            ps3 = koneksi.prepareStatement(sb3.toString());

            StringBuilder sb4 = new StringBuilder();
            sb4.append("select periksa_radiologi.no_rawat,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,reg_periksa.umurdaftar umur,petugas.nama,periksa_radiologi.tgl_periksa,periksa_radiologi.jam,");
            sb4.append("periksa_radiologi.dokter_perujuk,periksa_radiologi.kd_dokter,periksa_radiologi.tgl_periksa,periksa_radiologi.jam,pasien.alamat,dokter.nm_dokter from periksa_radiologi inner join reg_periksa inner join pasien inner join petugas  inner join dokter ");
            sb4.append("on periksa_radiologi.no_rawat=reg_periksa.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis and periksa_radiologi.nip=petugas.nip and periksa_radiologi.kd_dokter=dokter.kd_dokter where ");
            sb4.append("periksa_radiologi.tgl_periksa like ? and periksa_radiologi.jam like ? and periksa_radiologi.no_rawat like ? group by concat(periksa_radiologi.no_rawat,periksa_radiologi.tgl_periksa,periksa_radiologi.jam)");
            ps4 = koneksi.prepareStatement(sb4.toString());

            StringBuilder sb5 = new StringBuilder();
            sb5.append("select hasil, diag_klinis_radiologi, kd_jenis_prw from hasil_radiologi where hasil_radiologi.no_rawat like ? and ");
            sb5.append("hasil_radiologi.tgl_periksa like ? and hasil_radiologi.jam like ? and hasil_radiologi.kd_jenis_prw like ?");
            ps5 = koneksi.prepareStatement(sb5.toString());
        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            ps4.setString(1, nmPemberiJT.toString());
            ps4.setString(2, noTelpJT.toString());
            ps4.setString(3, norawat.toString());
            rs = ps4.executeQuery();
            while (rs.next()) {
                Sequel.queryu("delete from temporary");
                koneksi.setAutoCommit(false);
                ps2.setString(1, rs.getString("no_rawat"));
                ps2.setString(2, rs.getString("tgl_periksa"));
                ps2.setString(3, rs.getString("jam"));
                rs2 = ps2.executeQuery();
                ttl = 0;
                while (rs2.next()) {
                    item = rs2.getDouble("biaya") + Sequel.cariIsiAngka("select sum(biaya_item) from template_laboratorium where kd_jenis_prw=?", rs2.getString("kd_jenis_prw"));
                    ttl = ttl + item;
                    Sequel.menyimpan("temporary", "'0','" + rs2.getString("nm_perawatan") + "','" + item + "','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Transaksi Biaya Rad");
                }
                Sequel.menyimpan("temporary", "'0','Total Biaya Pemeriksaan Radiologi','" + ttl + "','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Transaksi Biaya Rad");
                
                //proses data ke nota pdf
                crbyr = Sequel.cariIsi("select p.png_jawab from reg_periksa r inner join penjab p on p.kd_pj=r.kd_pj where r.no_rawat='" + norawat + "'");
                nmFile = "Nota Transaksi Radiologi " + norawat.replaceAll("/", "");

                Map<String, Object> param = new HashMap<>();
                param.put("namars", akses.getnamars());
                param.put("alamatrs", akses.getalamatrs());
                param.put("kotars", akses.getkabupatenrs());
                param.put("propinsirs", akses.getpropinsirs());
                param.put("kontakrs", akses.getkontakrs());
                param.put("emailrs", akses.getemailrs());
                param.put("logo", Sequel.cariGambar("select logo from setting"));
                param.put("norm", jmlNominalJT);
                param.put("nmpasien", angkaNomP);
                param.put("tglPeriksa", nmPemberiJT + ", Pukul : " + noTelpJT);
                param.put("drRad", userP);
                param.put("cara_byr", crbyr);
                param.put("tglNota", "Martapura, " + waktuSimpan);
                param.put("umur", Sequel.cariIsi("select concat(date_format(p.tgl_lahir,'%d/%m/%Y'),' (',rp.umurdaftar,' ',rp.sttsumur,'.)') from reg_periksa rp "
                        + "inner join pasien p on p.no_rkm_medis=rp.no_rkm_medis where rp.no_rawat='" + norawat + "'"));

                if (Sequel.cariInteger("select count(-1) from reg_periksa where no_rawat='" + norawat + "' and status_lanjut='Ralan'") > 0) {
                    param.put("nmUnit", Sequel.cariIsi("select pl.nm_poli from reg_periksa rp inner join poliklinik pl on pl.kd_poli=rp.kd_poli where rp.no_rawat='" + norawat + "'"));
                } else {
                    param.put("nmUnit", Sequel.cariIsi("select b.nm_bangsal from kamar_inap ki inner join kamar k on k.kd_kamar=ki.kd_kamar "
                            + "inner join bangsal b on b.kd_bangsal=k.kd_bangsal where ki.no_rawat='" + norawat + "' order by ki.tgl_masuk desc, ki.jam_masuk desc limit 1"));
                }

                if (akses.getadmin() == true) {
                    nmpetgs = "...................";
                } else {
                    nmpetgs = Sequel.cariIsi("select nama from petugas where nip='" + akses.getkode() + "'");
                }

                param.put("petugas_ksr", "( " + nmpetgs + " )");

                if (akses.getadmin() == true) {
                    Valid.MyReportToPDF("rptNotaRadiologi.jasper", "report", "::[ Nota Transaksi Radiologi ]::",
                            " SELECT temp1, FORMAT(temp2, 0) biaya, (SELECT FORMAT(temp2, 0) FROM temporary WHERE temp1 = 'Total Biaya Pemeriksaan Radiologi') total_byr "
                            + "FROM temporary WHERE temp1 NOT LIKE '%biaya%'", param, Sequel.cariFolderTte(), nmFile);
                } else {
                    String isi = "";
                    isi = Sequel.cariIsi("select replace(kalimat_qrcode,kalimat_qrcode,"
                            + "'" + Valid.kalimatQRcode(Sequel.cariIsi("select jenis_dokumen from kalimat_tte where kode='011'"),
                                    "Nota Transaksi Radiologi", nmpetgs,
                                    Sequel.cariIsi("select date_format('" + Valid.SetTgl(waktuSimpan + "") + "','%d/%m/%Y')"),
                                    Sequel.cariIsi("select time(now())")) + "') from kalimat_tte where kode='011'");

                    Valid.cetakQrTte(isi, Sequel.cariFolderTte(), "QRTte.jpg", "select logo from setting");
                    Sequel.queryu("delete from setting_qr where judul = 'QRTte'");
                    Sequel.menyimpanQr("setting_qr", "'QRTte'", "file QRCode TTE Nota Transaksi Radiologi", Sequel.cariFolderPrintTte());
                    param.put("lokasiQr", Sequel.cariGambar("select gambar from setting_qr where judul = 'QRTte'"));
                    param.put("kalimatTte", Sequel.cariIsi("select replace(kalimat_footer,'##jns_dokumen##',jenis_dokumen) from kalimat_tte where kode='011'"));

                    Valid.MyReportToPDF("rptNotaRadiologiQr.jasper", "report", "::[ Nota Transaksi Radiologi ]::",
                            " SELECT temp1, FORMAT(temp2, 0) biaya, (SELECT FORMAT(temp2, 0) FROM temporary WHERE temp1 = 'Total Biaya Pemeriksaan Radiologi') total_byr "
                            + "FROM temporary WHERE temp1 NOT LIKE '%biaya%'", param, Sequel.cariFolderTte(), nmFile);
                }              
                
                TPesan.setText("Nota Pembayaran Pemeriksaan Radiologi (" + Sequel.cariIsi("select concat(p.no_rkm_medis,' - ',p.nm_pasien) from reg_periksa r "
                        + "inner join pasien p on p.no_rkm_medis=r.no_rkm_medis where r.no_rawat='" + norawat + "'") + ")");
                TnoWa.setText("");
                TnmFile.setText(nmFile);
                TnoWa.requestFocus();
                //-------------------------------
                koneksi.setAutoCommit(true);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
}
