/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLhtBiaya.java
 *
 * Created on 12 Jul 10, 16:21:34
 */

package keuangan;
import fungsi.WarnaTable;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import simrskhanza.frmUtama;

/**
 *
 * @author perpustakaan
 */
public final class DlgPaymentPoint extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i = 0, total = 0;
    private String nonota = "", dialog_simpan = "";
    private frmUtama formUtama;

    /** Creates new form DlgLhtBiaya
     * @param parent
     * @param modal */
    public DlgPaymentPoint(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //data di tabel grid rata tengah
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        this.setLocation(8,1);
        setSize(885,674);

        Object[] rowRwJlDr = {"No.", "Tanggal", "Shift", "No.Rawat/No.Nota", "No. RM - Nama Pasien", "Pembayaran",
            "Poli/Inst./Rg. Rawat/Trans.", "Petugas Kasir", "jlh_bayar"};
        tabMode=new DefaultTableModel(null,rowRwJlDr){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
             Class[] types = new Class[] {
                 java.lang.String.class, java.lang.String.class, java.lang.String.class,
                 java.lang.String.class, java.lang.String.class, java.lang.Double.class,
                 java.lang.String.class, java.lang.String.class, java.lang.String.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        
        Tabel.setModel(tabMode);
        Tabel.setPreferredScrollableViewportSize(new Dimension(500,500));
        Tabel.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 9; i++) {
            TableColumn column = Tabel.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(50);
            } else if (i == 1) {
                column.setPreferredWidth(135);
            } else if (i == 2) {
                column.setPreferredWidth(70);
            } else if (i == 3) {
                column.setPreferredWidth(125);
            } else if (i == 4) {
                column.setPreferredWidth(300);
            } else if (i == 5) {
                column.setPreferredWidth(110);
            } else if (i == 6) {
                column.setPreferredWidth(260);
            } else if (i == 7) {
                column.setPreferredWidth(220);
            } else if (i == 8) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }
        Tabel.setDefaultRenderer(Object.class, new WarnaTable());
        //ini posisi kolom yang datanya ingin rata tengah
        Tabel.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        Tabel.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        Tabel.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnDownloadData = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        Tabel = new widget.Table();
        panelGlass5 = new widget.panelisi();
        label17 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel11 = new javax.swing.JLabel();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass6 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        jLabel10 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        label12 = new widget.Label();
        Ttotal = new widget.Label();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jPopupMenu1.setName("jPopupMenu1"); // NOI18N
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(140, 28));

        MnDownloadData.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnDownloadData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/export-excel.png"))); // NOI18N
        MnDownloadData.setText("Download Data");
        MnDownloadData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnDownloadData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnDownloadData.setIconTextGap(5);
        MnDownloadData.setName("MnDownloadData"); // NOI18N
        MnDownloadData.setPreferredSize(new java.awt.Dimension(140, 28));
        MnDownloadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDownloadDataActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnDownloadData);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Payment Point ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        Tabel.setComponentPopupMenu(jPopupMenu1);
        Tabel.setName("Tabel"); // NOI18N
        Tabel.getTableHeader().setReorderingAllowed(false);
        Scroll.setViewportView(Tabel);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label17.setForeground(new java.awt.Color(0, 0, 0));
        label17.setText("Key Word :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass5.add(label17);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(200, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass5.add(TCari);

        BtnCari.setForeground(new java.awt.Color(0, 0, 0));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setText("Tampilkan Data");
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(130, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnCari);

        BtnAll.setForeground(new java.awt.Color(0, 0, 0));
        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setText("Semua Data");
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(120, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnAll);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass5.add(jLabel11);

        BtnPrint.setForeground(new java.awt.Color(0, 0, 0));
        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setEnabled(false);
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnPrint);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(55, 45));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setForeground(new java.awt.Color(0, 0, 0));
        label11.setText("Tgl. Pembayaran :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass6.add(label11);

        Tgl1.setEditable(false);
        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass6.add(Tgl1);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("s.d");
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass6.add(jLabel10);

        Tgl2.setEditable(false);
        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass6.add(Tgl2);

        label12.setForeground(new java.awt.Color(0, 0, 0));
        label12.setText("Total Uang Masuk :");
        label12.setName("label12"); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass6.add(label12);

        Ttotal.setForeground(new java.awt.Color(0, 0, 0));
        Ttotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ttotal.setText("0");
        Ttotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ttotal.setName("Ttotal"); // NOI18N
        Ttotal.setPreferredSize(new java.awt.Dimension(250, 23));
        panelGlass6.add(Ttotal);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            //TCari.requestFocus();
        } else if (tabMode.getRowCount() != 0) {
            Sequel.AutoComitFalse();
            Sequel.queryu("delete from temporary");
            for (int r = 0; r < tabMode.getRowCount(); r++) {
                Sequel.menyimpan("temporary", "'0','"
                        + tabMode.getValueAt(r, 0).toString().replaceAll("'", "`") + "','"
                        + tabMode.getValueAt(r, 1).toString().replaceAll("'", "`") + "','"
                        + tabMode.getValueAt(r, 2).toString().replaceAll("'", "`") + "','"
                        + tabMode.getValueAt(r, 3).toString().replaceAll("'", "`") + "','"
                        + tabMode.getValueAt(r, 4).toString().replaceAll("'", "`") + "','"
                        + Valid.SetAngka(Double.parseDouble(tabMode.getValueAt(r, 5).toString())) + "','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "data");
            }
            Sequel.AutoComitTrue();
            Map<String, Object> param = new HashMap<>();
            param.put("namars", akses.getnamars());
            param.put("alamatrs", akses.getalamatrs());
            param.put("kotars", akses.getkabupatenrs());
            param.put("propinsirs", akses.getpropinsirs());
            param.put("shift", "Semua Sift");
            param.put("kontakrs", akses.getkontakrs());
            param.put("emailrs", akses.getemailrs());
            param.put("logo", Sequel.cariGambar("select logo from setting"));
            Valid.MyReport("rptPaymentPoint.jasper", "report", "::[ Payment Point ]::",
                    "select * from temporary order by no asc", param);
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl1,BtnKeluar);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        frmUtama.getInstance().tutupDialogDiPanelUtama(this);
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            frmUtama.getInstance().tutupDialogDiPanelUtama(this);
        } else {
            Valid.pindah(evt, BtnKeluar, TCari);
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnPrint);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            tampil();
            this.setCursor(Cursor.getDefaultCursor());
        }else{
            Valid.pindah(evt,TCari, BtnPrint);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void MnDownloadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDownloadDataActionPerformed
        if (Tabel.getRowCount() != 0) {
            downloadData();
        } else {
            JOptionPane.showMessageDialog(null, "Data masih kosong,..!!!");
        }
    }//GEN-LAST:event_MnDownloadDataActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgPaymentPoint dialog = new DlgPaymentPoint(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private javax.swing.JMenuItem MnDownloadData;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.Table Tabel;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Label Ttotal;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label17;
    private widget.panelisi panelGlass5;
    private widget.panelisi panelGlass6;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        total = 0;
        try {
            if (akses.getadmin() == true) {
                ps = koneksi.prepareStatement("SELECT ts.no_nota, ts.nama_pasien, ts.jumlah_bayar, DATE_FORMAT(ts.tgl_bayar,'%d-%m-%Y %H:%i Wita') tgl_byr, ck.shift, "
                        + "CASE WHEN rp.status_lanjut = 'Ralan' THEN pl.nm_poli WHEN rp.status_lanjut = 'Ranap' THEN b.nm_bangsal ELSE 'Penjualan Obat Langsung' END nmunit, pg.nama ptgs_kasir, "
                        + "CASE WHEN rp.no_rkm_medis IS NOT NULL AND rp.no_rkm_medis <> '' THEN rp.no_rkm_medis ELSE '-' END norm "
                        + "FROM tagihan_sadewa ts inner join pegawai pg on pg.nik=ts.petugas "
                        + "LEFT JOIN reg_periksa rp ON rp.no_rawat = ts.no_nota "
                        + "LEFT JOIN poliklinik pl ON pl.kd_poli = rp.kd_poli "
                        + "LEFT JOIN kamar_inap ki ON ki.no_rawat = ts.no_nota AND ki.stts_pulang NOT IN ('-','Pindah kamar') "
                        + "LEFT JOIN kamar k ON k.kd_kamar = ki.kd_kamar "
                        + "LEFT JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal "
                        + "LEFT JOIN closing_kasir ck ON "
                        + "((ck.jam_masuk <= ck.jam_pulang AND TIME(ts.tgl_bayar) BETWEEN ck.jam_masuk AND ck.jam_pulang) OR "
                        + "(ck.jam_masuk > ck.jam_pulang AND (TIME(ts.tgl_bayar) >= ck.jam_masuk OR TIME(ts.tgl_bayar) <= ck.jam_pulang))) where "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.nama_pasien like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.no_nota like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and pg.nama like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ck.shift like ? order by ts.tgl_bayar, ts.no_nota");
            } else {
                ps = koneksi.prepareStatement("SELECT ts.no_nota, ts.nama_pasien, ts.jumlah_bayar, DATE_FORMAT(ts.tgl_bayar,'%d-%m-%Y %H:%i Wita') tgl_byr, ck.shift, "
                        + "CASE WHEN rp.status_lanjut = 'Ralan' THEN pl.nm_poli WHEN rp.status_lanjut = 'Ranap' THEN b.nm_bangsal ELSE 'Penjualan Obat Langsung' END nmunit, pg.nama ptgs_kasir, "
                        + "CASE WHEN rp.no_rkm_medis IS NOT NULL AND rp.no_rkm_medis <> '' THEN rp.no_rkm_medis ELSE '-' END norm "
                        + "FROM tagihan_sadewa ts inner join pegawai pg on pg.nik=ts.petugas "
                        + "LEFT JOIN reg_periksa rp ON rp.no_rawat = ts.no_nota "
                        + "LEFT JOIN poliklinik pl ON pl.kd_poli = rp.kd_poli "
                        + "LEFT JOIN kamar_inap ki ON ki.no_rawat = ts.no_nota AND ki.stts_pulang NOT IN ('-','Pindah kamar') "
                        + "LEFT JOIN kamar k ON k.kd_kamar = ki.kd_kamar "
                        + "LEFT JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal "
                        + "LEFT JOIN closing_kasir ck ON "
                        + "((ck.jam_masuk <= ck.jam_pulang AND TIME(ts.tgl_bayar) BETWEEN ck.jam_masuk AND ck.jam_pulang) OR "
                        + "(ck.jam_masuk > ck.jam_pulang AND (TIME(ts.tgl_bayar) >= ck.jam_masuk OR TIME(ts.tgl_bayar) <= ck.jam_pulang))) where "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.petugas='" + akses.getkode() + "' and ts.nama_pasien like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.petugas='" + akses.getkode() + "' and ts.no_nota like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.petugas='" + akses.getkode() + "' and pg.nama like ? or "
                        + "date(ts.tgl_bayar) between ? and ? and ts.status = 'sudah' and ts.petugas='" + akses.getkode() + "' and ck.shift like ? order by ts.tgl_bayar, ts.no_nota");
            }
            try {
                ps.setString(1, Valid.SetTgl(Tgl1.getSelectedItem() + ""));
                ps.setString(2, Valid.SetTgl(Tgl2.getSelectedItem() + ""));
                ps.setString(3, "%" + TCari.getText().trim() + "%");
                ps.setString(4, Valid.SetTgl(Tgl1.getSelectedItem() + ""));
                ps.setString(5, Valid.SetTgl(Tgl2.getSelectedItem() + ""));
                ps.setString(6, "%" + TCari.getText().trim() + "%");
                ps.setString(7, Valid.SetTgl(Tgl1.getSelectedItem() + ""));
                ps.setString(8, Valid.SetTgl(Tgl2.getSelectedItem() + ""));
                ps.setString(9, "%" + TCari.getText().trim() + "%");
                ps.setString(10, Valid.SetTgl(Tgl1.getSelectedItem() + ""));
                ps.setString(11, Valid.SetTgl(Tgl2.getSelectedItem() + ""));
                ps.setString(12, "%" + TCari.getText().trim() + "%");
                rs = ps.executeQuery();
                i = 1;
                while (rs.next()) {
                    nonota = Sequel.cariIsi("select no_nota from nota_inap where no_rawat=?", rs.getString("no_nota"));
                    if (nonota.equals("")) {
                        nonota = Sequel.cariIsi("select no_nota from nota_jalan where no_rawat=?", rs.getString("no_nota"));
                        if (nonota.equals("")) {
                            nonota = rs.getString("no_nota");
                        }
                    }
                    
                    tabMode.addRow(new Object[]{
                        i + ".", 
                        rs.getString("tgl_byr"), 
                        rs.getString("shift"), 
                        nonota, 
                        rs.getString("norm") + " - " + rs.getString("nama_pasien"), 
                        rs.getDouble("jumlah_bayar"),
                        rs.getString("nmunit"),
                        rs.getString("ptgs_kasir"),
                        rs.getString("jumlah_bayar")
                    });
                    i++;
                    
                    if (total == 0) {
                        total = Integer.parseInt(rs.getString("jumlah_bayar"));
                    } else {
                        total = total + Integer.parseInt(rs.getString("jumlah_bayar"));
                    }
                    Ttotal.setText("Rp. " + Valid.SetAngka(total));
                }                
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }        
    }
    
    private void downloadData() {
        Sequel.AutoComitFalse();
        Sequel.queryu("delete from temporary1");
        int row = tabMode.getRowCount();
        for (int r = 0; r < row; r++) {
            Sequel.menyimpan("temporary1", "'"
                    + tabMode.getValueAt(r, 0).toString() + "','"
                    + tabMode.getValueAt(r, 1).toString() + "','"
                    + tabMode.getValueAt(r, 2).toString() + "','"
                    + tabMode.getValueAt(r, 3).toString() + "','"
                    + tabMode.getValueAt(r, 4).toString().replaceAll("'", "") + "','"
                    + tabMode.getValueAt(r, 8).toString() + "','"
                    + tabMode.getValueAt(r, 6).toString() + "','"
                    + tabMode.getValueAt(r, 7).toString().replaceAll("'", "") + "','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''", "Data");
        }
        Sequel.AutoComitTrue();

        dialog_simpan = Valid.openDialog();
        if (Valid.MyReportToExcelBoolean("SELECT temp1 'No.', temp2 'Tanggal', temp3 'Shift', temp4 'No.Rawat/No.Nota', "
                + "temp5 'No. RM - Nama Pasien', temp6 'Pembayaran', temp7 'Poli/Inst./Rg. Rawat/Trans.', temp8 'Petugas Kasir' from temporary1", dialog_simpan) == true) {
            JOptionPane.showMessageDialog(null, "Data payment point berhasil diexport menjadi file excel,..!!!");
        } else {
            JOptionPane.showMessageDialog(null, "Data payment point gagal diexport menjadi file excel,..!!!");
        }
    }
}
