/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package kepegawaian;

import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dosen
 */
public final class DlgDepartemen extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private validasi Valid = new validasi();
    private Connection koneksi = koneksiDB.condb();    
    private PreparedStatement ps;
    private ResultSet rs;
    private sekuel Sequel = new sekuel();
    private String cekStatus = "";
    private int x = 0;
    
    /** Creates new form DlgPenyakit
     * @param parent
     * @param modal */
    
    public DlgDepartemen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);

        String[] row = {"Kode Departemen", "Nama Departemen", "Status", "Nama Gedung"};
        
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        
        tbDepartemen.setModel(tabMode);
        tbDepartemen.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbDepartemen.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 4; i++) {
            TableColumn column = tbDepartemen.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(110);
            } else if (i == 1) {
                column.setPreferredWidth(400);
            } else if (i == 2) {
                column.setPreferredWidth(80);
            } else if (i == 3) {
                column.setPreferredWidth(300);
            }
        }
        tbDepartemen.setDefaultRenderer(Object.class, new WarnaTable());
        
        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
        Tkode.setDocument(new batasInput((int) 4).getKata(Tkode));
        TnmDepartemen.setDocument(new batasInput((int) 75).getKata(TnmDepartemen));
        
        if(koneksiDB.cariCepat().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
            });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelisi4 = new widget.panelisi();
        label11 = new widget.Label();
        Tkode = new widget.TextBox();
        label12 = new widget.Label();
        TnmDepartemen = new widget.TextBox();
        label13 = new widget.Label();
        cmbStatus = new widget.ComboBox();
        label14 = new widget.Label();
        cmbGedung = new widget.ComboBox();
        Scroll = new widget.ScrollPane();
        tbDepartemen = new widget.Table();
        panelisi5 = new widget.panelisi();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        panelisi6 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Departemen & Mapping Gedung ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi4.setName("panelisi4"); // NOI18N
        panelisi4.setPreferredSize(new java.awt.Dimension(100, 105));
        panelisi4.setLayout(null);

        label11.setForeground(new java.awt.Color(0, 0, 0));
        label11.setText("Kode Departemen :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi4.add(label11);
        label11.setBounds(0, 10, 140, 23);

        Tkode.setForeground(new java.awt.Color(0, 0, 0));
        Tkode.setName("Tkode"); // NOI18N
        Tkode.setPreferredSize(new java.awt.Dimension(312, 23));
        panelisi4.add(Tkode);
        Tkode.setBounds(145, 10, 70, 23);

        label12.setForeground(new java.awt.Color(0, 0, 0));
        label12.setText("Nama Departemen :");
        label12.setName("label12"); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi4.add(label12);
        label12.setBounds(0, 38, 140, 23);

        TnmDepartemen.setForeground(new java.awt.Color(0, 0, 0));
        TnmDepartemen.setName("TnmDepartemen"); // NOI18N
        TnmDepartemen.setPreferredSize(new java.awt.Dimension(312, 23));
        panelisi4.add(TnmDepartemen);
        TnmDepartemen.setBounds(145, 38, 530, 23);

        label13.setForeground(new java.awt.Color(0, 0, 0));
        label13.setText("Status Departemen :");
        label13.setName("label13"); // NOI18N
        label13.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi4.add(label13);
        label13.setBounds(0, 66, 140, 23);

        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aktif", "Non Aktif" }));
        cmbStatus.setName("cmbStatus"); // NOI18N
        panelisi4.add(cmbStatus);
        cmbStatus.setBounds(145, 66, 80, 23);

        label14.setForeground(new java.awt.Color(0, 0, 0));
        label14.setText("Gedung Rawat Inap/RS :");
        label14.setName("label14"); // NOI18N
        label14.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi4.add(label14);
        label14.setBounds(225, 66, 140, 23);

        cmbGedung.setForeground(new java.awt.Color(0, 0, 0));
        cmbGedung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "BAYI", "AR-RAUDAH", "APOTEK", "GUDANG FARMASI", "IBS", "VK BERSALIN", "LABORATORIUM", "RADIOLOGI", "KAMAR JENAZAH", "RAWAT JALAN", "IPSRS", "SANITASI", "REKAM MEDIK", "CSSD", "DAPUR", "MANAJEMEN", "PONEK - VK BERSALIN" }));
        cmbGedung.setName("cmbGedung"); // NOI18N
        cmbGedung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbGedungMouseReleased(evt);
            }
        });
        panelisi4.add(cmbGedung);
        cmbGedung.setBounds(370, 66, 230, 23);

        internalFrame1.add(panelisi4, java.awt.BorderLayout.PAGE_START);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbDepartemen.setName("tbDepartemen"); // NOI18N
        tbDepartemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDepartemenMouseClicked(evt);
            }
        });
        tbDepartemen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDepartemenKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbDepartemen);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi5.setName("panelisi5"); // NOI18N
        panelisi5.setPreferredSize(new java.awt.Dimension(100, 86));
        panelisi5.setLayout(new java.awt.BorderLayout());

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setForeground(new java.awt.Color(0, 0, 0));
        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi3.add(label9);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(312, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi3.add(TCari);

        BtnCari.setForeground(new java.awt.Color(0, 0, 0));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setText("Tampilkan Data");
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(130, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi3.add(BtnCari);

        BtnAll.setForeground(new java.awt.Color(0, 0, 0));
        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setText("Semua Data");
        BtnAll.setToolTipText("2Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(110, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi3.add(BtnAll);

        label10.setForeground(new java.awt.Color(0, 0, 0));
        label10.setText("Record :");
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label10);

        LCount.setForeground(new java.awt.Color(0, 0, 0));
        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi3.add(LCount);

        panelisi5.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        panelisi6.setName("panelisi6"); // NOI18N
        panelisi6.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        BtnSimpan.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 23));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelisi6.add(BtnSimpan);

        BtnBatal.setForeground(new java.awt.Color(0, 0, 0));
        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 23));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelisi6.add(BtnBatal);

        BtnHapus.setForeground(new java.awt.Color(0, 0, 0));
        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('G');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+G");
        BtnHapus.setIconTextGap(3);
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 23));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelisi6.add(BtnHapus);

        BtnEdit.setForeground(new java.awt.Color(0, 0, 0));
        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setIconTextGap(3);
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 23));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelisi6.add(BtnEdit);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(90, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi6.add(BtnKeluar);

        panelisi5.add(panelisi6, java.awt.BorderLayout.CENTER);

        internalFrame1.add(panelisi5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tbDepartemen.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil();
}//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnAllActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnCari, TCari);
        }
}//GEN-LAST:event_BtnAllKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Sequel.cariIsiComboDB("SELECT nm_gedung FROM bangsal WHERE nm_gedung<>'-' and status='1' GROUP BY nm_gedung ORDER BY nm_gedung", cmbGedung);
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void tbDepartemenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDepartemenKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
    }//GEN-LAST:event_tbDepartemenKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (Tkode.getText().trim().equals("")) {
            Valid.textKosong(Tkode, "Kode Departemen");
        } else if (TnmDepartemen.getText().trim().equals("")) {
            Valid.textKosong(TnmDepartemen, "Nama Departemen");
        } else {
            cekStatus = "";
            Valid.autoNomerDokter("departemen", "D", 3, Tkode);
            if (cmbStatus.getSelectedIndex() == 0) {
                cekStatus = "1";
            } else {
                cekStatus = "0";
            }

            if (Sequel.menyimpantf("departemen", "'" + Tkode.getText() + "','" + TnmDepartemen.getText() + "','" + cekStatus + "'", "Departemen") == true) {
                Sequel.menyimpan("mapping_departemen_gedung", "?,?", "Mapping Departemen & Gedung", 2, new String[]{
                    Tkode.getText(), cmbGedung.getSelectedItem().toString()});
                
                emptTeks();
                tampil();
            }
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
        tampil();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            emptTeks();
        }
    }//GEN-LAST:event_BtnBatalKeyPressed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if (tbDepartemen.getSelectedRow() > -1) {
            if (Tkode.getText().trim().equals("")) {
                Valid.textKosong(Tkode, "Kode Departemen");
            } else if (TnmDepartemen.getText().trim().equals("")) {
                Valid.textKosong(TnmDepartemen, "Nama Departemen");
            } else {
                cekStatus = "";
                if (cmbStatus.getSelectedIndex() == 0) {
                    cekStatus = "1";
                } else {
                    cekStatus = "0";
                }

                if (Sequel.mengedittf("departemen", "dep_id=?", "dep_id=?, nama=?, aktif=?", 4, new String[]{
                    Tkode.getText(), TnmDepartemen.getText(), cekStatus,
                    tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString()
                }) == true) {
                    Sequel.mengedit("mapping_departemen_gedung", "dep_id='" + tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString() + "'",
                            "dep_id='" + Tkode.getText() + "', nm_gedung='" + cmbGedung.getSelectedItem().toString() + "'");

                    Sequel.mengedit("pegawai", "departemen='" + tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString() + "'",
                            "departemen='" + Tkode.getText() + "', indexins='" + Tkode.getText() + "'");

                    emptTeks();
                    tampil();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih salah satu datanya terlebih dahulu..!!");
            tbDepartemen.requestFocus();
            tampil();
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnEditActionPerformed(null);
        }
    }//GEN-LAST:event_BtnEditKeyPressed

    private void tbDepartemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDepartemenMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
    }//GEN-LAST:event_tbDepartemenMouseClicked

    private void cmbGedungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbGedungMouseReleased
        AutoCompleteDecorator.decorate(cmbGedung);
    }//GEN-LAST:event_cmbGedungMouseReleased

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tbDepartemen.getSelectedRow() > -1) {
            x = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin data akan dihapus..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                if (Sequel.cariInteger("select count(-1) from pegawai where departemen='" + Tkode.getText() + "'") > 0
                        || Sequel.cariInteger("select count(-1) from satu_sehat_mapping_departemen where dep_id='" + Tkode.getText() + "'") > 0 
                        || Sequel.cariInteger("select count(-1) from pegawai where indexins='" + Tkode.getText() + "'") > 0 
                        || Sequel.cariInteger("select count(-1) from indexins where dep_id='" + Tkode.getText() + "'") > 0 
                        || Sequel.cariInteger("select count(-1) from jam_jaga where dep_id='" + Tkode.getText() + "'") > 0) {
                    JOptionPane.showMessageDialog(null, "Kode departemen tersebut masih terpakai ditabel pegawai, satu_sehat_mapping_departemen, indexins, jam_jaga..!!");
                    tampil();
                } else {
                    if (Sequel.queryu2tf("delete from departemen where dep_id=?", 1, new String[]{
                        tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString()
                    }) == true) {
                        Sequel.queryu("delete from mapping_departemen_gedung where dep_id='" + tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString() + "' "
                                + "and nm_gedung='" + cmbGedung.getSelectedItem().toString() + "'");

                        tampil();
                        emptTeks();
                    } else {
                        JOptionPane.showMessageDialog(null, "Gagal menghapus..!!");
                    }
                }
            } else {
                tampil();
                emptTeks();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih salah satu datanya terlebih dahulu..!!");
            tampil();
            tbDepartemen.requestFocus();
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgDepartemen dialog = new DlgDepartemen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.TextBox Tkode;
    private widget.TextBox TnmDepartemen;
    private widget.ComboBox cmbGedung;
    private widget.ComboBox cmbStatus;
    private widget.InternalFrame internalFrame1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.panelisi panelisi4;
    private widget.panelisi panelisi5;
    private widget.panelisi panelisi6;
    private widget.Table tbDepartemen;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        Valid.tabelKosong(tabMode);
        try {
            ps = koneksi.prepareStatement("select d.*, if(d.aktif='0','Non Aktif','Aktif') status, ifnull(m.nm_gedung,'- Belum Dimapping -') gedung from departemen d "
                    + "inner join mapping_departemen_gedung m on m.dep_id=d.dep_id "
                    + "where d.dep_id like ? or d.nama like ? or d.aktif like ? or m.nm_gedung like ? order by d.dep_id");
            try {
                ps.setString(1, "%" + TCari.getText().trim() + "%");
                ps.setString(2, "%" + TCari.getText().trim() + "%");
                ps.setString(3, "%" + TCari.getText().trim() + "%");
                ps.setString(4, "%" + TCari.getText().trim() + "%");
                rs = ps.executeQuery();
                while (rs.next()) {
                    tabMode.addRow(new String[]{
                        rs.getString("dep_id"),
                        rs.getString("nama"),
                        rs.getString("status"),
                        rs.getString("gedung")
                    });
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        LCount.setText("" + tabMode.getRowCount());
    }
    
    public void emptTeks() {
        Tkode.setText("");
        TnmDepartemen.setText("");
        cmbStatus.setSelectedIndex(0);
        cmbGedung.setSelectedIndex(0);
        Valid.autoNomerDokter("departemen","D",3,Tkode);
    }
    
    private void getData() {
        if (tbDepartemen.getSelectedRow() != -1) {
            Tkode.setText(tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 0).toString());
            TnmDepartemen.setText(tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 1).toString());
            cmbStatus.setSelectedItem(tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 2).toString());

            if (tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 3).toString().equals("- Belum Dimapping -")) {
                cmbGedung.setSelectedIndex(0);
            } else {
                cmbGedung.setSelectedItem(tbDepartemen.getValueAt(tbDepartemen.getSelectedRow(), 3).toString());
            }
        }
    }
}